# Generated by Django 5.2.15 on 2026-06-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link video YouTube/Vimeo (opsional). Tempel link biasa, mis. https://www.youtube.com/watch?v=XXXX'),
        ),
    ]
