# Generated by Django 5.2.15 on 2026-06-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text='Lesson content (HTML/Markdown allowed).'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo video link (optional). Paste a normal link, e.g. https://www.youtube.com/watch?v=XXXX'),
        ),
    ]
