# Generated by Django 5.2.15 on 2026-06-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_content_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text="Lesson content. Supports **bold**, *italic*, `code`, '- ' bullet lists, blank lines for paragraphs, and LaTeX math: \\(inline\\) or \\[display\\]."),
        ),
    ]
