# Generated by Django 5.2.15 on 2026-06-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('social', 'Social Studies'), ('rla', 'Language Arts'), ('other', 'Other')], default='math', max_length=20),
        ),
    ]
