from django.core.management.base import BaseCommand
from courses.models import Lesson

LESSONS = [
    (
        1,
        "**Quadratic Equations**\n\n"
        "Quadratic equations are among the most heavily tested topics in SAT Advanced Math. A **quadratic equation** is any equation that can be written in **standard form**: ax² + bx + c = 0, where a ≠ 0. The graph of a quadratic is a U-shaped curve called a **parabola**. Understanding how to solve quadratic equations efficiently is essential for earning a top SAT Math score.\n\n"
        "**Method 1 — Factoring**\n\n"
        "Factoring is the fastest method when it works. The goal is to rewrite ax² + bx + c as a product of two binomials. For equations where a = 1, find two numbers p and q such that p × q = c and p + q = b. Then factor as (x + p)(x + q) = 0 and apply the **Zero Product Property**: if a product equals zero, at least one factor must equal zero. Set each factor to zero and solve.\n\n"
        "Example: Solve x² − 5x + 6 = 0. Find two numbers that multiply to 6 and add to −5: those are −2 and −3. Factor: (x − 2)(x − 3) = 0. Solutions: x = 2 or x = 3.\n\n"
        "**Method 2 — Quadratic Formula**\n\n"
        "When factoring is not obvious, use the **quadratic formula**:\n\n"
        "x = (−b ± √(b² − 4ac)) / (2a)\n\n"
        "This formula is derived by completing the square on the general form ax² + bx + c = 0. Divide through by a, move c/a to the right, add (b/2a)² to both sides to complete the square, and simplify — the quadratic formula falls out naturally. Always identify a, b, and c carefully before substituting.\n\n"
        "**Method 3 — Completing the Square**\n\n"
        "**Completing the square** converts the equation into the form (x + d)² = e, which you solve by taking square roots. Steps: (1) Move c to the right side. (2) Divide every term by a if a ≠ 1. (3) Add (b/2)² to both sides. (4) Write the left side as a perfect square. (5) Take the square root of both sides (include ±). (6) Solve for x.\n\n"
        "Example: Solve x² + 6x − 7 = 0. Move −7: x² + 6x = 7. Add (3)² = 9: x² + 6x + 9 = 16. Factor: (x + 3)² = 16. Take square roots: x + 3 = ±4. So x = 1 or x = −7.\n\n"
        "**The Discriminant**\n\n"
        "The expression under the radical in the quadratic formula, b² − 4ac, is called the **discriminant** and tells you how many real solutions exist without fully solving the equation:\n\n"
        "- b² − 4ac > 0 → two distinct real roots (the parabola crosses the x-axis twice)\n"
        "- b² − 4ac = 0 → exactly one repeated real root (the parabola touches the x-axis at the vertex)\n"
        "- b² − 4ac < 0 → no real roots (the parabola does not cross the x-axis)\n\n"
        "**SAT-Style Worked Examples**\n\n"
        "Example 1: Solve 2x² + 3x − 2 = 0 by factoring. Multiply a × c = 2 × (−2) = −4. Find two numbers that multiply to −4 and add to 3: they are 4 and −1. Rewrite: 2x² + 4x − x − 2 = 0. Factor by grouping: 2x(x + 2) − 1(x + 2) = 0, giving (2x − 1)(x + 2) = 0. Solutions: x = 1/2 or x = −2.\n\n"
        "Example 2: How many real solutions does 3x² − 6x + 3 = 0 have? Compute the discriminant: (−6)² − 4(3)(3) = 36 − 36 = 0. Exactly one real (repeated) solution: x = 1.\n\n"
        "Example 3: A ball’s height (in feet) is given by h(t) = −4t² + 8t + 5. At what times is the ball at ground level (h = 0)? Solve −4t² + 8t + 5 = 0, or 4t² − 8t − 5 = 0. Discriminant: 64 + 80 = 144. t = (8 ± 12) / 8. So t = 2.5 or t = −0.5. Reject the negative time; the ball hits the ground at t = 2.5 seconds.\n\n"
        "**Common Traps**\n\n"
        "- Forgetting the ± in the quadratic formula — always write both roots.\n"
        "- Sign errors when factoring: (x − 3)(x + 2) = 0 gives x = 3 and x = −2, not the opposite.\n"
        "- Dividing by x early (e.g., x² = 3x becomes x = 3 only — you lose the x = 0 solution).\n\n"
        "**SAT Tip:** On the Digital SAT, factoring is usually the fastest method when the roots are integers or simple fractions. If you cannot spot the factors within 20 seconds, switch directly to the quadratic formula. Never waste time forcing factoring on a messy problem."
    ),
    (
        2,
        "**Quadratic Functions and Parabolas**\n\n"
        "A **quadratic function** is a function of the form f(x) = ax² + bx + c. Its graph is a **parabola** — a symmetric, U-shaped curve. Understanding the structure of a parabola lets you answer SAT questions about maximum values, zeros, and real-world models without plugging in many numbers.\n\n"
        "**Vertex Form**\n\n"
        "The most informative way to write a quadratic function is **vertex form**: f(x) = a(x − h)² + k. The **vertex** is the point (h, k), and it represents the minimum of the parabola when a > 0 (opens upward) or the maximum when a < 0 (opens downward). The **axis of symmetry** is the vertical line x = h, which divides the parabola into two mirror-image halves.\n\n"
        "[[figure:parabola|A parabola with vertex, axis of symmetry, and zeros labeled]]\n\n"
        "**Converting Standard Form to Vertex Form**\n\n"
        "Complete the square on f(x) = ax² + bx + c. Factor out a from the first two terms: a(x² + (b/a)x) + c. Add and subtract (b/2a)² inside the parentheses: a[(x + b/2a)² − (b/2a)²] + c. Simplify to get a(x + b/2a)² + (c − b²/4a). So h = −b/(2a) and k = f(h).\n\n"
        "**Finding Zeros from Factored Form**\n\n"
        "When f(x) = a(x − r)(x − s), the zeros (x-intercepts) are x = r and x = s. The **Vieta’s formulas** give a shortcut: for ax² + bx + c = 0, the **sum of the roots** equals −b/a and the **product of the roots** equals c/a. These are extremely useful on the SAT when a problem asks for the sum or product of solutions without requiring you to solve the full equation.\n\n"
        "Example: For 2x² − 10x + 8 = 0, the sum of roots = −(−10)/2 = 5 and the product of roots = 8/2 = 4. Roots are 1 and 4 (check: 1 + 4 = 5, 1 × 4 = 4).\n\n"
        "**Interpreting a, h, and k in Context**\n\n"
        "SAT word problems often present a quadratic like h(t) = −4.9(t − 3)² + 44.1, where h is height in meters and t is time in seconds. Here:\n\n"
        "- a = −4.9 tells you the object is falling (opens downward)\n"
        "- h = 3 means the maximum height occurs at t = 3 seconds\n"
        "- k = 44.1 is the maximum height (44.1 meters)\n\n"
        "Always read the context carefully to match the vertex coordinates to real-world meaning.\n\n"
        "**SAT-Style Worked Examples**\n\n"
        "Example 1: The function f(x) = −2(x − 4)² + 18 has its maximum at what point? The vertex is (4, 18) and since a = −2 < 0, this is a maximum. Maximum value is 18.\n\n"
        "Example 2: A parabola has zeros at x = −1 and x = 5. What is its axis of symmetry? The axis of symmetry is the average of the zeros: x = (−1 + 5)/2 = 2.\n\n"
        "Example 3: For f(x) = x² − 6x + 5, find the vertex and state whether it is a minimum or maximum. Convert: x² − 6x + 9 − 9 + 5 = (x − 3)² − 4. Vertex is (3, −4); since a = 1 > 0, this is a minimum.\n\n"
        "**Common Traps**\n\n"
        "- Misreading vertex form: f(x) = (x − 3)² has vertex at x = +3, not x = −3.\n"
        "- Confusing the axis of symmetry formula: it is x = −b/(2a), not x = b/(2a).\n"
        "- Assuming the largest y-value in a table is always the vertex — only true if the table hits the exact vertex.\n\n"
        "**SAT Tip:** When an SAT problem gives a quadratic in vertex form and asks for the maximum or minimum value, the answer is simply k. You do not need to graph or plug in values. This saves 30–60 seconds per question."
    ),
    (
        3,
        "**Polynomial Operations**\n\n"
        "A **polynomial** is an expression consisting of variables raised to non-negative integer powers, combined with coefficients. The **degree** of a polynomial is the highest power of the variable. The **leading coefficient** is the coefficient of the highest-degree term, and the **constant term** is the term with no variable. Polynomial operations are a foundational skill for the Advanced Math section of the SAT.\n\n"
        "[[figure:polynomial_degree|A polynomial with degree, leading coefficient, and constant labeled]]\n\n"
        "**Adding and Subtracting Polynomials**\n\n"
        "To add or subtract polynomials, **combine like terms** — terms that have the same variable raised to the same power. Align terms by degree to avoid errors. When subtracting, distribute the negative sign to every term in the second polynomial before combining.\n\n"
        "Example: (3x³ + 2x² − x + 5) − (x³ − 4x² + 3x − 2) = (3 − 1)x³ + (2 + 4)x² + (−1 − 3)x + (5 + 2) = 2x³ + 6x² − 4x + 7.\n\n"
        "**Multiplying Polynomials**\n\n"
        "For two **binomials**, use **FOIL** (First, Outer, Inner, Last): (a + b)(c + d) = ac + ad + bc + bd. For larger polynomials, use the **distributive property** — multiply every term in the first polynomial by every term in the second, then combine like terms.\n\n"
        "Example: (x + 3)(x² − 2x + 1). Distribute: x(x² − 2x + 1) + 3(x² − 2x + 1) = x³ − 2x² + x + 3x² − 6x + 3 = x³ + x² − 5x + 3.\n\n"
        "**Polynomial Long Division**\n\n"
        "Polynomial **long division** works exactly like numerical long division. To divide f(x) by d(x): (1) Divide the leading term of f(x) by the leading term of d(x) to get the first term of the quotient. (2) Multiply d(x) by that term and subtract. (3) Bring down the next term. (4) Repeat until the remainder has a lower degree than d(x).\n\n"
        "Example: Divide x³ − 2x² + x − 3 by (x − 1). The quotient is x² − x + 0 with remainder −3, so (x³ − 2x² + x − 3) / (x − 1) = x² − x − 3/(x − 1).\n\n"
        "**Remainder Theorem and Factor Theorem**\n\n"
        "The **Remainder Theorem** states: when a polynomial f(x) is divided by (x − a), the remainder equals f(a). This means you can find the remainder without performing long division — just evaluate the polynomial at x = a.\n\n"
        "The **Factor Theorem** is a direct consequence: (x − a) is a factor of f(x) **if and only if** f(a) = 0. This gives you a fast way to check whether a given binomial is a factor.\n\n"
        "**SAT-Style Worked Examples**\n\n"
        "Example 1: What is the remainder when f(x) = x³ − 3x² + 2x + 5 is divided by (x − 2)? By the Remainder Theorem, f(2) = 8 − 12 + 4 + 5 = 5. The remainder is 5.\n\n"
        "Example 2: Is (x + 1) a factor of g(x) = x³ − x² − x + 1? Evaluate g(−1): −1 − 1 + 1 + 1 = 0. Since g(−1) = 0, yes, (x + 1) is a factor.\n\n"
        "Example 3: Multiply (2x − 3)(3x² + x − 4). Distribute: 6x³ + 2x² − 8x − 9x² − 3x + 12 = 6x³ − 7x² − 11x + 12.\n\n"
        "**Common Traps**\n\n"
        "- Forgetting to distribute the negative sign when subtracting polynomials.\n"
        "- Missing middle terms when squaring binomials: (x + 3)² = x² + 6x + 9, not x² + 9.\n"
        "- Misapplying the Remainder Theorem: dividing by (x − a) requires evaluating f(a), not f(−a).\n\n"
        "**SAT Tip:** The SAT frequently tests the Remainder Theorem without telling you that’s what it’s testing. If a question asks “what is the remainder when f(x) is divided by (x − k),” simply evaluate f(k). No long division needed."
    ),
    (
        4,
        "**Radicals and Rational Exponents**\n\n"
        "Radicals and rational (fractional) exponents are two ways of expressing the same mathematical idea. Being fluent in both notations — and knowing the rules for simplifying and solving — is essential for SAT Advanced Math.\n\n"
        "**Radical Rules**\n\n"
        "The key rules for working with square roots and higher-order radicals are:\n\n"
        "- √(ab) = √a · √b (product rule for radicals)\n"
        "- √(a/b) = √a / √b (quotient rule for radicals)\n"
        "- You **cannot** simplify √(a + b) into √a + √b — this is one of the most common algebra errors on the SAT\n"
        "- To simplify a radical, factor out perfect squares: √72 = √(36 × 2) = 6√2\n\n"
        "**Rational Exponents**\n\n"
        "A **rational exponent** has the form m/n. The connection to radicals is: x^(m/n) = n-th root of (x^m) = (n-th root of x)^m. In particular, x^(1/n) is the n-th root of x, and x^(1/2) = √x.\n\n"
        "Example: 8^(2/3) = (cube root of 8)² = 2² = 4. Alternatively, 8^(2/3) = cube root of (8²) = cube root of 64 = 4.\n\n"
        "**Exponent Rules**\n\n"
        "All the standard exponent rules apply to rational exponents:\n\n"
        "- **Product rule**: x^a · x^b = x^(a+b)\n"
        "- **Quotient rule**: x^a / x^b = x^(a−b)\n"
        "- **Power rule**: (x^a)^b = x^(ab)\n"
        "- **Negative exponent**: x^(−a) = 1/x^a\n"
        "- **Zero exponent**: x^0 = 1 for any x ≠ 0\n\n"
        "**Solving Radical Equations**\n\n"
        "To solve a radical equation: (1) Isolate the radical on one side. (2) Raise both sides to the power that eliminates the radical (e.g., square both sides to remove a square root). (3) Solve the resulting equation. (4) **Check every solution** in the original equation, because squaring can introduce **extraneous solutions** — values that satisfy the squared equation but not the original.\n\n"
        "Example: Solve √(2x + 3) = x − 1. Square both sides: 2x + 3 = (x − 1)² = x² − 2x + 1. Rearrange: x² − 4x − 2 = 0. Solutions: x = (4 ± √24)/2 = 2 ± √6. Check both values in the original equation; reject any that make the right side negative (since the radical is non-negative).\n\n"
        "**SAT-Style Worked Examples**\n\n"
        "Example 1: Simplify (x^(3/4) · x^(1/4))^2. Apply product rule inside: x^(3/4 + 1/4) = x^1 = x. Then apply power rule: (x)^2 = x².\n\n"
        "Example 2: Solve √(x + 5) = 3. Square both sides: x + 5 = 9, so x = 4. Check: √9 = 3. Valid solution.\n\n"
        "Example 3: Solve √(3x − 2) = x − 2. Square both sides: 3x − 2 = x² − 4x + 4. Rearrange: x² − 7x + 6 = 0. Factor: (x − 1)(x − 6) = 0. Check x = 1: √1 = 1 but 1 − 2 = −1. Extraneous — reject. Check x = 6: √16 = 4 and 6 − 2 = 4. Valid.\n\n"
        "**Common Traps**\n\n"
        "- Adding radicals as if they were regular numbers: √4 + √9 ≠ √13.\n"
        "- Forgetting to check for extraneous solutions after squaring.\n"
        "- Misreading x^(2/3) as x^2 / 3 instead of (cube root of x)².\n\n"
        "**SAT Tip:** When you see a rational exponent on the SAT, immediately rewrite it as a radical (or vice versa) — whichever form makes the arithmetic clearer. The test often presents one form when the other is much easier to evaluate."
    ),
    (
        5,
        "**Rational Expressions and Equations**\n\n"
        "A **rational expression** is a fraction where the numerator and/or denominator is a polynomial. Rational expressions appear in about 2–3 questions per SAT Math section, and they almost always involve simplifying, combining, or solving. The key difference from regular fractions: you must always track the **domain** — values of the variable that make any denominator equal to zero are excluded.\n\n"
        "**Simplifying Rational Expressions**\n\n"
        "To simplify a rational expression: (1) Factor the numerator completely. (2) Factor the denominator completely. (3) Cancel any factors that appear in both. State the domain restrictions (the values excluded) before canceling.\n\n"
        "Example: Simplify (x² − 9) / (x² − x − 6). Factor numerator: (x + 3)(x − 3). Factor denominator: (x − 3)(x + 2). Cancel (x − 3): result is (x + 3)/(x + 2), with x ≠ 3 and x ≠ −2.\n\n"
        "**Multiplying and Dividing Rational Expressions**\n\n"
        "To **multiply**: factor all numerators and denominators, cancel common factors across any numerator-denominator pair, then multiply what remains. To **divide**: multiply the first expression by the **reciprocal** of the second, then proceed as with multiplication.\n\n"
        "Example: [(x + 2)/(x − 1)] ÷ [(x² − 4)/(x² + x − 2)]. Flip the second fraction and multiply: [(x + 2)/(x − 1)] × [(x² + x − 2)/(x² − 4)]. Factor: (x + 2)(x + 2)(x − 1) / [(x − 1)(x + 2)(x − 2)]. Cancel: (x + 2)/(x − 2).\n\n"
        "**Adding and Subtracting Rational Expressions**\n\n"
        "Adding or subtracting rational expressions requires a **least common denominator (LCD)**. (1) Factor each denominator. (2) Identify the LCD (the product of all distinct factors at their highest powers). (3) Rewrite each fraction over the LCD. (4) Combine the numerators. (5) Simplify if possible.\n\n"
        "Example: 3/(x + 1) + 2/(x − 1). LCD = (x + 1)(x − 1). Rewrite: [3(x − 1) + 2(x + 1)] / [(x + 1)(x − 1)] = (3x − 3 + 2x + 2) / (x² − 1) = (5x − 1) / (x² − 1).\n\n"
        "**Solving Rational Equations**\n\n"
        "To solve a rational equation: (1) Find the LCD of all fractions. (2) Multiply every term on both sides by the LCD to clear the fractions. (3) Solve the resulting polynomial equation. (4) **Check** every solution: if any solution makes a denominator in the original equation equal to zero, it is an **extraneous solution** and must be rejected.\n\n"
        "Example: Solve 1/(x − 2) + 1/(x + 2) = 4/(x² − 4). Note x² − 4 = (x − 2)(x + 2). LCD = (x − 2)(x + 2). Multiply through: (x + 2) + (x − 2) = 4. So 2x = 4, x = 2. Check: x = 2 makes (x − 2) = 0. Extraneous — no solution.\n\n"
        "**SAT-Style Worked Examples**\n\n"
        "Example 1: Simplify (2x² + 6x) / (x² + 5x + 6). Factor: 2x(x + 3) / [(x + 2)(x + 3)]. Cancel (x + 3): 2x/(x + 2), x ≠ −3, x ≠ −2.\n\n"
        "Example 2: Solve 2/x + 3/(x + 1) = 5/(x(x + 1)). Multiply by x(x + 1): 2(x + 1) + 3x = 5. So 5x + 2 = 5, x = 3/5. Check: neither denominator is zero at x = 3/5. Valid.\n\n"
        "Example 3: Which value of x is NOT in the domain of (x + 4)/((x − 3)(x + 7))? The excluded values are x = 3 and x = −7.\n\n"
        "**Common Traps**\n\n"
        "- Canceling terms instead of factors: (x² + 4)/(x + 4) cannot be simplified by canceling the 4.\n"
        "- Forgetting to check for extraneous solutions after multiplying through by the LCD.\n"
        "- Missing domain restrictions, which the SAT may test directly.\n\n"
        "**SAT Tip:** On the SAT, if a rational equation has only one solution and it turns out to be extraneous, the correct answer is “no solution.” Always verify before bubbling in your answer."
    ),
    (
        6,
        "**Exponential Functions**\n\n"
        "Exponential functions model situations where a quantity grows or decays by a **constant factor** over equal time intervals — compound interest, population growth, radioactive decay, and more. Recognizing and working with exponential functions is a high-priority skill for SAT Advanced Math.\n\n"
        "**Standard Form**\n\n"
        "An exponential function has the form f(x) = ab^x, where:\n\n"
        "- **a** is the **initial value** (the output when x = 0, since b^0 = 1)\n"
        "- **b** is the **base** (the growth or decay factor per unit increase in x)\n\n"
        "When b > 1, the function models **exponential growth** (the quantity increases). When 0 < b < 1, it models **exponential decay** (the quantity decreases).\n\n"
        "**Percent Growth and Decay**\n\n"
        "In real-world SAT problems, the base b is often expressed in terms of a percentage rate r:\n\n"
        "- **Growth**: b = 1 + r, where r is the growth rate as a decimal. Example: 5% annual growth → b = 1.05.\n"
        "- **Decay**: b = 1 − r, where r is the decay rate as a decimal. Example: 8% annual decay → b = 0.92.\n\n"
        "So the full model becomes f(t) = a(1 + r)^t for growth and f(t) = a(1 − r)^t for decay, where t is time.\n\n"
        "**Exponential vs. Linear Growth**\n\n"
        "A **linear function** increases by a **constant amount** each period (constant additive change). An **exponential function** increases by a **constant factor** each period (constant multiplicative change). On the SAT, you may be asked to identify which model fits a data table. Look at the differences vs. ratios between consecutive values: constant differences → linear; constant ratios → exponential.\n\n"
        "**Doubling Time and Half-Life**\n\n"
        "The **doubling time** is the time it takes an exponentially growing quantity to double. The **half-life** is the time it takes an exponentially decaying quantity to reduce to half its value. If a quantity has half-life h, the model is f(t) = a × (1/2)^(t/h). If it has doubling time d, the model is f(t) = a × 2^(t/d).\n\n"
        "Example: A radioactive substance has a half-life of 10 years. If you start with 200 grams, how much remains after 30 years? f(30) = 200 × (1/2)^(30/10) = 200 × (1/2)^3 = 200 × 1/8 = 25 grams.\n\n"
        "**SAT-Style Worked Examples**\n\n"
        "Example 1 (Population): A city’s population was 50,000 in 2010 and grows by 3% per year. What is the population model? P(t) = 50000(1.03)^t, where t is years after 2010. In 2025, t = 15: P(15) = 50000(1.03)^15 ≈ 50000 × 1.558 ≈ 77,900.\n\n"
        "Example 2 (Compound Interest): $1,000 is invested at 6% annual interest compounded annually. What is the value after 4 years? A = 1000(1.06)^4 ≈ 1000 × 1.2625 ≈ $1,262.50.\n\n"
        "Example 3 (Identifying Growth Type): A table shows values (0, 3), (1, 6), (2, 12), (3, 24). Is this linear or exponential? Ratios: 6/3 = 2, 12/6 = 2, 24/12 = 2. Constant ratio → exponential with a = 3 and b = 2.\n\n"
        "**Common Traps**\n\n"
        "- Confusing a percentage rate r with the base b: a 20% growth rate means b = 1.20, not b = 0.20.\n"
        "- Applying exponential decay incorrectly: 10% decay per year means 90% remains, so b = 0.90, not 0.10.\n"
        "- Confusing linear and exponential models when looking at a table — always check ratios, not differences.\n\n"
        "**SAT Tip:** When a real-world SAT problem says something “increases/decreases by x% each year,” that is the signal for an exponential model. When it says “increases/decreases by x units each year,” that is linear. This single distinction will save you from many answer-choice traps."
    ),
    (
        7,
        "**Function Notation and Transformations**\n\n"
        "Function notation and transformations are tested throughout the SAT Math section, often in combination with other Advanced Math topics. Mastering these concepts lets you interpret graphs, predict how equations change under transformations, and navigate composition problems efficiently.\n\n"
        "**Function Notation**\n\n"
        "The notation **f(x)** is read “f of x” and represents the output of function f when the input is x. Two common SAT tasks:\n\n"
        "- **Evaluating f(a)**: substitute x = a into the function’s rule and simplify. Example: if f(x) = 3x² − 2, then f(4) = 3(16) − 2 = 46.\n"
        "- **Solving f(x) = a**: find the x-value(s) that produce the output a. Example: if f(x) = 3x² − 2 = 46, then 3x² = 48, x² = 16, x = ±4.\n\n"
        "The **domain** is the set of allowable inputs (x-values); the **range** is the set of possible outputs (y-values). Common domain restrictions: division by zero, square roots of negatives.\n\n"
        "**Graph Transformations**\n\n"
        "Given a base function f(x), the following transformations produce predictable shifts and reflections:\n\n"
        "- f(x) + k → shifts the graph **up** by k units\n"
        "- f(x) − k → shifts the graph **down** by k units\n"
        "- f(x + h) → shifts the graph **left** by h units (counter-intuitive: adding inside shifts left)\n"
        "- f(x − h) → shifts the graph **right** by h units\n"
        "- −f(x) → **reflects** the graph over the x-axis\n"
        "- af(x) with a > 1 → **vertical stretch** by factor a; 0 < a < 1 → **vertical compression**\n\n"
        "A key SAT insight: horizontal shifts inside the parentheses move in the **opposite** direction of the sign. f(x + 3) shifts left 3, not right 3.\n\n"
        "**Composition of Functions**\n\n"
        "The **composition** (f ∘ g)(x) = f(g(x)) means: first apply g, then apply f to the result. Always evaluate the **inner function first**. The order matters: f(g(x)) is generally not the same as g(f(x)).\n\n"
        "Example: If f(x) = 2x + 1 and g(x) = x², then f(g(3)) = f(9) = 2(9) + 1 = 19. But g(f(3)) = g(7) = 49.\n\n"
        "**Even and Odd Functions**\n\n"
        "A function is **even** if f(−x) = f(x) for all x in its domain. Its graph is symmetric about the **y-axis**. Examples: f(x) = x², f(x) = |x|.\n\n"
        "A function is **odd** if f(−x) = −f(x) for all x. Its graph has **origin symmetry** (rotating 180° about the origin produces the same graph). Examples: f(x) = x³, f(x) = x.\n\n"
        "To classify, substitute −x for x and simplify. If the result equals the original expression, the function is even. If it equals the negation, the function is odd. If neither, it is neither even nor odd.\n\n"
        "**SAT-Style Worked Examples**\n\n"
        "Example 1 (Composition): Given f(x) = x² − 1 and g(x) = √(x + 5), find f(g(4)). g(4) = √9 = 3. f(3) = 9 − 1 = 8.\n\n"
        "Example 2 (Transformation): The graph of y = f(x) passes through (2, 5). What point is on the graph of y = f(x − 3) + 4? The transformation shifts right 3 and up 4: the corresponding point is (2 + 3, 5 + 4) = (5, 9).\n\n"
        "Example 3 (Even/Odd): Determine whether h(x) = x⁴ − 2x² + 1 is even, odd, or neither. h(−x) = (−x)⁴ − 2(−x)² + 1 = x⁴ − 2x² + 1 = h(x). Since h(−x) = h(x), the function is **even**.\n\n"
        "**Common Traps**\n\n"
        "- Applying horizontal shifts in the wrong direction: f(x + 2) shifts **left**, not right.\n"
        "- Reversing the order of composition: (f ∘ g)(x) applies g first, then f.\n"
        "- Confusing reflection over the x-axis (−f(x)) with reflection over the y-axis (f(−x)).\n\n"
        "**SAT Tip:** For transformation problems, track a single key point (like the vertex or a zero) through the transformation rule rather than trying to redraw the entire graph. One point is enough to identify a shift or reflection and eliminate three wrong answer choices."
    ),
]


class Command(BaseCommand):
    help = "Enrich lesson content for SAT Math: Advanced Math"

    def handle(self, *args, **options):
        for order, content in LESSONS:
            rows = Lesson.objects.filter(
                course__slug="sat-math-advanced-math", order=order
            ).update(content=content)
            self.stdout.write(f"  Lesson {order}: {rows} row(s) updated")
        self.stdout.write(
            self.style.SUCCESS("Done enriching SAT Math: Advanced Math lessons.")
        )
