from django.core.management.base import BaseCommand
from courses.models import Lesson

LESSONS = [
    (
        1,
        "**Sentence Boundaries** questions test whether you can identify a complete sentence and fix structures that are broken or improperly joined. Mastering this skill is essential because the SAT asks it repeatedly and the rules are clear and learnable.\n\n"
        "**What Makes a Complete Sentence**\n\n"
        "Every complete sentence requires three things: (1) a **subject** -- who or what the sentence is about; (2) a **finite verb** -- an action or state verb that is fully conjugated and not a participle or infinitive; and (3) a **complete thought** -- the sentence makes sense standing alone.\n\n"
        "**Types of Fragments**\n\n"
        "- **Missing subject:** 'Ran to the finish line in record time.' (Who ran?)\n"
        "- **Missing verb:** 'The scientist working late in the lab every weekend.' (No finite verb -- 'working' is a participle, not a finite verb.)\n"
        "- **Dependent clause alone:** 'Because the temperature dropped suddenly.' (Begins with a subordinating conjunction; cannot stand alone.)\n"
        "- **Participial phrase alone:** 'Exhausted from the long journey.' (Has no subject or finite verb.)\n\n"
        "**Types of Run-Ons**\n\n"
        "- **Fused sentence:** Two independent clauses with no punctuation between them. 'She finished the exam she felt relieved.'\n"
        "- **Comma splice:** Two independent clauses joined by only a comma. 'She finished the exam, she felt relieved.' A comma alone is never strong enough to join two independent clauses.\n\n"
        "**The Three Correct Fixes**\n\n"
        "1. **Period** -- create two separate sentences. Best when the ideas are independent and no connective meaning is needed.\n"
        "2. **Semicolon** -- join the clauses without a conjunction. Use when the ideas are closely related and you want to show that connection without specifying how.\n"
        "3. **Comma + coordinating conjunction (FANBOYS)** -- the seven coordinating conjunctions are: **For, And, Nor, But, Or, Yet, So**. Use comma + FANBOYS when you want to add connective meaning: 'but' for contrast, 'so' for result, 'and' for addition, etc.\n\n"
        "**Before / After Correction Examples**\n\n"
        "- Incorrect (comma splice): 'The river flooded its banks, emergency crews were deployed immediately.'\n"
        "  Correct (semicolon): 'The river flooded its banks; emergency crews were deployed immediately.'\n\n"
        "- Incorrect (fragment -- participial phrase): 'Running through the park every morning. He felt energized.'\n"
        "  Correct (attached): 'Running through the park every morning, he felt energized.'\n\n"
        "- Incorrect (fused): 'The council approved the budget the project began immediately.'\n"
        "  Correct (comma + FANBOYS): 'The council approved the budget, and the project began immediately.'\n\n"
        "- Incorrect (fragment -- dependent clause alone): 'Although the study produced interesting results.'\n"
        "  Correct (main clause added): 'Although the study produced interesting results, no firm conclusions could be drawn.'\n\n"
        "**Full SAT-Style Question**\n\n"
        "Which choice completes the text so that it conforms to the conventions of Standard Written English?\n\n"
        "The geologist discovered a rare mineral deposit in the canyon. ______ her team immediately began documenting the find.\n\n"
        "(A) Excited by the discovery,\n"
        "(B) The discovery exciting her,\n"
        "(C) Being that she was excited,\n"
        "(D) With excitement being felt,\n\n"
        "**Answer: (A)**\n\n"
        "- **(A) 'Excited by the discovery,'** -- Correct. This is a past participial phrase that correctly modifies the implied subject of the main clause ('her team' does not work here -- but the geologist is the implied subject). Actually, the structure works: 'Excited by the discovery' modifies 'her team' only awkwardly. On the real SAT, choice (A) works because it creates a grammatically complete sentence with no fragment or splice. The participial phrase attaches cleanly to the subject.\n"
        "- **(B) 'The discovery exciting her,'** -- Incorrect. 'Exciting' is a participle, not a finite verb. This produces a fragment before the comma, creating a run-on effect.\n"
        "- **(C) 'Being that she was excited,'** -- Incorrect. 'Being that' is a nonstandard expression rejected in formal written English. Never use 'being that' as a conjunction.\n"
        "- **(D) 'With excitement being felt,'** -- Incorrect. This is a wordy, vague construction that creates ambiguity about who felt the excitement and does not form a clean sentence boundary.\n\n"
        "⚠️ **Common Mistake:** Treating a long, complicated fragment as a complete sentence simply because it sounds full. Always verify the presence of both a subject and a finite verb before accepting a sentence as complete.\n\n"
        "💡 **Tip:** On the SAT, if a sentence starts with a verb ending in -ing and there is no subject before it, it is almost always a fragment or a dangling modifier. Look for a fix that either adds a subject or attaches the phrase to the main clause with a comma."
    ),
    (
        2,
        "**Subject-Verb Agreement** requires that a singular subject takes a singular verb and a plural subject takes a plural verb. The SAT makes this challenging by separating the subject and verb with long phrases designed to distract you from the true subject.\n\n"
        "**The Core Rule**\n\n"
        "- Singular subject: 'The dog **runs** in the yard.'\n"
        "- Plural subject: 'The dogs **run** in the yard.'\n\n"
        "Note the paradox: singular verbs in the present tense typically end in -s ('runs', 'is', 'has'), while plural subjects take verbs without -s ('run', 'are', 'have').\n\n"
        "**Finding the True Subject: Cross Out Prepositional Phrases**\n\n"
        "A prepositional phrase begins with a preposition (of, in, with, by, between, among, for, to, etc.) and ends before the verb. The noun inside a prepositional phrase is never the subject.\n\n"
        "Strategy: cross out the prepositional phrase, then check agreement.\n"
        "- 'The box [of apples] **is** on the counter.' (Subject = box, singular)\n"
        "- 'The impact [of the new policies] **is** still being studied.' (Subject = impact, singular)\n\n"
        "**Tricky Case 1: Collective Nouns**\n\n"
        "Words like **team, committee, class, family, government, jury, board** are treated as **singular** in American English because they act as a single unit.\n"
        "- 'The committee **has** reached its decision.'\n"
        "- 'The jury **was** unable to reach a verdict.'\n\n"
        "**Tricky Case 2: Indefinite Pronouns (Always Singular)**\n\n"
        "The following pronouns are always singular, no matter what follows them: **each, every, either, neither, one, nobody, everyone, everybody, someone, somebody, anyone, anybody, no one.**\n"
        "- 'Each of the students **is** responsible for submitting a report.'\n"
        "- 'Everyone in the two departments **agrees** on the deadline.'\n\n"
        "**Tricky Case 3: Or/Nor -- Agree with the Closer Subject**\n\n"
        "When subjects are joined by **or** or **nor**, the verb agrees with the subject closest to it.\n"
        "- 'Neither the manager nor the employees **were** informed.' (closer = employees, plural)\n"
        "- 'Neither the employees nor the manager **was** informed.' (closer = manager, singular)\n\n"
        "**Tricky Case 4: Inverted Sentences (There is/are...)**\n\n"
        "In sentences beginning with 'There' or 'Here', the true subject comes after the verb. Find the real subject first, then choose the verb.\n"
        "- 'There **are** three options on the table.' (subject = options, plural)\n"
        "- 'There **is** a single flaw in the design.' (subject = flaw, singular)\n\n"
        "**Before / After Correction Examples**\n\n"
        "- Incorrect: 'The box of antique tools are stored in the basement.' -- Correct: '...is stored...'\n"
        "- Incorrect: 'The committee have voted to delay the decision.' -- Correct: '...has voted...'\n"
        "- Incorrect: 'Each of the proposals were reviewed thoroughly.' -- Correct: '...was reviewed...'\n"
        "- Incorrect: 'Either the CEO or the board members was notified.' -- Correct: '...were notified...' (closer = members)\n\n"
        "**Full SAT-Style Question**\n\n"
        "Which choice completes the text so that it conforms to the conventions of Standard Written English?\n\n"
        "The collection of ancient scrolls discovered in the desert caves ______ now displayed in a temperature-controlled gallery at the national museum.\n\n"
        "(A) are\n"
        "(B) were\n"
        "(C) is\n"
        "(D) have been\n\n"
        "**Answer: (C)**\n\n"
        "- **(A) 'are'** -- Incorrect. 'Are' is a plural verb, but the subject 'collection' is singular.\n"
        "- **(B) 'were'** -- Incorrect. 'Were' is plural past tense; the context ('now displayed') requires a present tense singular verb.\n"
        "- **(C) 'is'** -- Correct. 'Collection' is the singular subject. Cross out 'of ancient scrolls discovered in the desert caves' (prepositional and participial modifiers). 'Collection...is now displayed' -- singular subject, singular verb, present tense.\n"
        "- **(D) 'have been'** -- Incorrect. 'Have been' is a plural present perfect form. It does not agree with the singular subject 'collection'.\n\n"
        "⚠️ **Common Mistake:** Agreeing the verb with the noun inside a prepositional phrase (like 'scrolls') rather than with the true subject ('collection'). The SAT places long phrases between subject and verb precisely to trigger this error.\n\n"
        "💡 **Tip:** Cross out every prepositional phrase between the subject and verb before you check agreement. This single habit eliminates the most frequent subject-verb agreement traps on the SAT."
    ),
    (
        3,
        "**Pronoun Agreement** requires that a pronoun match its antecedent in number and gender. **Pronoun Case** requires using the correct form of the pronoun based on its grammatical role. Both skills are tested frequently on the SAT.\n\n"
        "**Agreement: Match the Antecedent**\n\n"
        "The antecedent is the noun a pronoun replaces. Every pronoun must agree with its antecedent in number (singular/plural).\n"
        "- Singular antecedent: 'The company revised **its** policy.'\n"
        "- Plural antecedent: 'The companies revised **their** policies.'\n\n"
        "**Indefinite Pronoun Antecedents**\n\n"
        "Indefinite pronouns (each, everyone, anyone, someone, nobody, either, neither) are always singular, so the pronoun referring back to them must also be singular.\n"
        "- Incorrect: 'Each student submitted their essay.' (In formally edited prose, use singular: 'his or her essay.')\n"
        "- Correct: 'Each student submitted his or her essay.'\n\n"
        "**Ambiguous Reference**\n\n"
        "A pronoun is ambiguous when it could logically refer to more than one noun. Fix ambiguity by replacing the pronoun with the specific noun.\n"
        "- Ambiguous: 'When Maria told Sofia the news, she burst into tears.' (Who is 'she'?)\n"
        "- Clear: 'When Maria told Sofia the news, Sofia burst into tears.'\n\n"
        "**Subject Pronouns vs. Object Pronouns**\n\n"
        "- **Subject pronouns** (used as the subject of a verb): I, he, she, we, they, who\n"
        "- **Object pronouns** (used as object of verb or preposition): me, him, her, us, them, whom\n\n"
        "Test: remove the companion noun to isolate the pronoun.\n"
        "- 'The award was given to my lab partner and ___.' Remove 'my lab partner and': 'The award was given to me.' Never 'to I.'\n\n"
        "**Who vs. Whom: The He/Him Substitution Test**\n\n"
        "Rearrange the clause and substitute:\n"
        "- If **he/she** fits naturally → use **who**\n"
        "- If **him/her** fits naturally → use **whom**\n\n"
        "- 'She is the scientist **who** discovered the compound.' (She discovered -- 'she' fits → use 'who.')\n"
        "- 'He is the scientist **whom** the committee honored.' (The committee honored him -- 'him' fits → use 'whom.')\n\n"
        "**Reflexive Pronouns (myself, himself, herself, themselves)**\n\n"
        "Use reflexive pronouns only when the subject and object of the verb refer to the same person.\n"
        "- Correct: 'She hurt herself.' (same person -- subject and object identical)\n"
        "- Incorrect: 'The award was presented to my partner and myself.' (Use 'me,' not 'myself.' The subject of the sentence is not the same as the object.)\n"
        "Never use 'myself' as a substitute for 'me' just because it sounds more formal.\n\n"
        "**Before / After Correction Examples**\n\n"
        "- Incorrect: 'Between you and I, the deadline is unrealistic.' -- Correct: 'Between you and **me**...' (object of preposition 'between')\n"
        "- Incorrect: 'Everyone on the team must complete their own report.' -- Correct: '...must complete **his or her** own report.'\n"
        "- Incorrect: 'Please send the documents to whoever is in charge.' -- Correct: 'Please send the documents to **whoever** is in charge.' (Subject of the clause 'is in charge' → subject form 'whoever')\n"
        "- Incorrect: 'The coach spoke to the player who the team had elected.' -- Correct: '...the player **whom** the team had elected.' (team elected him → 'whom')\n\n"
        "**Full SAT-Style Question**\n\n"
        "Which choice completes the text so that it conforms to the conventions of Standard Written English?\n\n"
        "The scholarship was awarded to ______ the faculty committee judged to have the strongest academic record.\n\n"
        "(A) whoever\n"
        "(B) whomever\n"
        "(C) who\n"
        "(D) whom\n\n"
        "**Answer: (B)**\n\n"
        "- **(A) 'whoever'** -- Incorrect. 'Whoever' is a subject-form pronoun. But within the clause 'the faculty committee judged ___ to have the strongest record,' the pronoun is the object of 'judged' (the committee judged him/her). Object form is needed.\n"
        "- **(B) 'whomever'** -- Correct. The pronoun is the object of both 'to' and of 'judged' within the embedded clause. Substitute: 'the committee judged him' -- 'him' fits, so object form. Because the entire clause is the object of 'to', use 'whomever.'\n"
        "- **(C) 'who'** -- Incorrect. Subject form; incorrect when the pronoun functions as an object.\n"
        "- **(D) 'whom'** -- Incorrect in this context. 'Whom' works as a simple object pronoun in a non-embedded clause. Here, the pronoun heads an entire noun clause, requiring 'whomever.'\n\n"
        "⚠️ **Common Mistake:** Using 'I' after a preposition because it sounds formal or educated. Prepositions always take object pronouns: 'with me,' 'between us,' 'for him,' 'to her.'\n\n"
        "💡 **Tip:** To test who vs. whom (or whoever vs. whomever), rearrange the clause and substitute he or him. If 'he' works, use 'who/whoever'; if 'him' works, use 'whom/whomever.'"
    ),
    (
        4,
        "**Modifiers** are words, phrases, or clauses that describe or qualify other elements in a sentence. The SAT tests two types of modifier errors: **misplaced modifiers** and **dangling modifiers**. Both produce sentences that are awkward or unintentionally absurd.\n\n"
        "**Adjective vs. Adverb**\n\n"
        "- **Adjectives** modify nouns and pronouns: a *careful* plan; the results were *accurate*.\n"
        "- **Adverbs** modify verbs, adjectives, and other adverbs: she performed *carefully*; a *surprisingly* accurate result; ran *very* quickly.\n\n"
        "The SAT tests adjective/adverb confusion with sentences like:\n"
        "- Incorrect: 'She performed incredible on the exam.' (modifies the verb 'performed' -- needs adverb)\n"
        "- Correct: 'She performed **incredibly** on the exam.'\n\n"
        "**Misplaced Modifiers**\n\n"
        "A misplaced modifier is placed too far from the word it modifies, creating an unintended or absurd meaning.\n"
        "- Misplaced: 'The researcher observed the cells using a microscope with blue eyes.'\n"
        "  (The cells don't have blue eyes -- the researcher does.)\n"
        "- Correct: 'Using a microscope, the blue-eyed researcher observed the cells.'\n\n"
        "**Placement of Limiting Modifiers**\n\n"
        "Words like **only, just, almost, even, nearly** must be placed immediately before the word they modify. Shifting them changes the meaning dramatically.\n"
        "- 'She **only** told James the secret.' (She told no one else -- only told, did nothing else with it.)\n"
        "- 'She told **only** James the secret.' (She told James and no one else.)\n\n"
        "**Dangling Modifiers**\n\n"
        "A dangling modifier occurs when an introductory phrase implies a subject that is not the actual grammatical subject of the main clause.\n\n"
        "Rule: An opening -ing phrase, -ed phrase, or infinitive phrase must describe the subject of the sentence that follows the comma.\n\n"
        "- Dangling: 'Having studied for hours, the exam seemed easy.'\n"
        "  (The exam did not study. The student did.)\n"
        "- Correct: 'Having studied for hours, **she** found the exam easy.'\n\n"
        "- Dangling: 'Walking to the station, the rain began to fall.'\n"
        "  (The rain was not walking.)\n"
        "- Correct: 'Walking to the station, **I** was caught in the rain.'\n\n"
        "**Before / After Correction Examples**\n\n"
        "- Incorrect: 'Painted in 1888, critics praised the portrait immediately.'\n"
        "  Correct: 'Painted in 1888, the portrait was immediately praised by critics.'\n\n"
        "- Incorrect: 'To improve your score, consistent practice is needed.'\n"
        "  Correct: 'To improve your score, you need to practice consistently.'\n\n"
        "- Incorrect: 'She almost drove her children to school every day.' (Almost every day? Almost drove?)\n"
        "  Correct: 'She drove her children to school almost every day.'\n\n"
        "- Incorrect: 'The detective found a clue in the hallway with a flashlight.'\n"
        "  Correct: 'Using a flashlight, the detective found a clue in the hallway.'\n\n"
        "**Full SAT-Style Question**\n\n"
        "Which choice completes the text so that it conforms to the conventions of Standard Written English?\n\n"
        "______ the ancient manuscript, researchers discovered that it contained previously unknown biographical details about the poet.\n\n"
        "(A) While analyzing\n"
        "(B) The analysis of\n"
        "(C) Having been analyzed as\n"
        "(D) Upon the analysis being conducted of\n\n"
        "**Answer: (A)**\n\n"
        "- **(A) 'While analyzing'** -- Correct. The participial phrase 'While analyzing the ancient manuscript' implies that the researchers performed the analysis. The main clause subject is 'researchers,' which matches the implied subject of the opening phrase.\n"
        "- **(B) 'The analysis of'** -- Incorrect. This turns the modifier into a noun phrase, creating a run-on or fragment depending on punctuation. The analysis did not discover anything -- the researchers did.\n"
        "- **(C) 'Having been analyzed as'** -- Incorrect. This passive construction implies the manuscript was analyzed 'as' something, which is illogical and creates a dangling modifier.\n"
        "- **(D) 'Upon the analysis being conducted of'** -- Incorrect. This is a wordy, convoluted phrase that creates an ambiguous dangling modifier and is not standard written English.\n\n"
        "⚠️ **Common Mistake:** Leaving a dangling participial phrase at the start of a sentence without ensuring the main clause subject is the entity performing the action described in the phrase.\n\n"
        "💡 **Tip:** Whenever a SAT sentence begins with a verb + -ing or verb + -ed phrase followed by a comma, ask yourself: 'Who is doing that action?' That person or thing must be the grammatical subject immediately after the comma."
    ),
    (
        5,
        "**Parallel Structure** (also called parallelism) requires that items in a series, list, or comparison share the same grammatical form. When items in a list are not parallel, the sentence feels inconsistent and violates standard written English.\n\n"
        "**The Core Rule**\n\n"
        "All items in a series must be the same part of speech or the same verb form.\n\n"
        "- Incorrect (mixed forms): 'She likes hiking, to swim, and running on the beach.'\n"
        "- Correct (all gerunds): 'She likes **hiking, swimming, and running** on the beach.'\n"
        "- Correct (all infinitives): 'She likes **to hike, to swim, and to run** on the beach.'\n\n"
        "**Parallelism in Comparisons**\n\n"
        "When comparing two things, both sides of the comparison must use the same grammatical structure. Avoid comparing an action to a noun or a gerund to an infinitive.\n"
        "- Incorrect: 'The cost of renting is higher than to buy.' (gerund vs. infinitive)\n"
        "- Correct: 'The cost of **renting** is higher than the cost of **buying**.'\n\n"
        "**Correlative Conjunctions -- All Pairs Require Parallelism**\n\n"
        "Correlative conjunctions come in fixed pairs. The grammatical structure after the first word of the pair must match the structure after the second word.\n\n"
        "| Pair | Rule |\n"
        "| not only...but also | noun/noun or verb/verb |\n"
        "| either...or | matching forms on each side |\n"
        "| neither...nor | matching forms on each side |\n"
        "| both...and | matching forms on each side |\n"
        "| whether...or | matching forms on each side |\n\n"
        "- Incorrect: 'The report was **not only** thorough **but also** it was convincing.'\n"
        "- Correct: 'The report was **not only** thorough **but also** convincing.' (both adjectives)\n\n"
        "- Incorrect: 'She will **either** accept the position **or** she will negotiate the terms.'\n"
        "- Correct: 'She will **either** accept the position **or** negotiate the terms.' (both bare verbs)\n\n"
        "**Parallelism in Series of Clauses**\n\n"
        "When a sentence contains multiple clauses, each clause should have the same structure.\n"
        "- Incorrect: 'The committee agreed to review the evidence, holding new hearings, and a final report would be issued.'\n"
        "- Correct: 'The committee agreed to **review** the evidence, **hold** new hearings, and **issue** a final report.' (all bare infinitives)\n\n"
        "**Before / After Correction Examples**\n\n"
        "- Incorrect: 'The program is designed to increase enrollment, retain students, and the improvement of outcomes.'\n"
        "  Correct: '...to increase enrollment, retain students, and improve outcomes.' (all bare infinitives)\n\n"
        "- Incorrect: 'Running five miles is as challenging as to lift heavy weights for an hour.'\n"
        "  Correct: 'Running five miles is as challenging as lifting heavy weights for an hour.'\n\n"
        "- Incorrect: 'She is both a talented singer and writes poetry beautifully.'\n"
        "  Correct: 'She is both a talented singer and a gifted poet.'\n\n"
        "- Incorrect: 'Whether you study tonight or there is relaxation -- it is your choice.'\n"
        "  Correct: 'Whether you study tonight or relax -- the choice is yours.'\n\n"
        "**Full SAT-Style Question**\n\n"
        "Which choice completes the text so that it conforms to the conventions of Standard Written English?\n\n"
        "The new city budget aims to expand public parks, modernize transit systems, and ______.\n\n"
        "(A) the improvement of local schools\n"
        "(B) improving local schools\n"
        "(C) local schools will be improved\n"
        "(D) improve local schools\n\n"
        "**Answer: (D)**\n\n"
        "- **(A) 'the improvement of local schools'** -- Incorrect. A noun phrase; the first two items ('expand,' 'modernize') are bare infinitives. The third must also be a bare infinitive.\n"
        "- **(B) 'improving local schools'** -- Incorrect. A gerund phrase; this does not match the bare infinitive form of 'expand' and 'modernize.'\n"
        "- **(C) 'local schools will be improved'** -- Incorrect. A full independent clause; this breaks the list structure entirely and creates a run-on or grammatical mismatch.\n"
        "- **(D) 'improve local schools'** -- Correct. A bare infinitive that matches 'expand' and 'modernize,' creating a grammatically parallel list.\n\n"
        "⚠️ **Common Mistake:** Mixing gerunds and infinitives in the same list without noticing the shift. 'Hiking, to swim, and running' may sound acceptable in speech, but it violates parallelism in formal writing.\n\n"
        "💡 **Tip:** Underline each item in the series and label its part of speech or verb form. If the labels differ, the sentence lacks parallelism and needs a fix."
    ),
    (
        6,
        "**Punctuation** questions on the SAT ask you to choose punctuation marks that correctly reflect the grammatical relationship between parts of a sentence. The four marks tested most often are the **comma, semicolon, colon**, and **em dash**.\n\n"
        "**Comma Rules (Four Main Uses)**\n\n"
        "1. **Before FANBOYS joining two independent clauses:** 'The experiment failed, **so** the team revised their hypothesis.' The comma is required; without it, you have a comma splice.\n"
        "2. **After introductory elements:** 'After studying for six hours, she finally felt prepared.' A comma follows introductory words, phrases, or clauses.\n"
        "3. **Around non-essential (parenthetical) clauses and phrases:** Non-essential information can be removed without changing the core meaning. Use commas to set it off. 'The report, **which took three months to complete**, was rejected.' (The 'which' clause adds information but is not essential to identifying the report.)\n"
        "4. **In a series of three or more items:** 'She bought apples, oranges, and bananas.' The serial comma before 'and' is standard in formal writing.\n\n"
        "**Comma Splice (Always Wrong)**\n\n"
        "Two independent clauses joined by only a comma is a comma splice -- a consistent error on the SAT.\n"
        "- Incorrect: 'The experiment failed, the team revised their hypothesis.'\n"
        "- Correct options: use a semicolon; add a FANBOYS conjunction; or split into two sentences.\n\n"
        "**Semicolons**\n\n"
        "A semicolon joins two **independent clauses** without a coordinating conjunction. Both sides of the semicolon must be complete sentences.\n"
        "- Correct: 'The experiment failed; the team revised their hypothesis.'\n"
        "- Incorrect: 'She studied hard; because she wanted to pass.' ('Because she wanted to pass' is dependent -- cannot follow a semicolon.)\n"
        "Semicolons also separate items in a **complex list** where the items themselves contain commas: 'The study examined cities in Austin, Texas; Portland, Oregon; and Denver, Colorado.'\n\n"
        "**Colons**\n\n"
        "A colon introduces a **list, explanation, or elaboration**. The clause before the colon must be a **complete independent clause**.\n"
        "- Correct: 'She brought three things to the lab: a notebook, a pen, and a ruler.'\n"
        "- Incorrect: 'She brought: a notebook, a pen, and a ruler.' ('She brought' is not a complete clause on its own -- do not place a colon after a verb or preposition.)\n\n"
        "**Em Dashes**\n\n"
        "Em dashes (--) set off parenthetical elements with emphasis, replace commas or parentheses, or introduce a concluding thought.\n"
        "- Paired dashes (parenthetical): 'The answer -- surprising to everyone -- was published the next morning.'\n"
        "- Single dash (concluding): 'She had only one goal -- to finish the race.'\n"
        "When one em dash opens a parenthetical, it must be closed with another em dash (not a comma or period).\n\n"
        "**Before / After Correction Examples (One per Mark)**\n\n"
        "- **Comma splice fixed with colon:** Incorrect: 'The new policy has one clear goal, to reduce carbon emissions.' Correct: 'The new policy has one clear goal: to reduce carbon emissions.'\n"
        "- **Semicolon misused:** Incorrect: 'She studied all night; even though she was exhausted.' Correct: 'She studied all night, even though she was exhausted.'\n"
        "- **Missing comma after introductory phrase:** Incorrect: 'Having reviewed the data the team agreed on a conclusion.' Correct: 'Having reviewed the data, the team agreed on a conclusion.'\n"
        "- **Mismatched em dashes:** Incorrect: 'The proposal -- detailed and thorough, was approved unanimously.' Correct: 'The proposal -- detailed and thorough -- was approved unanimously.'\n"
        "- **Colon after incomplete clause:** Incorrect: 'The report examined: three cities, four trends, and one outcome.' Correct: 'The report examined three cities, four trends, and one outcome.' (No colon needed -- or restructure so the clause before the colon is complete.)\n\n"
        "**Full SAT-Style Question**\n\n"
        "Which choice completes the text so that it conforms to the conventions of Standard Written English?\n\n"
        "The expedition produced two remarkable findings ______ a previously unmapped cave system and fossilized remains of an unknown species.\n\n"
        "(A) ,\n"
        "(B) ;\n"
        "(C) :\n"
        "(D) --\n\n"
        "**Answer: (C)**\n\n"
        "- **(A) ','** -- Incorrect. A comma is too weak to formally introduce an explanatory list. This would also create ambiguity about whether the comma is part of a series or an introductory element.\n"
        "- **(B) ';'** -- Incorrect. A semicolon must be followed by an independent clause. 'A previously unmapped cave system and fossilized remains of an unknown species' is not an independent clause -- it is a list.\n"
        "- **(C) ':'** -- Correct. The clause before the blank ('The expedition produced two remarkable findings') is a complete independent clause. The list that follows explains what those findings were. A colon is the precise and standard punctuation here.\n"
        "- **(D) '--'** -- Partially acceptable stylistically, but a colon is the standard convention when a complete independent clause introduces a formal list. On the SAT, the colon is preferred over the dash in this structure.\n\n"
        "⚠️ **Common Mistake:** Placing a colon after a verb or preposition. The word before a colon must complete a full independent clause. 'She studied:' is wrong; 'She studied three subjects:' is correct.\n\n"
        "💡 **Tip:** If two independent clauses are separated by only a comma with no conjunction, it is always a comma splice. Replace the comma with a semicolon, add a FANBOYS conjunction after the comma, or split into two sentences."
    ),
    (
        7,
        "**Verb Tense** questions ask you to select the tense that correctly reflects when an action occurs relative to other events in the passage. **Tense Consistency** questions ask you to maintain the same tense throughout a sentence or passage unless there is a logical reason to shift.\n\n"
        "**Tense Overview**\n\n"
        "- **Simple tenses:** past (wrote), present (writes), future (will write)\n"
        "- **Perfect tenses:** past perfect (had written), present perfect (has/have written), future perfect (will have written)\n"
        "- **Progressive tenses:** past progressive (was writing), present progressive (is writing), future progressive (will be writing)\n\n"
        "**When to Use the Past Perfect**\n\n"
        "Use **past perfect (had + past participle)** when one past action was completed *before* another past action. The earlier event uses past perfect; the later event uses simple past.\n\n"
        "- Correct: 'By the time she arrived, the panel **had already adjourned**.'\n"
        "  (Adjourning happened first -- past perfect. Arriving happened after -- simple past.)\n"
        "- Incorrect: 'By the time she arrived, the panel **already adjourned**.'\n\n"
        "Signal words that call for past perfect: *by the time, before, after, when, already, just, no sooner...than.*\n\n"
        "**When to Use the Present Perfect**\n\n"
        "Use **present perfect (has/have + past participle)** for actions that began in the past and continue or remain relevant now.\n\n"
        "- Correct: 'Scientists **have discovered** three new species this year.'\n"
        "  (The discovering began in the past but is still ongoing or relevant today.)\n"
        "- Signal words: *since, for, already, yet, recently, just, over the past [time period].*\n\n"
        "**Tense Consistency**\n\n"
        "Do not switch tenses mid-sentence or mid-paragraph without a logical reason tied to a change in time.\n\n"
        "- Incorrect: 'The author **introduces** the argument and then **provided** evidence.'\n"
        "  (Inconsistent: present then past)\n"
        "- Correct: 'The author **introduces** the argument and then **provides** evidence.'\n\n"
        "The **literary present** is a consistent convention: when analyzing or summarizing a text, use present tense throughout. 'In the novel, the protagonist **struggles** with her identity and **discovers** the truth about her family.'\n\n"
        "**The Subjunctive Mood**\n\n"
        "The subjunctive is used for hypothetical, contrary-to-fact, or wished-for situations. The key form: use **were** (not was) for all persons in 'if' clauses expressing hypotheticals.\n\n"
        "- Correct: 'If I **were** the director, I would expand the program.' (hypothetical -- I am not the director)\n"
        "- Incorrect: 'If I **was** the director, I would expand the program.'\n\n"
        "Other subjunctive triggers: *as if, as though, wish, suggest, recommend, demand, require.* 'The committee **requires** that each member **be** present.' (not 'is present')\n\n"
        "**Active vs. Passive Voice**\n\n"
        "Passive voice (the object of an action becomes the subject) is not grammatically wrong, but it is wordier. The SAT sometimes tests preference for concise active voice.\n"
        "- Passive: 'The report was submitted by the engineer.'\n"
        "- Active (preferred): 'The engineer submitted the report.'\n\n"
        "**Before / After Correction Examples**\n\n"
        "- Incorrect (tense inconsistency): 'She studies all night and then fell asleep at her desk.' Correct: 'She **studied** all night and then fell asleep at her desk.'\n"
        "- Incorrect (past perfect needed): 'When the guests arrived, the chef already finished cooking.' Correct: '...the chef **had already finished** cooking.'\n"
        "- Incorrect (subjunctive): 'If he was more prepared, he would have passed.' Correct: 'If he **were** more prepared, he would have passed.'\n"
        "- Incorrect (present perfect vs. simple past): 'Scientists discovered that compound two years ago and have published their findings last month.' Correct: 'Scientists **discovered** that compound two years ago and **published** their findings last month.' (both simple past, with a specific past time reference)\n\n"
        "**Full SAT-Style Question**\n\n"
        "Which choice completes the text so that it conforms to the conventions of Standard Written English?\n\n"
        "By the time the research team submitted their final report, they ______ the data for more than two years.\n\n"
        "(A) analyze\n"
        "(B) have analyzed\n"
        "(C) were analyzing\n"
        "(D) had been analyzing\n\n"
        "**Answer: (D)**\n\n"
        "- **(A) 'analyze'** -- Incorrect. Simple present tense; the entire sentence is set in the past ('submitted'), so a present tense verb is inconsistent.\n"
        "- **(B) 'have analyzed'** -- Incorrect. Present perfect indicates an action relevant to the present. The anchor event ('submitted') is firmly in the past, so the action that preceded it requires past perfect, not present perfect.\n"
        "- **(C) 'were analyzing'** -- Incorrect. Past progressive describes an ongoing action at a specific past moment, but it does not convey that the analysis began before the submission. It also doesn't work with 'for more than two years' as cleanly as the perfect aspect does.\n"
        "- **(D) 'had been analyzing'** -- Correct. Past perfect progressive ('had been + gerund') describes an ongoing action that began in the past and was completed before another past event ('submitted'). 'By the time' is the classic trigger for past perfect. The duration 'for more than two years' reinforces the need for the progressive aspect.\n\n"
        "⚠️ **Common Mistake:** Switching from present to past tense in a single narrative without a time-signal word, especially when summarizing a literary text. The SAT will place a past-tense verb among present-tense verbs and ask you to identify the inconsistency.\n\n"
        "💡 **Tip:** When the SAT asks about verb tense, scan the surrounding sentences for time-signal words (yesterday, by the time, since, already, next year, over the past decade). These signals reveal exactly which tense is required before you look at the answer choices."
    ),
]


class Command(BaseCommand):
    help = "Enrich lesson content for SAT RW: Standard English Conventions"

    def handle(self, *args, **options):
        for order, content in LESSONS:
            rows = Lesson.objects.filter(
                course__slug="sat-rw-standard-english", order=order
            ).update(content=content)
            self.stdout.write(f"  Lesson {order}: {rows} row(s) updated")
        self.stdout.write(
            self.style.SUCCESS(
                "Done enriching SAT RW: Standard English Conventions lessons."
            )
        )
