"""
Enrich lesson content for 'SAT Reading & Writing: Craft & Structure'.

Each lesson receives a longer, richer content block (600-800 words) including:
  - A full 10-sentence sample passage
  - A complete worked example with all 4 choices explained
  - Strategies, a Common mistake, and a Tip

Run:
    python manage.py enrich_sat_rw_craft_structure
"""
from django.core.management.base import BaseCommand
from courses.models import Lesson


LESSONS = [
    (
        1,
        "**Words in Context (Vocabulary)**\n\n"
        "Words in Context questions are the most common Craft & Structure question type on the digital SAT. "
        "They ask you to determine the meaning of a word or phrase as it is used in a specific passage -- "
        "not the definition you would find in a dictionary, but the precise meaning the author intends in "
        "that exact context. Two words that look like synonyms (for example, 'bold' and 'reckless') carry "
        "different emotional weight and will produce different right and wrong answers depending on the "
        "passage's tone and surrounding details.\n\n"
        "**Sample passage:**\n"
        "\"The city council's decision to table the infrastructure proposal stunned local advocates. "
        "For months, engineers had flagged the aging water mains as a critical hazard, documenting "
        "dozens of small failures across the eastern district. The chair acknowledged the urgency but "
        "insisted the funding mechanism required further study. Advocates argued this approach was not "
        "caution but capitulation. The delay, they warned, would allow a manageable problem to "
        "metastasize into a citywide emergency. Opposition council members, however, characterized "
        "the pause as responsible governance. They noted that three similar proposals in neighboring "
        "municipalities had ballooned in cost after premature approval. The chair ultimately scheduled "
        "a follow-up vote for the next fiscal quarter, a timeline critics called dangerously "
        "leisurely. Several engineers submitted formal dissents, citing professional obligations "
        "to protect public safety above political timelines.\"\n\n"
        "**Connotation vs. Denotation**\n"
        "Every word carries two layers of meaning. Its **denotation** is the literal, dictionary "
        "definition. Its **connotation** is the emotional register -- the feeling or attitude the "
        "word evokes. The SAT probes connotation, not just denotation. 'Inquisitive' and 'nosy' "
        "both mean curious, but only 'inquisitive' fits a sentence praising a scientist. 'Persistent' "
        "and 'stubborn' both mean continuing despite obstacles, but one carries admiration and the "
        "other carries frustration.\n\n"
        "**Tone words to know:**\n"
        "- Positive connotation: innovative, resilient, visionary, meticulous, tenacious\n"
        "- Negative connotation: reckless, obstinate, superficial, sycophantic, inflammatory\n"
        "- Neutral / technical: proposed, indicated, documented, cited, characterized\n\n"
        "**Three-step strategy:**\n"
        "Step 1 -- Remove the word from the sentence and read what remains. Ask: what meaning must "
        "fill this gap for the sentence to make sense?\n"
        "Step 2 -- Predict your own replacement word based solely on the context of the passage. "
        "Write it down before looking at the choices.\n"
        "Step 3 -- Match your prediction to the answer choice that is closest in both meaning and "
        "connotation. Plug that choice back into the sentence and confirm it sounds precise.\n\n"
        "**Worked example:**\n"
        "Q: As used in the passage, 'metastasize' most nearly means --\n\n"
        "(A) disappear gradually over time\n"
        "The passage says the delay would allow a 'manageable problem' to reach a worse state. "
        "'Disappear' is the opposite of what the context requires. Eliminate.\n\n"
        "(B) spread and grow more severe\n"
        "This fits precisely. The advocates are warning that a contained problem will expand and "
        "worsen if left unaddressed. The medical connotation of 'metastasize' (cancer spreading) "
        "adds urgency that matches the passage's alarmed tone. This is the correct answer.\n\n"
        "(C) become a subject of public debate\n"
        "The passage is about physical infrastructure failure, not about whether the problem will "
        "attract attention. 'Debate' is not what the engineers are warning against. Eliminate.\n\n"
        "(D) require additional engineering study\n"
        "This describes what the chair wants to do, not what the advocates fear will happen. It "
        "confuses one character's action with the prediction the word 'metastasize' expresses. Eliminate.\n\n"
        "**Why the dictionary-definition trap fails:**\n"
        "Many students know 'metastasize' primarily from cancer biology. On the SAT, the word is "
        "being used metaphorically to mean 'spread and worsen.' The passage context -- not your "
        "prior knowledge -- determines the correct meaning. Always trust the passage.\n\n"
        "**Additional strategy -- transition words as context clues:**\n"
        "Words like 'however,' 'yet,' and 'despite' signal contrast: the second idea opposes the "
        "first. Words like 'therefore,' 'thus,' and 'consequently' signal agreement or cause. "
        "Identifying these signals before you choose a replacement word makes your prediction "
        "more accurate.\n\n"
        "⚠️ Common mistake: choosing the most familiar or common meaning of the target word "
        "rather than the meaning the passage context requires. The SAT deliberately includes the "
        "everyday meaning as a wrong answer to catch readers who skip the context-checking step.\n\n"
        "💡 Tip: Cover the answer choices with your hand, read the sentence and one sentence on "
        "either side, and say your replacement word out loud before uncovering the options. "
        "Students who predict first are far less likely to be seduced by attractive wrong answers."
    ),
    (
        2,
        "**Text Structure and Organization**\n\n"
        "Text Structure and Organization questions ask you to identify how a passage is arranged "
        "and why the author chose that arrangement. Every paragraph serves a function: it might "
        "introduce a problem, present evidence, offer a counterargument, or propose a solution. "
        "Recognizing the structure before you read the questions allows you to answer them in "
        "seconds rather than re-reading the entire passage.\n\n"
        "**Sample passage:**\n"
        "\"Freshwater availability has declined sharply in regions that once considered water "
        "a permanent resource. Aquifers that took thousands of years to fill are being depleted "
        "at rates ten to forty times faster than natural recharge allows. Agricultural irrigation "
        "accounts for roughly seventy percent of global freshwater withdrawals, making farming "
        "practices the single most consequential variable in the crisis. Industrial cooling "
        "systems and municipal consumption compound the pressure. Climate models predict that "
        "precipitation patterns will shift further, reducing snowpack in mountainous regions "
        "that supply downstream rivers. Several nations have already begun rationing water "
        "during summer months. In response, engineers and policymakers have piloted desalination "
        "plants along coastlines, with energy costs remaining the primary obstacle to widespread "
        "adoption. Drip irrigation technology, when adopted broadly, has demonstrated the "
        "capacity to reduce agricultural water use by up to fifty percent. The evidence suggests "
        "that solutions exist but require coordinated investment at a scale no single government "
        "has yet committed to achieving. Whether the political will can match the technical "
        "capacity remains the defining question of the coming decades.\"\n\n"
        "**The five key structural patterns:**\n"
        "- **Problem-Solution**: the author identifies a crisis, then presents one or more remedies.\n"
        "- **Compare-Contrast**: two or more things are placed side by side to highlight similarities "
        "or differences.\n"
        "- **Cause-Effect**: the author explains what causes something or what results from a cause.\n"
        "- **Chronological**: events are presented in the order they occurred.\n"
        "- **General-to-Specific** (also called Claim-Evidence): a broad assertion is followed by "
        "increasingly specific evidence or examples.\n\n"
        "**How to identify structure using transition words:**\n"
        "'However,' 'in contrast,' 'on the other hand' signal contrast or compare-contrast. "
        "'As a result,' 'consequently,' 'therefore' signal cause-effect. "
        "'First... then... finally' signals chronological order. "
        "'For example,' 'specifically,' 'in particular' signal general-to-specific. "
        "'In response,' 'to address this,' 'one solution' signal problem-solution.\n\n"
        "**How paragraph relationships work:**\n"
        "SAT questions often ask how paragraph X relates to paragraph Y. Label each paragraph "
        "before reading the questions: P1 = Problem, P2 = Causes, P3 = Complications, P4 = "
        "Solutions. Once you have these labels, relationship questions become direct look-ups.\n\n"
        "**Worked example:**\n"
        "Q: The main purpose of the final two sentences of the passage is to --\n\n"
        "(A) introduce a new scientific discovery about desalination technology\n"
        "The final sentences discuss political will, not a new discovery. They are evaluative "
        "and forward-looking, not informational. Eliminate.\n\n"
        "(B) summarize the causes of the freshwater crisis identified earlier in the passage\n"
        "Causes are discussed in sentences two through five. The final sentences move beyond "
        "causes to pose a larger question about human response. Eliminate.\n\n"
        "(C) suggest that available technical solutions will succeed without political action\n"
        "This reverses the passage's point. The passage explicitly says solutions 'require "
        "coordinated investment' and asks whether 'political will can match technical capacity.' "
        "The author is raising doubt, not expressing confidence. Eliminate.\n\n"
        "(D) frame the freshwater crisis as a problem whose resolution depends on political "
        "commitment, not just technical capacity\n"
        "This accurately captures the final sentences: solutions exist ('technical capacity'), "
        "but political will is the unresolved variable. This is the correct answer.\n\n"
        "⚠️ Common mistake: choosing 'to provide an example' when a sentence is actually "
        "drawing a conclusion or posing a question. Always ask: what is the sentence *doing* "
        "in relation to the rest of the passage, not just what it is *about*.\n\n"
        "💡 Tip: Before reading the questions, spend 20 seconds labeling each paragraph or "
        "major section with a single word (Problem, Cause, Solution, Contrast, Evidence). "
        "This mental map makes structure questions faster than any other strategy."
    ),
    (
        3,
        "**Author's Perspective and Point of View**\n\n"
        "Author's Perspective questions ask you to identify how the author feels about the subject "
        "of the passage -- not just what the passage says, but the attitude the author brings to "
        "it. The SAT tests whether you can distinguish between the author's own voice and the "
        "voices of sources the author cites, and whether you can read subtle signals of approval, "
        "skepticism, enthusiasm, or criticism embedded in word choice and sentence structure.\n\n"
        "**Sample passage:**\n"
        "\"Professor Hartley has argued for decades that class size is the primary determinant of "
        "student academic outcomes, citing a landmark study from his own institution as definitive "
        "evidence. His conviction is admirable in its consistency, if not always in its "
        "precision. Subsequent large-scale analyses across multiple countries have produced "
        "a more ambiguous picture: class size appears to matter most in the earliest grades and "
        "for the most economically disadvantaged students, while showing negligible effects in "
        "secondary schools with already-trained teachers. The education research community "
        "has largely moved toward a consensus that teacher quality, instructional method, and "
        "family engagement each outweigh class size as predictors of long-term achievement. "
        "Hartley's continued insistence on a single-factor explanation strikes many of his peers "
        "as increasingly difficult to defend against the weight of the accumulated evidence. "
        "Policymakers who base budget decisions on his framework risk misallocating resources "
        "that could be directed toward interventions with stronger empirical support. The debate "
        "is not merely academic: billions in public funds depend on which variables decision-makers "
        "choose to prioritize. A more honest accounting of the evidence would serve students "
        "far better than advocacy dressed as science.\"\n\n"
        "**Identifying author attitude:**\n"
        "Look for evaluative adjectives and adverbs: 'admirable,' 'flawed,' 'increasingly difficult,' "
        "'more honest.' These signal judgment. Look for hedging language: 'while,' 'although,' "
        "'despite' -- these signal that the author is about to qualify or contradict the preceding idea. "
        "The author's own thesis usually appears in the final sentence or near-final sentence.\n\n"
        "**Distinguishing author voice from cited sources:**\n"
        "When an author writes 'Professor Hartley has argued,' Hartley's view is being reported, "
        "not endorsed. The author's own position emerges in sentences without attribution verbs -- "
        "sentences where the author speaks directly rather than quoting or paraphrasing a source.\n\n"
        "**Hedging vs. confident assertion:**\n"
        "Hedging: 'appears to matter,' 'may suggest,' 'could indicate' -- the author is uncertain.\n"
        "Confident: 'strikes many peers as indefensible,' 'would serve students far better' -- "
        "the author is making a direct evaluative claim.\n\n"
        "**Worked example:**\n"
        "Q: The author's perspective on Professor Hartley's research can best be described as --\n\n"
        "(A) enthusiastic endorsement of a groundbreaking body of scholarship\n"
        "The author calls Hartley's conviction 'admirable in its consistency, if not always in "
        "its precision' -- that 'if not' clause immediately undercuts any endorsement. The phrase "
        "'advocacy dressed as science' in the final sentence is openly critical. Eliminate.\n\n"
        "(B) qualified skepticism: the author acknowledges Hartley's contribution but finds his "
        "single-factor framework increasingly unsupported by evidence\n"
        "This matches the passage's structure precisely. The author concedes consistency and "
        "admirable conviction, then pivots to list all the evidence that contradicts Hartley's "
        "conclusion. The final sentence explicitly calls for 'a more honest accounting.' This is "
        "the correct answer.\n\n"
        "(C) complete indifference, presenting both sides without taking a position\n"
        "The author clearly takes a position -- the final two sentences are direct recommendations "
        "and critiques. Indifference would mean the author never evaluates, which is not the case. Eliminate.\n\n"
        "(D) full agreement with the education research community's consensus position\n"
        "The author references the community's consensus but does not simply defer to it -- the "
        "author makes an independent argument about resource allocation and honest evidence. "
        "Mere agreement would not produce this level of direct argumentation. Eliminate.\n\n"
        "⚠️ Common mistake: attributing a cited source's view to the author. Always ask: does "
        "the author endorse this view, or merely report it? Verbs like 'argues,' 'claims,' "
        "'contends,' and 'insists' signal reporting, not endorsement.\n\n"
        "💡 Tip: Underline every verb of attribution in the passage (argues, claims, contends, "
        "suggests, warns). Sentences without such verbs are almost always the author speaking "
        "in their own voice -- those are the sentences that reveal perspective."
    ),
    (
        4,
        "**Evaluating Arguments**\n\n"
        "Evaluating Arguments questions ask you to assess the logical structure of a passage. "
        "You will need to identify the author's main claim (conclusion), the evidence offered "
        "to support it (premises), and the hidden beliefs the argument depends on but never "
        "states (assumptions). You may also be asked which new piece of information would "
        "strengthen or weaken the argument, or what type of evidence is being used.\n\n"
        "**Sample passage:**\n"
        "\"Across fifteen elementary schools in the Westbrook district, students who participated "
        "in after-school music programs for at least one academic year scored an average of "
        "twelve percentile points higher on standardized reading assessments than students who "
        "did not participate. The music programs involved structured practice in rhythm, notation "
        "reading, and ensemble coordination. District administrators have concluded that expanding "
        "music education to all elementary students will produce meaningful gains in reading "
        "achievement across the district. The proposed expansion would cost approximately "
        "three million dollars annually and would require hiring forty-two additional music "
        "teachers. Administrators argue this investment is justified by the projected academic "
        "returns. Critics have noted that students who choose extracurricular activities tend "
        "to have more parental involvement, which is itself a strong predictor of academic "
        "performance. The district has not yet published a study controlling for parental "
        "engagement levels among participants and non-participants.\"\n\n"
        "**Argument anatomy:**\n"
        "- **Claim (conclusion):** Expanding music education will raise reading scores district-wide.\n"
        "- **Evidence (premises):** Music program participants scored 12 percentile points higher.\n"
        "- **Assumption (unstated):** The music program itself caused the higher scores, not some "
        "other characteristic shared by students who chose to participate.\n\n"
        "**Types of evidence and their strengths:**\n"
        "- **Anecdotal:** one person's story or a single example. Weakest -- cannot generalize.\n"
        "- **Statistical:** based on a sample. Stronger, but watch for selection bias.\n"
        "- **Experimental (randomized):** participants assigned randomly to conditions. Strongest "
        "for establishing causation.\n"
        "- **Expert opinion:** authority speaks. Useful but can be biased or outdated.\n\n"
        "**Strengthening vs. weakening:**\n"
        "A strengthener makes the link between evidence and conclusion more convincing. A "
        "weakener introduces doubt about that link -- usually by showing an alternative "
        "explanation or exposing an assumption. Target the connection between premise and "
        "conclusion, not peripheral facts.\n\n"
        "**Worked example:**\n"
        "Q: Which of the following, if true, would most directly weaken the district's argument?\n\n"
        "(A) Music programs in neighboring districts have also produced positive outcomes for students\n"
        "This would actually support the argument by showing the finding is replicable. It "
        "does not expose any flaw in the Westbrook reasoning. Eliminate.\n\n"
        "(B) Hiring forty-two music teachers will take two academic years due to certification requirements\n"
        "This is a practical implementation concern, not a logical challenge to the causal "
        "claim that music education raises reading scores. It weakens feasibility, not the argument. Eliminate.\n\n"
        "(C) Students who self-select into after-school activities have, on average, significantly "
        "higher levels of parental involvement than those who do not, and parental involvement is "
        "a documented predictor of reading achievement\n"
        "This directly targets the argument's core assumption. If parental involvement -- not "
        "music education -- is what drives the score difference, then the observed correlation "
        "does not establish that music caused the gain. Expanding the program to all students "
        "(including those without high parental involvement) would not replicate the effect. "
        "This is the correct answer.\n\n"
        "(D) Reading assessments are imperfect measures of literacy and omit several important skills\n"
        "This challenges the measurement tool but not the causal claim. Even if the test is "
        "imperfect, the argument's logic about music education still stands or falls on "
        "whether music caused the observed difference. Eliminate.\n\n"
        "⚠️ Common mistake: choosing an answer that attacks a side point (cost, implementation "
        "time, test quality) rather than the central assumption that connects the evidence to "
        "the conclusion. Weaken questions require you to break the logical chain, not criticize "
        "the program's practicality.\n\n"
        "💡 Tip: Always locate the conclusion first -- look for signal words like 'therefore,' "
        "'thus,' 'so,' 'hence,' 'this means,' or 'we conclude.' Everything before the conclusion "
        "is a premise. The assumption is the hidden bridge between them. Attack the bridge."
    ),
    (
        5,
        "**Analyzing Rhetorical Choices**\n\n"
        "Rhetorical Choices questions ask not just what an author says but why the author chose "
        "to say it in a particular way. Every word, example, structural choice, and tonal shift "
        "is a deliberate decision. The SAT asks you to explain the effect those decisions create "
        "on the reader and how they serve the author's larger purpose.\n\n"
        "**Sample passage:**\n"
        "\"In 1970, the Cuyahoga River in Ohio caught fire -- not for the first time, but for the "
        "last time before national outrage forced a legislative response. The image of a river "
        "in flames became a symbol so powerful that it accelerated the passage of the Clean "
        "Water Act and the creation of the Environmental Protection Agency. Thirteen-year-old "
        "Elena Vasquez, growing up two miles from that same river today, cannot name a single "
        "body of water in her state that meets federal safety standards for swimming. She has "
        "never gone fishing with her father because the fish are contaminated with industrial "
        "runoff from facilities that were issued permits after lobbying the very agency created "
        "to protect her. The legal mechanisms exist. The regulatory architecture is in place. "
        "What is absent is the political courage to enforce them against those with the financial "
        "power to resist. We have already burned our rivers once. Whether we choose to burn them "
        "again through indifference and institutional capture is the question this generation "
        "must answer.\"\n\n"
        "**The three rhetorical appeals:**\n"
        "- **Logos** (logic/evidence): the author uses data, causal reasoning, or systematic "
        "argument to persuade. ('The legal mechanisms exist.')\n"
        "- **Ethos** (credibility): the author establishes trustworthiness through expertise, "
        "credentials, or fair acknowledgment of complexity.\n"
        "- **Pathos** (emotion): the author uses personal stories, vivid imagery, or moral "
        "framing to generate an emotional response. (Elena's story.)\n\n"
        "**Tone shifts and their effects:**\n"
        "Notice how the passage shifts from historical narrative (Cuyahoga River, 1970) to a "
        "personal story (Elena) to a short, declarative verdict ('The legal mechanisms exist. "
        "The regulatory architecture is in place.') to a direct challenge to the reader. "
        "Each shift changes the register: historical -> personal -> analytical -> urgent. "
        "These shifts are deliberate and their purpose is to move the reader from informed to "
        "emotionally invested to morally challenged.\n\n"
        "**Specific diction choices:**\n"
        "Formal vs. informal. Technical vs. accessible. Abstract vs. concrete. When an author "
        "uses a child's name and specific details (two miles from the river, fishing with her "
        "father), the choice converts an abstract problem into a human face.\n\n"
        "**Worked example:**\n"
        "Q: Why does the author include the story of Elena Vasquez?\n\n"
        "(A) To provide verified statistical data about water quality in Ohio\n"
        "Elena's story is a personal anecdote, not a data set. No citation or measurement is "
        "offered. The author is not making a factual claim about Ohio statistics. Eliminate.\n\n"
        "(B) To introduce a counterargument that the Clean Water Act was ineffective\n"
        "Elena's story does not argue against the Clean Water Act's intent -- it argues that "
        "enforcement has failed. The purpose is not to undermine the law but to show its "
        "betrayal in practice. Eliminate.\n\n"
        "(C) To contrast the historical progress of 1970 with the ongoing failure to protect "
        "communities that still lack access to clean water, using a specific human story to "
        "make that failure emotionally concrete\n"
        "This captures the rhetorical purpose exactly. The Cuyahoga story represents legislative "
        "progress; Elena's story represents present-day failure. The author uses a named child "
        "to make an abstract policy failure feel personal and urgent -- a pathos move that "
        "anchors the argument's emotional core. This is the correct answer.\n\n"
        "(D) To shift the passage's focus away from environmental law and toward education policy\n"
        "The passage never leaves the subject of environmental regulation and enforcement. "
        "Elena's story is entirely about water quality and the EPA, not education. Eliminate.\n\n"
        "⚠️ Common mistake: saying a detail 'provides additional evidence' when it is actually "
        "functioning as a pathos appeal. Evidence and emotional illustration serve different "
        "rhetorical functions -- know the difference.\n\n"
        "💡 Tip: Ask yourself: what would this passage lose if this detail, word, or example "
        "were removed? That loss is the rhetorical function of the detail. The answer choice "
        "that best names that loss is correct."
    ),
    (
        6,
        "**Cross-Text Connections**\n\n"
        "Cross-Text Connections questions give you two short passages on the same topic written "
        "from different perspectives -- sometimes complementary, sometimes directly opposed. "
        "You must map each author's main claim, identify where they agree and where they "
        "diverge, and then answer questions about how one author would respond to the other. "
        "This question type rewards systematic thinking over guesswork.\n\n"
        "**Text 1:**\n"
        "\"The case for four-day workweeks has moved well beyond theoretical advocacy. "
        "A 2022 pilot involving thirty-three companies across the United Kingdom found that "
        "productivity, measured by revenue and output per employee, remained stable or "
        "improved in ninety-two percent of participating firms. Employee-reported well-being "
        "scores rose significantly, and voluntary turnover dropped by an average of fifty-seven "
        "percent during the trial period. Six months after the pilot ended, twenty-nine of the "
        "thirty-three companies had retained the four-day schedule permanently. The data "
        "challenge the assumption that hours worked is the correct proxy for productive value.\"\n\n"
        "**Text 2:**\n"
        "\"Enthusiasm for the four-day workweek reflects the priorities of knowledge workers in "
        "white-collar sectors, not the reality of industries where output is directly tied to "
        "time on the floor. Manufacturing, healthcare, logistics, and retail cannot simply "
        "redistribute their labor across four days without reducing service availability or "
        "driving up overtime costs. The UK pilot, frequently cited by advocates, drew almost "
        "entirely from tech, marketing, and professional services firms -- the very sectors "
        "where asynchronous work is already common and where productivity metrics are most "
        "easily decoupled from clock hours. Generalizing its results to the broader economy "
        "requires assumptions the data cannot support.\"\n\n"
        "**Mapping strategy:**\n"
        "After reading both texts, write one sentence per author before reading the questions:\n"
        "Author 1: Pilot data from the UK show that four-day workweeks maintain productivity "
        "and improve employee outcomes across a range of firms.\n"
        "Author 2: The UK pilot is drawn from a narrow, unrepresentative set of industries, "
        "and its findings cannot be generalized to the broader economy.\n\n"
        "**Where they agree:** Both authors acknowledge the UK pilot exists and that it involves "
        "productivity data. Neither disputes the facts of the study.\n"
        "**Where they disagree:** Author 1 treats the pilot as broadly applicable evidence. "
        "Author 2 argues the pilot's sample is too narrow to support broad policy conclusions.\n\n"
        "**Worked example 1:**\n"
        "Q: How would the author of Text 2 most likely respond to the claim in Text 1 that "
        "the UK pilot data 'challenge the assumption that hours worked is the correct proxy "
        "for productive value'?\n\n"
        "(A) By agreeing that hours worked is an outdated measure of productivity in all industries\n"
        "Author 2 explicitly argues the opposite for manufacturing and healthcare. This is "
        "directly contradicted by Text 2. Eliminate.\n\n"
        "(B) By acknowledging the pilot's findings within its sector but arguing that those "
        "findings cannot be generalized beyond knowledge-work industries\n"
        "This matches Author 2's logic precisely: concede the pilot's results within its "
        "specific context, then deny their generalizability. This is the correct answer.\n\n"
        "(C) By proposing that manufacturing and healthcare should adopt shorter workweeks first\n"
        "Text 2 argues these industries cannot adopt the model -- it does not suggest they "
        "should be first. This reverses the author's position. Eliminate.\n\n"
        "(D) By arguing that the UK pilot should be extended to more companies before any "
        "conclusions are drawn\n"
        "Text 2's objection is about industry composition, not sample size. More companies "
        "from the same sectors would not solve the representativeness problem. Eliminate.\n\n"
        "**Worked example 2:**\n"
        "Q: On which point would both authors most likely agree?\n\n"
        "(A) The four-day workweek should be adopted by all employers immediately\n"
        "Author 2 explicitly opposes this for several industries. Eliminate.\n\n"
        "(B) The UK pilot produced data on productivity and employee outcomes across participating firms\n"
        "Both authors reference the pilot and neither disputes its results -- they disagree only "
        "about what those results mean for policy. This is the correct answer.\n\n"
        "(C) Volunteer turnover is the most important measure of workplace policy success\n"
        "Neither author makes this claim. Eliminate.\n\n"
        "(D) Knowledge work and manufacturing require identical scheduling models\n"
        "Text 2 explicitly argues the opposite. Eliminate.\n\n"
        "⚠️ Common mistake: inventing a response that sounds logical but is not grounded in the "
        "text. For 'Author A would respond' questions, stay strictly within what Author A "
        "actually says in the passage -- do not extrapolate.\n\n"
        "💡 Tip: After reading both passages, write a one-sentence summary of each author's "
        "central claim before reading any question. This prevents you from conflating the two "
        "authors and makes comparison questions far easier to answer quickly."
    ),
    (
        7,
        "**SAT Craft & Structure Strategy**\n\n"
        "This lesson consolidates the skills from all six previous lessons into a unified, "
        "repeatable test-day process. The Craft & Structure domain makes up approximately "
        "twenty-eight percent of the digital SAT Reading and Writing section. Mastering the "
        "patterns of wrong answers is as important as mastering the correct strategies.\n\n"
        "**Sample passage (strategy in action):**\n"
        "\"The committee's report was careful to avoid the word 'failure,' preferring instead "
        "to characterize the project as an 'exploratory phase' that had 'surfaced valuable "
        "data.' Critics found this framing disingenuous. The project had consumed four years "
        "and ninety million dollars without producing a single deployable product. Supporters "
        "argued that the knowledge gained would accelerate future development, though they "
        "offered no timeline or benchmark by which this acceleration might be measured. "
        "The lead researcher, Dr. Priya Mehta, insisted in a statement that premature "
        "termination would forfeit the investment already made -- a sunk-cost argument that "
        "economists and project managers widely regard as a logical fallacy. Independent "
        "auditors, contracted by the legislature, recommended discontinuation and a formal "
        "review of the procurement process. The committee, whose members had approved the "
        "original funding, voted six to three to continue. The vote split precisely along "
        "the lines of which members had been publicly associated with the project's "
        "inception, raising questions that the committee's language of 'exploratory phases' "
        "did little to resolve.\"\n\n"
        "**Strategy 1 -- Vocabulary in context: context before dictionary**\n"
        "When you see a Words in Context question, resist the urge to rely on prior knowledge "
        "of the word. Read the surrounding sentences first. Ask: what must this word mean "
        "for the sentence to make sense in this passage? Predict, then match.\n\n"
        "**Strategy 2 -- Structure first: skim before questioning**\n"
        "Before reading the questions, spend twenty seconds labeling each paragraph's function "
        "(Problem / Cause / Solution / Evidence / Counterargument). When a question asks "
        "about a paragraph's purpose, you already have your answer.\n\n"
        "**Strategy 3 -- Author perspective: only the text counts**\n"
        "For 'the author would agree' questions, select only what is directly and explicitly "
        "supported in the passage. An answer that is plausible or that you agree with but "
        "that goes beyond the text is wrong.\n\n"
        "**Strategy 4 -- Cross-text questions: map before comparing**\n"
        "Always summarize each author's main claim in your own words before reading the "
        "answer choices. This two-sentence map prevents you from confusing the two voices "
        "and makes comparison questions mechanical rather than interpretive.\n\n"
        "**Strategy 5 -- Time management**\n"
        "Budget approximately seventy to ninety seconds per question. Vocabulary questions "
        "are typically the fastest -- three steps (read, predict, match) should take under "
        "sixty seconds. Cross-text questions require more setup but reward students who "
        "invest thirty seconds in mapping before reading the choices. If a question takes "
        "more than ninety seconds, eliminate two choices, select the better remaining option, "
        "flag it, and return at the end.\n\n"
        "**The top five Craft & Structure wrong-answer patterns:**\n"
        "1. **Dictionary definition trap:** the most common meaning of the word rather than "
        "the contextual meaning. Almost always a wrong answer on vocabulary questions.\n"
        "2. **Topic instead of purpose:** an answer that correctly identifies what the passage "
        "is about but misidentifies what the author is trying to accomplish.\n"
        "3. **Source confusion:** attributing a cited author's view to the passage author. "
        "Watch for attribution verbs.\n"
        "4. **Extreme language:** absolute words like 'always,' 'never,' 'proves,' or "
        "'all studies show' -- these almost never appear in correct answers.\n"
        "5. **Scope error:** an answer that correctly describes one sentence but presents it "
        "as the main idea, or an answer that goes beyond what the passage actually states.\n\n"
        "**Worked example (strategy application):**\n"
        "Q: As used in the passage, 'disingenuous' most nearly means --\n\n"
        "(A) technically accurate but intentionally misleading\n"
        "The critics find the committee's word choices dishonest -- the language of 'exploratory "
        "phase' is used to avoid the word 'failure' after ninety million dollars spent. "
        "'Technically accurate but intentionally misleading' captures this perfectly. The "
        "committee is not lying outright; it is choosing language designed to obscure. "
        "This is the correct answer.\n\n"
        "(B) factually incorrect and demonstrably false\n"
        "The report's language is evasive, not necessarily false. The passage does not say "
        "the committee made false statements -- only that critics found the framing misleading. Eliminate.\n\n"
        "(C) overly complicated and difficult for non-experts to understand\n"
        "The criticism is about honesty, not complexity. No one in the passage complains "
        "about jargon or inaccessibility. Eliminate.\n\n"
        "(D) neutral and designed to avoid taking any political position\n"
        "The committee's language is described as evasive, not neutral. Neutral language "
        "would not provoke criticism as dishonest. Eliminate.\n\n"
        "⚠️ Common mistake: skipping the prediction step and reading all four choices before "
        "committing to a meaning. Attractive wrong answers are designed to exploit students "
        "who have not formed their own prediction first. The prediction is not optional -- "
        "it is the single most effective guard against wrong-answer traps.\n\n"
        "💡 Tip: On the day of the test, treat every Craft & Structure question as two tasks: "
        "first, understand what the question is actually asking (circle the key verb -- "
        "'most nearly means,' 'primarily serves to,' 'best describes the author's perspective'); "
        "second, locate the specific evidence in the passage that answers it. Students who "
        "answer from evidence outscore students who answer from instinct on every question type."
    ),
]


class Command(BaseCommand):
    help = "Enrich lesson content for SAT RW: Craft & Structure"

    def handle(self, *args, **options):
        for order, content in LESSONS:
            rows = Lesson.objects.filter(
                course__slug="sat-rw-craft-structure", order=order
            ).update(content=content)
            self.stdout.write(f"  Lesson {order}: {rows} row(s) updated")
        self.stdout.write(
            self.style.SUCCESS(
                "Done enriching SAT RW: Craft & Structure lessons."
            )
        )
