"""
Enrich lesson content for the 'SAT Math: Complete Course & Test Prep' course.

Run:
    python manage.py enrich_sat_math_complete
"""
from django.core.management.base import BaseCommand
from courses.models import Lesson


LESSONS = [
    (
        1,
        "**Linear Equations & Slope** are the single most-tested topic on the SAT. Every question in this family rests on one core idea: an equation describes a straight line, and solving it means finding the value (or values) that make both sides equal.\n\n"
        "**Slope-intercept form** is the most useful way to write a line: y = mx + b. The coefficient **m** is the **slope** -- it measures how steeply the line rises or falls. The constant **b** is the **y-intercept** -- the point where the line crosses the y-axis (i.e., when x = 0). In y = 3x - 2, the slope is 3 (for every 1 unit right, the line goes up 3) and the y-intercept is -2.\n\n"
        "**Calculating slope from two points** uses the rise-over-run formula: m = (y2 - y1) / (x2 - x1). For the points (1, 4) and (3, 10): m = (10 - 4) / (3 - 1) = 6 / 2 = 3. Always subtract in the same order on top and bottom.\n\n"
        "[[figure:slope_types|Types of slope -- positive, negative, zero, undefined]]\n\n"
        "The four slope types:\n"
        "- **Positive slope:** Line rises from left to right (m > 0)\n"
        "- **Negative slope:** Line falls from left to right (m < 0)\n"
        "- **Zero slope:** Perfectly horizontal line (m = 0), written y = k\n"
        "- **Undefined slope:** Perfectly vertical line, written x = k\n\n"
        "**Other forms of a linear equation:**\n"
        "- **Point-slope form:** y - y1 = m(x - x1). Use this when you know the slope and one point but not b. To find the equation of a line with slope 2 through (3, 7): y - 7 = 2(x - 3) -> y = 2x + 1.\n"
        "- **Standard form:** Ax + By = C. Useful in systems of equations. Convert to slope-intercept by solving for y: from 2x + 3y = 12, get y = (12 - 2x)/3 = 4 - (2/3)x.\n\n"
        "**Solving linear equations** means undoing operations to isolate the variable:\n"
        "- **One-step:** x + 9 = 15 -> subtract 9 -> x = 6.\n"
        "- **Two-step:** 2x - 4 = 10 -> add 4 -> 2x = 14 -> divide by 2 -> x = 7.\n"
        "- **Multi-step:** 3(x - 2) + x = 14 -> distribute -> 3x - 6 + x = 14 -> combine -> 4x = 20 -> x = 5.\n\n"
        "**Special cases:** When you solve and the variable disappears entirely, check what's left:\n"
        "- **No solution:** You get a false statement like 3 = 7. The two sides represent parallel lines that never cross.\n"
        "- **Infinite solutions:** You get a true statement like 5 = 5. Both sides represent the same line.\n\n"
        "**Parallel and perpendicular lines:**\n"
        "- Parallel lines have the **same slope** (but different y-intercepts): m1 = m2.\n"
        "- Perpendicular lines have slopes that are **negative reciprocals**: m1 * m2 = -1. If one line has slope 3, the perpendicular slope is -1/3.\n\n"
        "**Worked Example 1 (SAT-style, Easy):** The line y = -4x + 7 is parallel to which of the following?\n"
        "- The slope of the given line is -4.\n"
        "- A parallel line also has slope -4.\n"
        "- Answer: any line of the form y = -4x + b (where b is not 7). For example, y = -4x + 2.\n\n"
        "**Worked Example 2 (SAT-style, Medium):** A line passes through (2, 1) and (6, 9). What is the y-intercept?\n"
        "- Step 1 -- Slope: m = (9 - 1) / (6 - 2) = 8 / 4 = 2.\n"
        "- Step 2 -- Point-slope: y - 1 = 2(x - 2) -> y = 2x - 3.\n"
        "- The y-intercept is **-3**.\n\n"
        "⚠️ Common mistake: In y = -2x + 5, students often identify the slope as 5 and the y-intercept as -2. Remember: the slope is always attached to x (here, m = -2), and the y-intercept is the standalone constant (b = 5).\n\n"
        "💡 Tip: To find a perpendicular slope quickly, flip the fraction and change the sign. Slope 2/3 becomes perpendicular slope -3/2. The product of perpendicular slopes always equals -1."
    ),
    (
        2,
        "**Systems of Linear Equations** ask you to find a single (x, y) pair that satisfies two equations simultaneously. Graphically, the solution is the **intersection point** of two lines.\n\n"
        "**Method 1 -- Substitution:** Best when one variable is already isolated (or easy to isolate).\n"
        "- Step 1: Solve one equation for one variable.\n"
        "- Step 2: Substitute that expression into the other equation.\n"
        "- Step 3: Solve the resulting single-variable equation.\n"
        "- Step 4: Substitute back to find the second variable.\n\n"
        "Full example: y = 2x - 1 and 3x + y = 14.\n"
        "- Substitute y: 3x + (2x - 1) = 14 -> 5x - 1 = 14 -> 5x = 15 -> x = 3.\n"
        "- Back-substitute: y = 2(3) - 1 = 5. Solution: (3, 5).\n"
        "- Verify in the second equation: 3(3) + 5 = 14. Confirmed.\n\n"
        "**Method 2 -- Elimination (Addition Method):** Best when both equations are in standard form Ax + By = C.\n"
        "- Step 1: Multiply one or both equations so that one variable has equal and opposite coefficients.\n"
        "- Step 2: Add the equations -- that variable cancels.\n"
        "- Step 3: Solve for the remaining variable, then back-substitute.\n\n"
        "Full example (requires scaling): 3x + 2y = 11 and 5x + 4y = 21.\n"
        "- Multiply the first equation by 2: 6x + 4y = 22.\n"
        "- Subtract the second equation: (6x + 4y) - (5x + 4y) = 22 - 21 -> x = 1.\n"
        "- Back-substitute: 3(1) + 2y = 11 -> 2y = 8 -> y = 4. Solution: (1, 4).\n\n"
        "**Three possible outcomes -- how to detect each:**\n"
        "- **One solution:** After solving, you get specific values for both x and y. The lines have different slopes and cross at exactly one point.\n"
        "- **No solution:** After eliminating a variable, you get a contradiction like 0 = 5. In slope-intercept form, both equations have the same slope but different y-intercepts -- parallel lines that never meet.\n"
        "- **Infinite solutions:** After eliminating, you get a tautology like 0 = 0. Both equations represent the same line (identical slope and y-intercept).\n\n"
        "**SAT shortcut -- don't solve for x and y separately:** If the question asks for x + y, x - y, 2x + 3y, or any linear combination, try adding or subtracting the two equations directly. This can produce the target expression in one step.\n\n"
        "**Worked Example 1 (shortcut):** If x + y = 10 and x - y = 4, what is the value of x + y?\n"
        "- The answer is right in the first equation: x + y = **10**. No algebra required.\n\n"
        "**Worked Example 2 (word problem):** A store sells pens for $2 and notebooks for $5. A customer buys 8 items for $25. How many notebooks did the customer buy?\n"
        "- Let p = pens, n = notebooks. System: p + n = 8 and 2p + 5n = 25.\n"
        "- Multiply first equation by 2: 2p + 2n = 16. Subtract from second: 3n = 9 -> n = 3.\n"
        "- The customer bought **3 notebooks** (and 5 pens).\n\n"
        "⚠️ Common mistake: After solving for one variable, students often forget to find the second. If the problem asks for x + y, you need both values -- or use the shortcut above.\n\n"
        "💡 Tip: Before doing any algebra, look at the structure of both equations. If you need x + y or 2x - y, try adding or subtracting the equations first. This SAT shortcut saves 60+ seconds per problem."
    ),
    (
        3,
        "**Linear Inequalities & Absolute Value** extend the algebra of equations to ranges of values and distances. These concepts appear in about 10-15% of SAT Math questions.\n\n"
        "**Solving linear inequalities** follows the same steps as solving equations, with one critical difference:\n"
        "- **The Flip Rule:** Whenever you multiply or divide both sides by a **negative number**, flip the inequality sign.\n\n"
        "Example: -3x + 6 <= 18.\n"
        "- Subtract 6: -3x <= 12.\n"
        "- Divide by -3 and flip the sign: x >= -4.\n\n"
        "Example without flipping: 2x - 5 > 7.\n"
        "- Add 5: 2x > 12.\n"
        "- Divide by 2 (positive -- no flip): x > 6.\n\n"
        "**Compound inequalities** combine two conditions:\n"
        "- **AND (conjunction):** Both conditions must hold. Written as a sandwich: -2 < x <= 5. On the number line, shade the **overlap** (intersection) of both regions. In interval notation: (-2, 5].\n"
        "- **OR (disjunction):** At least one condition holds. Example: x < -1 or x > 4. On the number line, shade the **union** of both regions -- two separate segments. In interval notation: (-inf, -1) U (4, +inf).\n\n"
        "**Interval notation quick reference:**\n"
        "- Parentheses ( ) for strict inequalities (< or >): endpoint is NOT included.\n"
        "- Brackets [ ] for inclusive inequalities (<= or >=): endpoint IS included.\n"
        "- x > a -> (a, +inf); x >= a -> [a, +inf); x < b -> (-inf, b); x <= b -> (-inf, b].\n\n"
        "**Absolute value equations:** The absolute value |x| represents the distance from zero on the number line. It is always non-negative. Because |x| = k means x is exactly k units from zero, there are two cases:\n"
        "- |x| = k means x = k OR x = -k (two solutions when k > 0; one solution when k = 0; no solution when k < 0).\n\n"
        "Example: |2x - 3| = 7.\n"
        "- Case 1: 2x - 3 = 7 -> 2x = 10 -> x = 5.\n"
        "- Case 2: 2x - 3 = -7 -> 2x = -4 -> x = -2.\n"
        "- Two solutions: x = 5 or x = -2.\n\n"
        "**Absolute value inequalities:** Think of these in terms of distance from zero:\n"
        "- |x| < k means -k < x < k (the value is WITHIN k units of zero -- an AND compound inequality).\n"
        "- |x| > k means x < -k OR x > k (the value is MORE THAN k units from zero -- an OR compound inequality).\n\n"
        "**Worked Example 1 (compound):** Solve -1 < 3x - 4 < 11.\n"
        "- Add 4 to all three parts: 3 < 3x < 15.\n"
        "- Divide by 3: 1 < x < 5. Interval notation: (1, 5).\n\n"
        "**Worked Example 2 (absolute value inequality):** Solve |x - 2| <= 5.\n"
        "- Expand: -5 <= x - 2 <= 5.\n"
        "- Add 2: -3 <= x <= 7. Interval notation: [-3, 7].\n"
        "- Meaning: x is within 5 units of 2 on the number line.\n\n"
        "⚠️ Common mistake: Forgetting to flip the inequality sign when dividing by a negative. In -3x > 9, dividing by -3 gives x < -3 (sign flips), not x > -3. This is the most frequently missed rule in SAT algebra.\n\n"
        "💡 Tip: For absolute value inequalities, memorize two patterns: 'less than' -> sandwich (AND); 'greater than' -> two separate tails (OR). If you remember those two shapes, you'll never mix them up."
    ),
    (
        4,
        "**Ratios, Proportions & Percentages** make up the core of SAT Problem-Solving and Data Analysis. These questions often appear in real-world contexts involving prices, rates, mixtures, and scaling.\n\n"
        "**Ratios** compare two quantities. A ratio can be written as a:b, a/b, or 'a to b'. There are two types:\n"
        "- **Part-to-part:** comparing one part to another (e.g., boys:girls = 3:5).\n"
        "- **Part-to-whole:** comparing one part to the total (e.g., boys:total = 3:8).\n"
        "To simplify a ratio, divide both numbers by their GCF: 12:16 simplifies to 3:4.\n\n"
        "**Proportions** set two ratios equal: a/b = c/d. Solve by **cross-multiplying**: a*d = b*c.\n\n"
        "Example: 3/4 = x/20 -> 4x = 60 -> x = 15.\n\n"
        "**Percent** means 'per hundred'. The core relationship: part = percent * whole.\n"
        "- Finding a percent: what percent of 80 is 20? -> 20/80 = 0.25 = 25%.\n"
        "- Finding the part: what is 15% of 60? -> 0.15 * 60 = 9.\n"
        "- Finding the whole: 30 is 25% of what? -> 30 / 0.25 = 120.\n\n"
        "**Percent increase and decrease:**\n"
        "- Percent change = (change / original) * 100.\n"
        "- A price rises from $40 to $50: change = 10; percent change = (10/40) * 100 = 25% increase.\n"
        "- Shortcut: multiply the original by (1 + rate) for increase or (1 - rate) for decrease.\n"
        "- 20% increase on $80: 80 * 1.20 = $96.\n"
        "- 15% decrease on $200: 200 * 0.85 = $170.\n\n"
        "**Finding the original after a percent change:** If the new value and the rate are known, divide by the multiplier.\n"
        "- After a 25% increase, the price is $75. Original = 75 / 1.25 = $60.\n\n"
        "**Successive percent changes:** Do NOT add the rates together. Multiply the multipliers.\n"
        "- A 20% increase followed by a 20% decrease: 1.20 * 0.80 = 0.96 -> a net 4% decrease, not 0%.\n"
        "- Example: $100 increases 30% to $130, then decreases 10%: 130 * 0.90 = $117.\n\n"
        "**Worked Example 1 (proportion with context):** A recipe requires 3 cups of flour for every 2 cups of sugar. If you use 9 cups of flour, how many cups of sugar do you need?\n"
        "- Set up the proportion: 3/2 = 9/x.\n"
        "- Cross-multiply: 3x = 18 -> x = 6 cups of sugar.\n\n"
        "**Worked Example 2 (successive percent changes):** A jacket costs $120. The store first increases the price by 25%, then offers a 20% discount. What is the final price?\n"
        "- After 25% increase: 120 * 1.25 = $150.\n"
        "- After 20% decrease: 150 * 0.80 = $120.\n"
        "- The final price is $120 -- back to the original, but only because the numbers happened to cancel. This will NOT always be the case.\n\n"
        "⚠️ Common mistake: Using the new value as the 'original' in a percent change calculation. Percent change always divides by the STARTING value. If a price goes from $50 to $60, the increase is (60-50)/50 = 20%, not (60-50)/60 = 16.7%.\n\n"
        "💡 Tip: For successive percent changes, multiply the decimal multipliers together. A 30% increase then a 10% decrease is 1.30 * 0.90 = 1.17, a net 17% increase. This is always faster than computing step by step."
    ),
    (
        5,
        "**Data Analysis & Statistics** account for roughly 20% of SAT Math questions. These questions test your ability to summarize, interpret, and draw conclusions from data presented in tables, graphs, and scatterplots.\n\n"
        "**Measures of center and spread:**\n"
        "- **Mean (average):** Sum all values, divide by the count. For 4, 8, 10, 10, 8: mean = 40/5 = 8.\n"
        "- **Median:** The middle value when data is sorted in order. For an odd count, it's the exact middle. For an even count, average the two middle values. For 3, 7, 9, 12, 20: median = 9.\n"
        "- **Mode:** The most frequently occurring value. For 4, 8, 10, 10, 8: both 8 and 10 appear twice (bimodal).\n"
        "- **Range:** Largest value minus smallest value. For the set above: 20 - 3 = 17.\n\n"
        "**Effect of outliers:** An **outlier** is an extreme value far from the others. Key impacts:\n"
        "- Outliers pull the **mean** significantly (mean is sensitive to extreme values).\n"
        "- Outliers barely affect the **median** (median is resistant; it only cares about position).\n"
        "- Outliers have no effect on the **mode**.\n"
        "Rule of thumb: when data is skewed by outliers, the **median** is a better measure of 'typical' than the mean.\n\n"
        "**Two-way tables** display data categorized by two variables. Read them carefully:\n"
        "- **Joint frequency:** The count in any individual cell (both conditions apply).\n"
        "- **Marginal frequency:** The row or column total.\n"
        "- **Conditional frequency:** A cell count divided by its row or column total. Example: 'What fraction of males preferred option A?' divides the cell (male AND option A) by the total males row.\n\n"
        "**Scatterplots and line of best fit:**\n"
        "- A **positive association** means both variables increase together (line slopes upward).\n"
        "- A **negative association** means as one variable increases, the other decreases (line slopes downward).\n"
        "- The **slope** of the line of best fit represents the rate of change of the y-variable per unit change in the x-variable. Interpret it in context: 'For each additional year, the population increases by 250 people.'\n"
        "- The **y-intercept** represents the predicted y-value when x = 0. Always check if this makes contextual sense.\n"
        "- Correlation does NOT imply causation. Two variables can have a strong association without one causing the other.\n\n"
        "**Probability basics:**\n"
        "- P(A) = (number of favorable outcomes) / (total number of outcomes).\n"
        "- **Complement rule:** P(not A) = 1 - P(A).\n"
        "- **Independent events:** P(A and B) = P(A) * P(B). Events are independent when the outcome of one does not affect the other.\n\n"
        "**Sampling:** A good sample is **representative** of the population -- it should be randomly selected and large enough to minimize bias. Common SAT biases:\n"
        "- **Convenience sampling:** Surveying only people who are easy to reach.\n"
        "- **Voluntary response bias:** Only people with strong opinions respond.\n"
        "- **Undercoverage:** Some groups in the population are underrepresented.\n\n"
        "**Worked Example 1 (two-way table):** In a survey of 100 students, 40 are seniors. Of the seniors, 30 prefer math. What is the conditional probability that a student prefers math, given that they are a senior?\n"
        "- P(prefers math | senior) = 30/40 = 0.75 or 75%.\n\n"
        "**Worked Example 2 (line of best fit):** A scatterplot shows the line y = 2.5x + 10, where x is hours studied and y is test score. What does the slope 2.5 represent?\n"
        "- For each additional hour studied, the predicted test score increases by **2.5 points**.\n\n"
        "⚠️ Common mistake: Confusing joint frequency with conditional frequency in two-way tables. 'What percent of the total are female seniors?' uses the grand total as the denominator. 'What percent of seniors are female?' uses only the senior total as the denominator.\n\n"
        "💡 Tip: When a question asks which measure of center best represents a skewed data set, choose the median. The mean gets pulled toward extreme values; the median stays in the middle where most data actually sits."
    ),
    (
        6,
        "**Functions & Quadratics** are tested heavily in the Advanced Math section of the SAT, which now makes up about 35% of all math questions. Understanding function notation, transformations, and quadratics puts a major chunk of the test within reach.\n\n"
        "**Function notation:** f(x) means 'the output of function f when the input is x.' It does NOT mean f multiplied by x.\n"
        "- **Evaluating:** f(a) means substitute a for every x. If f(x) = 3x - 5, then f(4) = 3(4) - 5 = 7.\n"
        "- **Solving f(x) = a:** Set the expression equal to a and solve. If f(x) = 3x - 5 = 7, then 3x = 12, so x = 4.\n\n"
        "**Function transformations** shift, reflect, or stretch the graph:\n"
        "- **Vertical shift up:** f(x) + k shifts the graph up k units.\n"
        "- **Vertical shift down:** f(x) - k shifts down k units.\n"
        "- **Horizontal shift right:** f(x - h) shifts right h units (note: minus inside means right).\n"
        "- **Horizontal shift left:** f(x + h) shifts left h units.\n"
        "- **Reflection over x-axis:** -f(x) flips the graph upside down.\n"
        "- **Composition:** f(g(x)) means apply g first, then apply f to the result. If f(x) = x + 1 and g(x) = 2x, then f(g(3)) = f(6) = 7.\n\n"
        "**Quadratic equations** contain an x^2 term and graph as a **parabola**. Three methods to solve them:\n"
        "- **Factoring:** x^2 - 5x + 6 = 0 -> (x - 2)(x - 3) = 0 -> x = 2 or x = 3. Find two numbers that multiply to c and add to b.\n"
        "- **Quadratic formula:** x = (-b +/- sqrt(b^2 - 4ac)) / (2a). Works for any quadratic ax^2 + bx + c = 0.\n"
        "- **The discriminant b^2 - 4ac** tells you how many real solutions exist: positive -> two solutions; zero -> one solution (tangent); negative -> no real solutions.\n\n"
        "[[figure:parabola|A parabola with vertex and zeros labeled]]\n\n"
        "**Vertex form:** f(x) = a(x - h)^2 + k.\n"
        "- The **vertex** is (h, k) -- the highest or lowest point of the parabola.\n"
        "- The **axis of symmetry** is the vertical line x = h.\n"
        "- If a > 0, the parabola opens upward (minimum at vertex); if a < 0, it opens downward (maximum at vertex).\n\n"
        "**Worked Example 1 (function evaluation + transformation):** If f(x) = x^2 - 4 and g(x) = f(x + 3), write the formula for g(x) and find g(1).\n"
        "- g(x) = f(x + 3) = (x + 3)^2 - 4 = x^2 + 6x + 9 - 4 = x^2 + 6x + 5.\n"
        "- g(1) = 1 + 6 + 5 = 12.\n\n"
        "**Worked Example 2 (quadratic):** A ball's height is h(t) = -16t^2 + 64t + 5, where t is in seconds. What is the maximum height?\n"
        "- Maximum height is at the vertex. t = -b/(2a) = -64/(2*(-16)) = -64/(-32) = 2 seconds.\n"
        "- Maximum height: h(2) = -16(4) + 64(2) + 5 = -64 + 128 + 5 = **69 feet**.\n\n"
        "⚠️ Common mistake: Confusing f(g(x)) with g(f(x)). Composition is not commutative -- the order matters. f(g(x)) applies g FIRST, then f. Always work from the inside out.\n\n"
        "💡 Tip: To find the vertex x-coordinate from standard form ax^2 + bx + c, use x = -b/(2a). This works faster than completing the square. Once you have the x-coordinate, substitute back into the equation to get the y-coordinate (the max or min value)."
    ),
    (
        7,
        "**Exponents, Radicals & Exponential Models** cover a wide range of SAT Advanced Math questions. Understanding the rules cold lets you simplify complex expressions quickly and interpret real-world growth and decay models.\n\n"
        "**Exponent rules -- the essential six:**\n"
        "- **Product rule:** x^m * x^n = x^(m+n). Same base, multiply -> add exponents. Example: 2^3 * 2^4 = 2^7 = 128.\n"
        "- **Quotient rule:** x^m / x^n = x^(m-n). Same base, divide -> subtract exponents. Example: x^5 / x^2 = x^3.\n"
        "- **Power rule:** (x^m)^n = x^(m*n). Power raised to a power -> multiply exponents. Example: (x^3)^2 = x^6.\n"
        "- **Zero exponent:** x^0 = 1 for any nonzero x. Example: 7^0 = 1.\n"
        "- **Negative exponent:** x^(-n) = 1/x^n. Negative exponent means 'flip to denominator.' Example: 2^(-3) = 1/8.\n"
        "- **Power of a product/quotient:** (xy)^n = x^n * y^n; (x/y)^n = x^n / y^n.\n\n"
        "**Rational exponents** bridge exponents and radicals:\n"
        "- x^(1/n) = the nth root of x. So x^(1/2) = sqrt(x) and x^(1/3) = cube_root(x).\n"
        "- x^(m/n) = the nth root of x^m, or equivalently (the nth root of x)^m.\n"
        "- Example: 8^(2/3) = (cube_root(8))^2 = 2^2 = 4.\n"
        "- Conversion: sqrt(x^3) = x^(3/2); cube_root(x^5) = x^(5/3).\n\n"
        "**Exponential functions** have the form f(x) = a * b^x:\n"
        "- **a** is the **initial value** (the output when x = 0, since b^0 = 1).\n"
        "- **b** is the **growth or decay factor**.\n"
        "- If b > 1, the function models **exponential growth**. A population doubling each year: P(t) = 500 * 2^t.\n"
        "- If 0 < b < 1, the function models **exponential decay**. A substance losing 20% per year: A(t) = 1000 * 0.80^t.\n"
        "- For a percent growth rate r: b = 1 + r. For 15% annual growth: b = 1.15.\n"
        "- For a percent decay rate r: b = 1 - r. For 10% annual decay: b = 0.90.\n\n"
        "**Exponential vs. linear growth:**\n"
        "- **Linear** growth adds a constant amount each period: f(x) = 3x + 5 adds 3 each time x increases by 1.\n"
        "- **Exponential** growth multiplies by a constant factor each period: f(x) = 5 * 2^x doubles each time x increases by 1.\n"
        "- Exponential growth eventually far outpaces linear growth, no matter how large the linear rate is.\n\n"
        "**Worked Example 1 (exponent rules):** Simplify (2x^3 * y^2)^3 / (4x^2 * y^3).\n"
        "- Numerator: 2^3 * x^9 * y^6 = 8x^9 y^6.\n"
        "- Divide: 8/4 = 2; x^(9-2) = x^7; y^(6-3) = y^3.\n"
        "- Simplified: 2x^7 y^3.\n\n"
        "**Worked Example 2 (real-world exponential):** A city has a population of 50,000 that grows at 4% per year. What will the population be after 3 years?\n"
        "- b = 1.04; P(3) = 50,000 * 1.04^3 = 50,000 * 1.1249 ≈ **56,245**.\n"
        "- Note: compound growth (4% three times) is NOT the same as a flat 12% increase (50,000 * 1.12 = 56,000). Compounding adds about 245 extra people.\n\n"
        "⚠️ Common mistake: Treating exponential expressions linearly. 2^(x+3) does not equal 2^x + 2^3. Use the product rule: 2^(x+3) = 2^x * 2^3 = 8 * 2^x.\n\n"
        "💡 Tip: When identifying whether a table shows linear or exponential growth, check whether consecutive y-values differ by a constant amount (linear -- addition) or a constant ratio (exponential -- multiplication). Divide consecutive terms; if the ratio is always the same, the model is exponential."
    ),
    (
        8,
        "**Geometry & Trigonometry** make up approximately 15% of SAT Math. The good news: the SAT provides a reference sheet with many key formulas, but you should know the common ones cold to save time.\n\n"
        "**Essential area and volume formulas:**\n"
        "- Area of a triangle: A = (1/2) * b * h (base times height divided by 2).\n"
        "- Area of a circle: A = pi * r^2.\n"
        "- Circumference: C = 2 * pi * r.\n"
        "- Volume of a cylinder: V = pi * r^2 * h.\n"
        "- Volume of a sphere: V = (4/3) * pi * r^3.\n"
        "- Volume of a rectangular prism: V = l * w * h.\n\n"
        "**Pythagorean theorem:** In any right triangle with legs a and b and hypotenuse c: a^2 + b^2 = c^2. The hypotenuse is always the side opposite the right angle and is always the longest side.\n\n"
        "**Special right triangles** (memorize these -- they appear constantly):\n"
        "- **30-60-90:** Sides are in ratio x : x*sqrt(3) : 2x. If the short leg is 5, the long leg is 5*sqrt(3) and the hypotenuse is 10.\n"
        "- **45-45-90:** Sides are in ratio x : x : x*sqrt(2). If the legs are 6, the hypotenuse is 6*sqrt(2).\n"
        "Common Pythagorean triples to memorize: 3-4-5, 5-12-13, 8-15-17.\n\n"
        "**Similar triangles:** If two triangles are similar, corresponding angles are equal and corresponding sides are proportional. The ratio of their areas equals the square of the ratio of their sides.\n"
        "- If triangle 1 has sides in ratio 2:3 to triangle 2, the area ratio is 4:9.\n\n"
        "**Trigonometry -- SOH-CAH-TOA:** For a right triangle with an angle A:\n"
        "- sin(A) = opposite / hypotenuse\n"
        "- cos(A) = adjacent / hypotenuse\n"
        "- tan(A) = opposite / adjacent\n\n"
        "To find a missing side: identify which trig function connects the known side and the unknown side, write the equation, and solve.\n"
        "Example: Angle A = 30 degrees, hypotenuse = 10. Find the opposite side.\n"
        "sin(30) = opposite/10 -> 0.5 = opposite/10 -> opposite = 5.\n\n"
        "**Complementary angle trig identity:** For any angle x, sin(x) = cos(90 - x). This appears on the SAT in the form 'sin(35) = cos(?)' -> cos(55). The two acute angles in a right triangle are complementary, so the sine of one equals the cosine of the other.\n\n"
        "**Coordinate geometry:**\n"
        "- **Distance formula:** d = sqrt((x2-x1)^2 + (y2-y1)^2) -- this is the Pythagorean theorem applied to coordinates.\n"
        "- **Midpoint formula:** midpoint = ((x1+x2)/2, (y1+y2)/2).\n"
        "- **Equation of a circle:** (x - h)^2 + (y - k)^2 = r^2, where (h, k) is the center and r is the radius.\n\n"
        "**Worked Example 1 (Pythagorean theorem):** A ladder 13 feet long leans against a wall. The base is 5 feet from the wall. How high up the wall does the ladder reach?\n"
        "- a^2 + 5^2 = 13^2 -> a^2 + 25 = 169 -> a^2 = 144 -> a = **12 feet**.\n\n"
        "**Worked Example 2 (trig and similarity):** Two similar triangles have a side ratio of 3:5. The area of the smaller triangle is 27 sq cm. What is the area of the larger?\n"
        "- Area ratio = (3/5)^2 = 9/25. So 27/area = 9/25 -> area = 27 * 25/9 = **75 sq cm**.\n\n"
        "⚠️ Common mistake: Applying the Pythagorean theorem to non-right triangles. Always confirm a right angle is present (look for the square symbol in the diagram or the word 'right' in the problem) before using a^2 + b^2 = c^2.\n\n"
        "💡 Tip: Before any geometry problem, label what you know directly on the diagram. Write in angle values, side lengths, and marks for equal sides. A labeled diagram almost always reveals the next step immediately."
    ),
    (
        9,
        "**SAT Math Strategy: Backsolve & Plug In** -- knowing the math is necessary, but knowing HOW to take the test is what separates good scores from great ones. This lesson covers the Digital SAT format, two powerful shortcuts, and the five most common SAT traps.\n\n"
        "**The Digital SAT Math format:**\n"
        "- Two modules, 22 questions each, 35 minutes per module -- 44 total math questions in 70 minutes.\n"
        "- A calculator is allowed for BOTH modules (the 'no-calculator section' no longer exists on the Digital SAT).\n"
        "- Most questions are **multiple choice** (4 options); some are **grid-in (student-produced response)** where you type your own answer. Grid-in answers can be fractions or decimals but are never negative.\n"
        "- The second module adapts: if you performed well on module 1, module 2 is harder; if not, it is easier.\n\n"
        "**What's on the reference sheet (you don't need to memorize these):**\n"
        "Area formulas for circles, rectangles, and triangles; special right triangle ratios; volume formulas for cones, cylinders, spheres, and pyramids; the number of degrees in a circle and a triangle.\n\n"
        "**What's NOT on the reference sheet (you must memorize these):**\n"
        "Quadratic formula, slope formula, distance and midpoint formulas, trig ratios (SOH-CAH-TOA), exponent rules, percent change formula, properties of parallel lines.\n\n"
        "**Strategy 1 -- Plugging In:** When a question has variables in both the question stem AND the answer choices, assign a simple number to the variable and compute.\n"
        "- Pick a number that is easy to work with (2, 3, 5, or 10 are often good choices). Avoid 0 and 1 -- they can make multiple answer choices produce the same result.\n"
        "- Compute the target value using your number.\n"
        "- Substitute the same number into each answer choice. The one that matches your target is correct.\n"
        "- Example: 'If n is a positive integer, which expression is always even?' Plug in n = 3 (odd) and n = 2 (even); check each choice.\n\n"
        "**Strategy 2 -- Backsolving:** When a question asks for a specific numerical value and the answer choices ARE numbers, test the answer choices directly in the problem.\n"
        "- Start with a middle value (choice B or C), since SAT answers are often listed in order.\n"
        "- Substitute into the original equation or condition. If the result is too large, try a smaller choice; if too small, try a larger one.\n"
        "- Example: '3x - 4 = 2x + 1, what is x?' Try x = 5: left = 11, right = 11. Match! No algebra needed.\n\n"
        "**Strategy 3 -- Process of elimination:** Use partial knowledge to eliminate wrong answers.\n"
        "- Eliminate by **sign:** if the answer must be positive, cross out negatives.\n"
        "- Eliminate by **magnitude:** if the answer should be between 1 and 10, cross out 100 or -3.\n"
        "- Eliminate by **units:** if the answer should be in square feet, eliminate choices in feet.\n"
        "Even eliminating one or two choices improves your odds significantly on a guess.\n\n"
        "**Time management:**\n"
        "- Flag and return: if you're stuck after 90 seconds, mark the question and move on. Easy questions at the end of the section are worth the same points as hard ones at the beginning.\n"
        "- Don't spend more than 90 seconds on any single question during your first pass.\n"
        "- On grid-in questions, double-check that your answer fits the format (fractions, mixed numbers, and negative signs have specific rules).\n\n"
        "**The 5 most common SAT math traps:**\n"
        "- **Trap 1 -- Solving for the wrong variable:** The problem asks for 2x + 1 but you found x = 4 and wrote 4. Always re-read the final question line before selecting your answer.\n"
        "- **Trap 2 -- Ignoring units:** Mixing minutes and hours, or inches and feet, in a rate or measurement problem. Convert everything to the same unit before setting up the equation.\n"
        "- **Trap 3 -- Assuming diagrams are to scale:** SAT figures are explicitly labeled 'Note: Figure not drawn to scale.' Never measure with your eye -- use the given values.\n"
        "- **Trap 4 -- Missing a negative sign:** Especially when distributing -- -(x - 3) is -x + 3, not -x - 3. Also common when squaring a negative: (-3)^2 = 9, not -9.\n"
        "- **Trap 5 -- Forgetting the second answer in a quadratic:** x^2 = 25 has two solutions: x = 5 AND x = -5. The SAT often lists both as separate answer choices to trap students who only find one.\n\n"
        "**Worked Strategy Example 1 (Backsolving):** If 4(x - 2) = 2x + 6, what is x?\n"
        "- Try x = 7 (choice C): left = 4(5) = 20; right = 14 + 6 = 20. Match!\n"
        "- Answer: x = 7. No algebra required.\n\n"
        "**Worked Strategy Example 2 (Plugging In):** If k is a positive integer, which of the following is always odd?\n"
        "- (A) 2k (B) k + 1 (C) 2k + 1 (D) k^2\n"
        "- Plug in k = 2 (even): (A) 4 even; (B) 3 odd; (C) 5 odd; (D) 4 even. Eliminates A and D.\n"
        "- Plug in k = 3 (odd): (B) 4 even -- eliminates B. (C) 7 odd -- still works.\n"
        "- Answer: **(C) 2k + 1** -- always odd because 2k is always even, and even + 1 is always odd.\n\n"
        "⚠️ Common mistake: Using 0 or 1 when plugging in numbers. These special values often make multiple answer choices produce the same result, making it impossible to tell which is correct. Choose a number like 2, 3, or 5 instead.\n\n"
        "💡 Tip: Before you submit any answer, re-read the final sentence of the question. SAT problems frequently ask for x + 3, the value of y, or the total cost -- not the variable you solved for. This one habit, applied consistently, can recover 2-4 points per test."
    ),
]


class Command(BaseCommand):
    help = "Enrich lesson content for SAT Math: Complete Course & Test Prep"

    def handle(self, *args, **options):
        for order, content in LESSONS:
            rows = Lesson.objects.filter(
                course__slug="sat-math-complete-course", order=order
            ).update(content=content)
            self.stdout.write(f"  Lesson {order}: {rows} row(s) updated")
        self.stdout.write(
            self.style.SUCCESS("Done enriching SAT Math: Complete Course lessons.")
        )
