"""
Enrich lesson content for the 'SAT Math: Geometry & Trigonometry' course.

Run:
    python manage.py enrich_sat_math_geometry
"""
from django.core.management.base import BaseCommand
from courses.models import Lesson


LESSONS = [
    (
        1,
        "**Lines, Angles, and Triangles** form the foundation of SAT geometry. Mastering the relationships between angles is the single fastest way to gain points on this domain.\n\n"
        "**Angle types:** An **acute angle** measures less than 90 degrees. A **right angle** measures exactly 90 degrees (marked with a small square in diagrams). An **obtuse angle** measures between 90 and 180 degrees. A **straight angle** measures exactly 180 degrees and forms a straight line. Two angles are **complementary** when their measures sum to 90 degrees; they are **supplementary** when their measures sum to 180 degrees.\n\n"
        "**Angle relationships at intersecting lines:** When two lines intersect, they create two pairs of **vertical angles** -- the angles directly across from each other. Vertical angles are always equal. For example, if one angle is 47 degrees, the vertical angle is also 47 degrees. The two adjacent angles at the same intersection are supplementary, summing to 180 degrees. All four angles around a single point always sum to 360 degrees.\n\n"
        "**Parallel lines cut by a transversal:** When a transversal crosses two parallel lines, it creates eight angles. Three key relationships appear on every SAT:\n"
        "- **Corresponding angles** occupy the same position at each intersection (e.g., both in the upper-left corner). They are equal.\n"
        "- **Alternate interior angles** lie between the parallel lines on opposite sides of the transversal. They are equal.\n"
        "- **Co-interior (same-side interior) angles** lie between the parallel lines on the same side of the transversal. They are supplementary -- they add to 180 degrees.\n\n"
        "**Triangle angle-sum theorem:** The three interior angles of any triangle always sum to exactly 180 degrees. This is the most-used geometry fact on the SAT. If two angles are known, the third is simply 180 minus their sum.\n\n"
        "**Exterior angle theorem:** An exterior angle of a triangle equals the sum of the two non-adjacent (remote) interior angles. If a triangle has angles 40, 65, and 75 degrees, the exterior angle at the 75-degree vertex equals 40 + 65 = 105 degrees. This shortcut is faster than computing the interior angle first and then subtracting from 180.\n\n"
        "**Similar triangles:** Two triangles are **similar** when their corresponding angles are equal and their corresponding sides are proportional. The three similarity shortcuts are:\n"
        "- **AA (Angle-Angle):** If two pairs of corresponding angles are equal, the triangles are similar.\n"
        "- **SAS (Side-Angle-Side):** Two pairs of sides proportional with the included angles equal.\n"
        "- **SSS (Side-Side-Side):** All three pairs of sides proportional.\n"
        "If the similarity ratio is 1:k, side lengths scale by k, areas scale by k squared, and perimeters scale by k.\n\n"
        "**Worked Example 1:** Two parallel lines are cut by a transversal. One angle measures (3x + 10) degrees and its alternate interior angle measures (5x - 30) degrees. Find x.\n"
        "- Alternate interior angles are equal: 3x + 10 = 5x - 30.\n"
        "- Subtract 3x: 10 = 2x - 30. Add 30: 40 = 2x, so x = 20.\n"
        "- Check: 3(20) + 10 = 70 and 5(20) - 30 = 70. Confirmed.\n\n"
        "**Worked Example 2:** In triangle ABC, angle A = 52 degrees and angle B = 74 degrees. An exterior angle is drawn at vertex C. Find the exterior angle.\n"
        "- Exterior angle = sum of remote interior angles = 52 + 74 = 126 degrees.\n\n"
        "**Worked Example 3:** Triangle PQR is similar to triangle STU with ratio 3:5. Side PQ = 12. Find side ST.\n"
        "- 12/ST = 3/5. Cross-multiply: 3 * ST = 60, so ST = 20.\n\n"
        "**Common traps:**\n"
        "- Confusing **complementary** (sum = 90) with **supplementary** (sum = 180). A trick: C comes before S in the alphabet, and 90 comes before 180.\n"
        "- Forgetting the exterior angle theorem and instead computing the interior angle first, wasting time.\n"
        "- In similar triangles, squaring the side ratio for area but forgetting to square it (using the ratio directly for area).\n\n"
        "**Tip:** When a diagram shows parallel lines, immediately label every angle you know and mark equal pairs with matching tick marks. One labeled angle typically unlocks all eight angles in the figure, turning a complex-looking problem into straightforward substitution."
    ),
    (
        2,
        "**Circles** appear on nearly every SAT math section. The good news is that every circle question flows from a small set of formulas and theorems -- learn them cold and circle problems become reliably fast points.\n\n"
        "**Core definitions:** The **radius** (r) is the distance from the center to any point on the circle. The **diameter** (d) is twice the radius: d = 2r. A **chord** is any line segment connecting two points on the circle. The **diameter** is the longest possible chord.\n\n"
        "**Fundamental formulas:**\n"
        "- **Circumference:** C = 2*pi*r = pi*d (the total distance around the circle)\n"
        "- **Area:** A = pi*r^2 (always use the radius, never the diameter)\n\n"
        "**Arcs and sectors:** An **arc** is a portion of a circle's circumference. A **sector** is the pie-slice region bounded by two radii and an arc. Both are calculated as a fraction of the full circle based on the **central angle** (the angle at the center):\n"
        "- **Arc length** = (central angle / 360) * 2*pi*r\n"
        "- **Sector area** = (central angle / 360) * pi*r^2\n"
        "Think of these as: (fraction of the full circle) * (full circumference or area).\n\n"
        "**Central angle and arc measure:** A central angle and its intercepted arc have the same degree measure. A central angle of 90 degrees intercepts a 90-degree arc, which is one-quarter of the circle.\n\n"
        "**Inscribed angle theorem:** An **inscribed angle** has its vertex on the circle and its two sides as chords. An inscribed angle equals exactly half the central angle that intercepts the same arc. If the central angle is 100 degrees, the inscribed angle is 50 degrees. A special case: any inscribed angle that intercepts a semicircle (180-degree arc) is always 90 degrees -- this is **Thales' theorem**.\n\n"
        "**Tangent lines:** A line is **tangent** to a circle if it touches the circle at exactly one point. The key property: a tangent line is always perpendicular to the radius drawn to the point of tangency. This creates a right angle, making the Pythagorean theorem usable whenever a tangent appears.\n\n"
        "**Worked Example 1 -- Arc length:** A circle has radius 9. A sector has a central angle of 80 degrees. Find the arc length.\n"
        "- Arc length = (80/360) * 2*pi*9 = (2/9) * 18*pi = 4*pi inches.\n\n"
        "**Worked Example 2 -- Sector area:** A circle has radius 12 cm. The central angle is 150 degrees. Find the sector area.\n"
        "- Sector area = (150/360) * pi*12^2 = (5/12) * 144*pi = 60*pi sq cm.\n\n"
        "**Worked Example 3 -- Missing central angle:** A sector has area 20*pi in a circle with radius 10. Find the central angle.\n"
        "- 20*pi = (theta/360) * pi*100. Divide both sides by pi: 20 = (theta/360)*100.\n"
        "- theta/360 = 20/100 = 1/5. So theta = 360/5 = 72 degrees.\n\n"
        "**Common traps:**\n"
        "- Using the **diameter instead of the radius** in A = pi*r^2. Always halve the diameter before squaring.\n"
        "- Confusing the **inscribed angle** with the **central angle**: the inscribed angle is half the central angle, not equal to it.\n"
        "- Forgetting to take the square root when asked for the radius after being given the area.\n\n"
        "**Tip:** On any arc or sector problem, write the fraction (central angle / 360) first and simplify it before multiplying. This prevents arithmetic errors and keeps numbers manageable."
    ),
    (
        3,
        "**Area and Volume** problems test your ability to select the right formula, substitute correctly, and handle composite shapes and scaling. The SAT formula sheet provides most formulas -- but knowing them cold is still faster.\n\n"
        "**Area formulas (2D):**\n"
        "- **Rectangle:** A = length * width\n"
        "- **Triangle:** A = (1/2) * base * height (height is always perpendicular to the base, not the slant side)\n"
        "- **Parallelogram:** A = base * height (again, perpendicular height)\n"
        "- **Trapezoid:** A = (1/2) * (base1 + base2) * height (average the two parallel bases, then multiply by height)\n"
        "- **Circle:** A = pi*r^2\n\n"
        "**Volume formulas (3D):**\n"
        "- **Rectangular prism (box):** V = length * width * height\n"
        "- **Cylinder:** V = pi*r^2*h\n"
        "- **Cone:** V = (1/3)*pi*r^2*h (exactly one-third of the cylinder with the same base and height)\n"
        "- **Sphere:** V = (4/3)*pi*r^3\n"
        "- **Pyramid:** V = (1/3) * base area * height\n\n"
        "**Surface area:** Surface area measures the total outer skin of a 3D solid.\n"
        "- **Rectangular prism:** SA = 2(lw + lh + wh) -- sum of areas of all 6 faces\n"
        "- **Cylinder:** SA = 2*pi*r^2 + 2*pi*r*h (two circular ends plus the lateral rectangle unrolled)\n"
        "- **Lateral area** refers only to the curved or side surfaces, excluding the bases.\n\n"
        "**Net-based thinking:** When visualizing surface area, imagine cutting the solid along edges and unfolding it flat. The cylinder's lateral surface unfolds into a rectangle with width 2*pi*r (the circumference) and height h.\n\n"
        "**Scaling -- the most tested concept in this area:**\n"
        "- If all linear dimensions are multiplied by a factor k, **area scales by k^2** and **volume scales by k^3**.\n"
        "- Example: doubling every dimension of a box (k = 2) multiplies the volume by 2^3 = 8.\n"
        "- This applies to similar solids: if radius doubles, cylinder volume becomes 4 times larger (k^2 affects r^2 inside pi*r^2*h, and k also scales h, giving k^3 overall).\n\n"
        "**Worked Example 1 -- Composite volume:** A cylinder has radius 3 ft and height 10 ft. A cone sits on top with the same base radius and height 4 ft. Find the combined volume.\n"
        "- Cylinder: pi*(3^2)*10 = 90*pi.\n"
        "- Cone: (1/3)*pi*(3^2)*4 = 12*pi.\n"
        "- Total: 102*pi cubic feet.\n\n"
        "**Worked Example 2 -- Trapezoid area:** A trapezoid has parallel bases 8 cm and 14 cm with perpendicular height 5 cm. Find the area.\n"
        "- A = (1/2)*(8+14)*5 = (1/2)*22*5 = 55 sq cm.\n\n"
        "**Worked Example 3 -- Scaling:** A model car is built at a 1:20 scale. If the real car has a tank volume of 60 liters, what is the volume of the model's tank?\n"
        "- Volume scales by k^3. k = 1/20, so k^3 = 1/8000.\n"
        "- Model tank = 60 / 8000 = 0.0075 liters.\n\n"
        "**Common traps:**\n"
        "- Using **slant height** instead of **perpendicular height** in triangle, parallelogram, cone, and pyramid formulas.\n"
        "- Confusing **surface area** and **volume** -- read the question carefully.\n"
        "- Applying the **area scale factor (k^2)** when the problem asks about **volume (k^3)**.\n\n"
        "**Tip:** For composite figures, always decompose first and list sub-problems. Write 'outer shape minus inner shape' or 'shape A plus shape B' before calculating. This prevents accidentally using a wrong formula for the whole figure."
    ),
    (
        4,
        "**The Coordinate Plane** connects algebra and geometry. SAT questions in this area test distance, midpoints, slope, and circle equations -- all of which flow from a few key formulas.\n\n"
        "[[figure:coordinate_quadrants|The four quadrants and the signs of x and y in each]]\n\n"
        "**The four quadrants:** The x-axis and y-axis divide the plane into four quadrants. In Quadrant I, both x and y are positive. In Quadrant II, x is negative and y is positive. In Quadrant III, both are negative. In Quadrant IV, x is positive and y is negative. Knowing these sign patterns helps you check that answers are in a sensible location.\n\n"
        "**Distance formula:** The distance between (x1, y1) and (x2, y2) is:\n"
        "- d = sqrt((x2 - x1)^2 + (y2 - y1)^2)\n"
        "This is just the Pythagorean theorem in disguise: the horizontal difference is one leg, the vertical difference is the other leg, and d is the hypotenuse. On a grid, count the horizontal and vertical gaps first and apply a^2 + b^2 = c^2 -- it is faster than plugging four coordinates into the formula.\n\n"
        "**Midpoint formula:** The midpoint M of a segment from (x1, y1) to (x2, y2) is:\n"
        "- M = ((x1 + x2) / 2, (y1 + y2) / 2)\n"
        "Average the x-coordinates and average the y-coordinates separately.\n\n"
        "**Slope from two points:** The slope m of the line through (x1, y1) and (x2, y2) is:\n"
        "- m = (y2 - y1) / (x2 - x1) = rise / run\n"
        "- A positive slope rises left to right; negative slope falls left to right.\n"
        "- A horizontal line has slope 0. A vertical line has undefined slope.\n"
        "- **Parallel lines** share the same slope. **Perpendicular lines** have slopes that are negative reciprocals: m1 * m2 = -1.\n\n"
        "**Equation of a circle:** A circle with center (h, k) and radius r in the coordinate plane satisfies:\n"
        "- (x - h)^2 + (y - k)^2 = r^2\n"
        "To read the center, note that the signs inside the parentheses are opposite the center coordinates: (x + 3)^2 means h = -3.\n\n"
        "**Completing the square:** When the circle equation is in expanded form (x^2 + y^2 + bx + cy + d = 0), rewrite it in standard form by completing the square for both x and y. Step-by-step: move the constant to the right, group x and y terms, add (b/2)^2 and (c/2)^2 to both sides, then factor.\n\n"
        "**Worked Example 1 -- Distance:** Find the distance between (1, 2) and (7, 10).\n"
        "- d = sqrt((7-1)^2 + (10-2)^2) = sqrt(36 + 64) = sqrt(100) = 10. (Recognizes 6-8-10 triple.)\n\n"
        "**Worked Example 2 -- Circle center and radius:** Find the center and radius of x^2 + y^2 - 6x + 4y - 12 = 0.\n"
        "- Group: (x^2 - 6x) + (y^2 + 4y) = 12.\n"
        "- Complete: (x-3)^2 - 9 + (y+2)^2 - 4 = 12.\n"
        "- Simplify: (x-3)^2 + (y+2)^2 = 25. Center: (3, -2). Radius: 5.\n\n"
        "**Worked Example 3 -- Perpendicular slope:** Line A passes through (2, 1) and (6, 9). Find the slope of a perpendicular line.\n"
        "- Slope of A: m = (9-1)/(6-2) = 8/4 = 2.\n"
        "- Perpendicular slope: -1/2.\n\n"
        "**Common traps:**\n"
        "- Reading (x + 3)^2 as center x = +3 instead of x = -3.\n"
        "- Forgetting to take the square root of r^2 when reporting the radius.\n"
        "- Subtracting coordinates in the wrong order for slope; always keep the same point as 'point 2' in both numerator and denominator.\n\n"
        "**Tip:** For distance problems on a labeled grid, count grid squares for the horizontal leg and vertical leg, then apply the Pythagorean theorem mentally. This is almost always faster than using the distance formula with raw coordinates."
    ),
    (
        5,
        "**Right Triangles and the Pythagorean Theorem** appear in some form on virtually every SAT math section -- and the tools here extend far beyond basic triangles into 3D geometry, distance problems, and coordinate geometry.\n\n"
        "[[figure:pythagorean_triangle|Right triangle with legs a, b and hypotenuse c labeled]]\n\n"
        "**The Pythagorean theorem:** In any right triangle with legs a and b and hypotenuse c (the side opposite the right angle):\n"
        "- a^2 + b^2 = c^2\n"
        "Use it to find any missing side when the other two are known. If a = 6 and b = 8, then c^2 = 36 + 64 = 100, so c = 10.\n\n"
        "**Pythagorean triples:** These are sets of three positive integers that satisfy a^2 + b^2 = c^2. Memorizing them lets you skip all arithmetic:\n"
        "- 3-4-5 and its multiples: 6-8-10, 9-12-15, 12-16-20\n"
        "- 5-12-13\n"
        "- 8-15-17\n"
        "- 7-24-25\n"
        "When you see two sides that fit a triple, write the third side immediately without calculating.\n\n"
        "**45-45-90 triangle:** An isosceles right triangle. If each leg has length x, then:\n"
        "- Legs: x and x\n"
        "- Hypotenuse: x*sqrt(2)\n"
        "To go from hypotenuse to leg, divide by sqrt(2) (equivalently, multiply by sqrt(2)/2). A square cut along its diagonal creates two 45-45-90 triangles.\n\n"
        "**30-60-90 triangle:** Half of an equilateral triangle. If the shortest leg (opposite 30 degrees) has length x, then:\n"
        "- Shortest leg (opposite 30): x\n"
        "- Longer leg (opposite 60): x*sqrt(3)\n"
        "- Hypotenuse (opposite 90): 2x\n"
        "The SAT formula sheet provides these ratios. Internalize the pattern: each side is either doubled or multiplied by sqrt(3) as you move from the 30-degree angle outward.\n\n"
        "**Applications:**\n"
        "- **Diagonal of a rectangle:** A rectangle with sides l and w has diagonal d = sqrt(l^2 + w^2).\n"
        "- **Height of an equilateral triangle:** For an equilateral triangle with side s, the height is (s*sqrt(3))/2 (drop an altitude to split it into two 30-60-90 triangles).\n"
        "- **3D diagonal of a box:** For a box with dimensions l, w, h, the space diagonal is sqrt(l^2 + w^2 + h^2). Apply the Pythagorean theorem twice (or recognize it as one extended formula).\n\n"
        "**Worked Example 1 -- Pythagorean triple:** A right triangle has legs 9 and 40. Find the hypotenuse.\n"
        "- c^2 = 81 + 1600 = 1681. c = 41. (9-40-41 is a Pythagorean triple.)\n\n"
        "**Worked Example 2 -- 30-60-90:** In a 30-60-90 triangle, the hypotenuse is 10. Find both legs.\n"
        "- Hypotenuse = 2x = 10, so x = 5. Short leg = 5; long leg = 5*sqrt(3).\n\n"
        "**Worked Example 3 -- 3D diagonal:** A box is 3 ft long, 4 ft wide, and 12 ft tall. Find the space diagonal.\n"
        "- Diagonal = sqrt(3^2 + 4^2 + 12^2) = sqrt(9 + 16 + 144) = sqrt(169) = 13 ft.\n\n"
        "**Common traps:**\n"
        "- In a 30-60-90 triangle, assigning the longer leg to the 30-degree angle. The longer leg is always opposite the larger angle (60 degrees).\n"
        "- In a 45-45-90 triangle, thinking the hypotenuse equals x instead of x*sqrt(2).\n"
        "- Applying the Pythagorean theorem with the hypotenuse as a leg -- always confirm which side is opposite the right angle.\n\n"
        "**Tip:** Before computing, check if the two given sides form part of a known triple. If you see legs 5 and 12, write hypotenuse = 13 immediately. This habit saves a significant amount of time across the full test."
    ),
    (
        6,
        "**Trigonometric Ratios** let you find missing sides and angles in right triangles using three core ratios. The SAT tests these ratios directly, through the complementary identity, and by converting between degrees and radians.\n\n"
        "**SOH-CAH-TOA:** For an acute angle theta in a right triangle:\n"
        "- **sin(theta) = Opposite / Hypotenuse**\n"
        "- **cos(theta) = Adjacent / Hypotenuse**\n"
        "- **tan(theta) = Opposite / Adjacent**\n"
        "The mnemonic SOH-CAH-TOA encodes all three ratios. Always label sides relative to the angle in question: the **opposite** side is across from the angle; the **adjacent** side touches the angle but is not the hypotenuse.\n\n"
        "**Exact values table -- memorize these:**\n"
        "- sin(0) = 0, cos(0) = 1, tan(0) = 0\n"
        "- sin(30) = 1/2, cos(30) = sqrt(3)/2, tan(30) = sqrt(3)/3\n"
        "- sin(45) = sqrt(2)/2, cos(45) = sqrt(2)/2, tan(45) = 1\n"
        "- sin(60) = sqrt(3)/2, cos(60) = 1/2, tan(60) = sqrt(3)\n"
        "- sin(90) = 1, cos(90) = 0, tan(90) = undefined\n\n"
        "**Complementary angle relationship:** Because the two acute angles in a right triangle sum to 90 degrees, their sine and cosine are swapped:\n"
        "- sin(x) = cos(90 - x) and cos(x) = sin(90 - x)\n"
        "This appears on the SAT in the form: if sin(x) = cos(32), then x + 32 = 90, so x = 58. No calculator needed -- just recognize the identity.\n\n"
        "**Finding missing sides:** Set up the appropriate trig ratio, then solve by cross-multiplication.\n"
        "Example: A ladder 12 ft long leans against a wall at 60 degrees from the ground. How high does it reach?\n"
        "- sin(60) = height / 12. Height = 12 * sin(60) = 12 * (sqrt(3)/2) = 6*sqrt(3) ft.\n\n"
        "**Finding missing angles:** Use inverse trig functions.\n"
        "- arcsin, arccos, arctan (written sin^-1, cos^-1, tan^-1 on calculators)\n"
        "- If tan(theta) = 4/3, then theta = arctan(4/3). Use the calculator on non-standard angles.\n\n"
        "**Radians vs. degrees:** A full circle equals 360 degrees or 2*pi radians. The conversion formulas are:\n"
        "- Degrees to radians: multiply by pi/180\n"
        "- Radians to degrees: multiply by 180/pi\n"
        "- Key conversions: 30 = pi/6, 45 = pi/4, 60 = pi/3, 90 = pi/2, 180 = pi, 270 = 3*pi/2, 360 = 2*pi\n\n"
        "**Pythagorean identity:** sin^2(theta) + cos^2(theta) = 1. The SAT occasionally asks you to simplify expressions using this identity.\n\n"
        "**Worked Example 1 -- Finding sin and cos:** In right triangle ABC, angle C = 90, AB = 13, BC = 5. Find sin(A) and cos(A).\n"
        "- AC = sqrt(13^2 - 5^2) = sqrt(144) = 12.\n"
        "- sin(A) = opposite/hypotenuse = BC/AB = 5/13.\n"
        "- cos(A) = adjacent/hypotenuse = AC/AB = 12/13.\n\n"
        "**Worked Example 2 -- Complementary identity:** If cos(x) = sin(47), find x.\n"
        "- cos(x) = sin(47) = cos(90 - 47) = cos(43). So x = 43 degrees.\n\n"
        "**Worked Example 3 -- Radian conversion:** Convert 270 degrees to radians.\n"
        "- 270 * (pi/180) = 270/180 * pi = 3/2 * pi = 3*pi/2 radians.\n\n"
        "**Common traps:**\n"
        "- Swapping **opposite** and **adjacent**. Relabel the triangle for each new angle before writing the ratio.\n"
        "- Using degree mode on the calculator when the problem is in radians, or vice versa.\n"
        "- Forgetting that tan(90) is undefined (the adjacent side length is zero).\n\n"
        "**Tip:** If you cannot recall an exact trig value during the test, quickly sketch the relevant special triangle (30-60-90 or 45-45-90) using the ratios from the SAT formula sheet and read off the ratio directly. This takes about 10 seconds and is more reliable than guessing from memory."
    ),
    (
        7,
        "**SAT Geometry and Trigonometry Strategy** is about working smarter, not just harder. Knowing the content is necessary but not sufficient -- you also need a systematic approach for translating word problems into correct diagrams and solutions under timed pressure.\n\n"
        "**Using the SAT formula sheet:** The Digital SAT provides a reference sheet at the start of the math section. It includes:\n"
        "- Area formulas: triangle, circle\n"
        "- Volume and surface area: cylinder, cone, sphere, pyramid, rectangular prism\n"
        "- Special right triangles: 30-60-90 and 45-45-90 ratios\n"
        "- Circle: total degrees (360), semicircle (180)\n"
        "**Not on the sheet:** distance formula, midpoint formula, slope, trig ratios, arc length, sector area, the Pythagorean theorem. Know these from memory. Use the sheet freely -- there is no penalty for checking it, and doing so takes only a few seconds.\n\n"
        "**Strategy 1 -- Draw and label your own diagram:** When a question describes a geometric situation without a figure, sketch it immediately. Mark every given length and angle. Label the unknown with x and circle what the question actually asks for. Students who draw first consistently outperform students who try to hold the picture in their heads.\n\n"
        "**Strategy 2 -- Work backward from answer choices:** On multiple-choice geometry problems, plug answer choices back into the question. Start with a middle value when answers are ordered numerically (eliminates half the options on each try). This is especially effective for angle problems and side-length problems where setting up an equation takes longer than testing a value.\n\n"
        "**Strategy 3 -- Estimate with scale when diagrams are drawn to scale:** Many SAT figures are drawn to scale (the problem will say so, or will not include the 'not drawn to scale' note). Use the diagram to eliminate extreme answer choices. If the unknown angle looks close to 60 degrees, eliminate answers like 20 and 150 before solving.\n\n"
        "**When to use the Pythagorean theorem vs. trigonometry:**\n"
        "- Use the **Pythagorean theorem** when you know two sides and need the third -- no angle required.\n"
        "- Use **trigonometry** (SOH-CAH-TOA) when you know one side and one acute angle and need another side, OR when you know two sides and need an angle.\n"
        "- Use **special triangle ratios** (30-60-90, 45-45-90) as a shortcut when angles are 30, 45, or 60 -- faster than trig.\n\n"
        "**Common SAT geometry trap types:**\n"
        "- **Radius vs. diameter:** Halve the diameter before using any area or arc formula.\n"
        "- **Forgetting units:** If lengths are in centimeters, area is in cm^2 and volume is in cm^3. Mixing units (cm and m in the same problem) is a trap.\n"
        "- **Degrees vs. radians:** Identify which the question uses before computing. An answer in radians and an answer in degrees for the same angle look completely different numerically.\n"
        "- **Answering the wrong quantity:** The question might ask for 2x + 3 after you find x = 5. Always re-read the final question before bubbling in your answer.\n"
        "- **'Not drawn to scale':** If a diagram carries this warning, trust the numbers -- not the picture. Diagrams can be misleading by design.\n\n"
        "**Worked Example 1 -- Multi-step composite area:** A large square has side 10. A circle is inscribed inside it (touching all four sides). Find the shaded area between the square and circle.\n"
        "- Square area = 100. Circle radius = 5. Circle area = 25*pi.\n"
        "- Shaded area = 100 - 25*pi.\n\n"
        "**Worked Example 2 -- Working backward:** A question asks for the angle in a triangle and the answer choices are 30, 45, 60, and 75 degrees. You know two angles are equal and sum to 90 degrees. Testing 45: two equal angles of 45 sum to 90, leaving the third angle as 90. That satisfies the constraint. Answer: 45 degrees.\n\n"
        "**Worked Example 3 -- Pythagorean vs. trig:** A right triangle has hypotenuse 10 and one acute angle of 30 degrees. Find both legs.\n"
        "- Use special triangle: shorter leg = 10/2 = 5 (opposite 30). Longer leg = 5*sqrt(3) (opposite 60). Faster than using sin and cos individually.\n\n"
        "**Common traps (summary):**\n"
        "- Solving for x when the question asks for x + 5.\n"
        "- Using slant height where perpendicular height is required.\n"
        "- Mixing up inscribed angle and central angle (inscribed = half of central).\n\n"
        "**Tip:** Before submitting any geometry answer, do a 5-second sanity check: Is the answer a reasonable size given the figure? Does it have the right units? Did you answer what was asked? This habit catches a significant percentage of careless errors without requiring re-solving the problem."
    ),
]


class Command(BaseCommand):
    help = "Enrich lesson content for SAT Math: Geometry & Trigonometry"

    def handle(self, *args, **options):
        for order, content in LESSONS:
            rows = Lesson.objects.filter(
                course__slug="sat-math-geometry-trig", order=order
            ).update(content=content)
            self.stdout.write(f"  Lesson {order}: {rows} row(s) updated")
        self.stdout.write(
            self.style.SUCCESS(
                "Done enriching SAT Math: Geometry & Trigonometry lessons."
            )
        )
