"""
Enrich lesson content for 'SAT Full-Length Practice Test (Reading, Writing & Math)'.

Each of the 4 lessons receives a longer, richer content block (600-800 words)
written as a coach's pre-game briefing: comprehensive, motivating, and precise.

Run:
    python manage.py enrich_sat_full_practice
"""
from django.core.management.base import BaseCommand
from courses.models import Lesson


LESSONS = [
    (
        1,
        "**How the Full Digital SAT Works**\n\n"
        "Before you attempt a single question, understand the arena you are stepping into. "
        "The digital SAT is a precisely engineered two-hour-and-fourteen-minute exam divided "
        "into two major sections: **Reading & Writing** and **Math**. Every minute and every "
        "question has a purpose, and knowing the structure in advance turns an intimidating "
        "marathon into a manageable sprint with a clear map.\n\n"
        "**Section 1 -- Reading & Writing (64 minutes, 54 questions)**\n"
        "The Reading & Writing section runs first. It contains two back-to-back modules:\n"
        "- **Module 1:** approximately 27 questions in 32 minutes\n"
        "- **Module 2:** approximately 27 questions in 32 minutes\n\n"
        "Each question in both modules is paired with its own short passage -- usually one "
        "to three sentences for grammar questions and four to twelve sentences for reading "
        "questions. You never need outside knowledge; everything you need is on the screen.\n\n"
        "**Section 2 -- Math (70 minutes, 44 questions)**\n"
        "After a 10-minute break, Math begins. It also has two modules:\n"
        "- **Module 1:** 22 questions in 35 minutes\n"
        "- **Module 2:** 22 questions in 35 minutes\n\n"
        "Most questions are multiple choice. A smaller number are **grid-in (free response)** "
        "questions where you enter a numerical answer directly -- there are no choices to "
        "guess from. A College Board-approved calculator is permitted for the entire Math "
        "section. A reference sheet with basic geometry formulas appears on-screen during "
        "Math; use it. There is also a **5-minute break between the two Math modules**.\n\n"
        "**The Adaptive Engine -- How Difficulty Adjusts**\n"
        "The digital SAT uses a **multistage adaptive** design. After you complete Module 1 "
        "of each section, the testing software evaluates your performance and routes you to "
        "one of two versions of Module 2:\n"
        "- If you performed well on Module 1, Module 2 will be **harder** -- but questions "
        "in the harder module are worth more toward your final score.\n"
        "- If you performed less well on Module 1, Module 2 will be **easier** -- accessible "
        "questions, but with a ceiling on how high your total score can go.\n\n"
        "A critical point: **both modules count fully**. Skipping or rushing through Module 1 "
        "to save energy for Module 2 is a losing strategy. Lay a strong foundation in Module 1 "
        "and the adaptive engine will reward you.\n\n"
        "**Scoring: 400 to 1600**\n"
        "Your total SAT score is the sum of two section scores:\n"
        "- **Reading & Writing:** 200 to 800\n"
        "- **Math:** 200 to 800\n\n"
        "There is **no penalty for wrong answers**. A blank and a wrong answer cost you "
        "exactly the same thing: the point you did not earn. This means you should answer "
        "every single question, even if you have to guess. A strategic guess after eliminating "
        "two wrong choices gives you a 50% chance at a point you would otherwise guarantee losing.\n\n"
        "**Question Types at a Glance**\n"
        "Reading & Writing has four question domains: Craft & Structure, Information & Ideas, "
        "Standard English Conventions, and Expression of Ideas. Math has four: Algebra, "
        "Advanced Math, Problem-Solving & Data Analysis, and Geometry & Trigonometry. "
        "You will encounter these in shuffled order within each module -- the test does not "
        "group them by type.\n\n"
        "**Why Full-Length Practice Matters**\n"
        "Stamina is a skill. The real SAT asks you to sustain focus and accuracy for over two "
        "hours while transitioning from reading comprehension to grammar to algebra to geometry "
        "and back. Students who only practice individual question types often discover on test "
        "day that their pacing collapses in the second Math module. Full-length simulation -- "
        "timed, no phone, real break, real conditions -- trains your brain to hold performance "
        "through fatigue. Your practice score is a direct reflection of your practice habits.\n\n"
        "⚠️ Common mistake: treating Module 1 as a warm-up. Students who coast through early "
        "questions hoping to 'get going' in Module 2 lower their adaptive track and cap their "
        "final score. Module 1 sets the ceiling -- protect it.\n\n"
        "💡 Tip: Before this practice test begins, set a timer for 32 minutes per Reading & "
        "Writing module and 35 minutes per Math module. Close your phone completely. Treat the "
        "10-minute break as a real break -- eat a snack, hydrate, do not review questions. "
        "The closer your simulation matches real conditions, the more accurately your score "
        "predicts what you will achieve on test day."
    ),
    (
        2,
        "**Reading & Writing: Strategy Recap**\n\n"
        "The Reading & Writing section tests four distinct skill domains. If you know which "
        "domain a question belongs to before you start reading the answer choices, you already "
        "know which strategy to apply. That recognition -- type first, method second -- is the "
        "highest-leverage habit in the entire section.\n\n"
        "**Domain 1 -- Craft & Structure (~28% of the section)**\n"
        "These questions ask how language is used, not just what it says.\n"
        "- **Words in Context:** the stem says 'most nearly means' or asks you to fill a blank "
        "with the most precise word. Your move: ignore the choices, read the sentence and one "
        "sentence on either side, predict your own replacement word, then match.\n"
        "- **Text Structure & Organization:** the stem asks about the function of a sentence, "
        "paragraph, or structural choice. Label the passage structure before you read choices.\n"
        "- **Cross-Text Connections:** two short passages on the same topic; you must identify "
        "where they agree and where they diverge. Write one sentence per author in the margin "
        "before touching the choices.\n"
        "- **Author's Perspective:** you must identify tone, attitude, or how the author would "
        "respond to another claim. Underline every evaluative word (admirably, surprisingly, "
        "unfortunately) -- these are direct signals of perspective.\n\n"
        "**Domain 2 -- Information & Ideas (~26% of the section)**\n"
        "These questions test whether you correctly understand what the passage says and implies.\n"
        "- **Central Ideas:** the main idea must cover the whole passage -- any choice that is "
        "too narrow (just one detail) or too broad (goes beyond the text) is wrong.\n"
        "- **Command of Evidence (textual):** find the quotation or detail that most directly "
        "proves or disproves the stated claim. 'Related to the topic' is not enough -- it must "
        "speak to the specific claim.\n"
        "- **Command of Evidence (quantitative):** a chart or table is paired with text. Identify "
        "exactly which data point or comparison the question is asking about, then read the graph.\n"
        "- **Inferences:** the correct answer is the most logical conclusion, not a stretch. "
        "It must follow directly from the evidence in the passage.\n\n"
        "**Domain 3 -- Standard English Conventions (~26% of the section)**\n"
        "These questions test grammar and mechanics. The stem says 'conforms to the conventions "
        "of Standard Written English.'\n"
        "- **Sentence Boundaries:** identify whether each side of the punctuation mark is a "
        "complete sentence. Two complete sentences need a period, semicolon, or comma + FANBOYS. "
        "A comma alone between two complete sentences is always wrong (comma splice).\n"
        "- **Subject-Verb Agreement:** find the true subject -- cross out prepositional phrases "
        "('of the students,' 'along with the coach') to isolate it.\n"
        "- **Verb Tense and Pronoun Reference:** tense must match the time frame established "
        "in the sentence; pronouns must clearly and logically refer to a specific noun.\n"
        "- **Modifiers:** the noun that follows a descriptive opening phrase must be the thing "
        "the phrase actually describes. If not, it is a dangling modifier.\n\n"
        "**Domain 4 -- Expression of Ideas (~20% of the section)**\n"
        "- **Transitions:** read the sentence before and after the blank. Decide the logical "
        "relationship: additive (furthermore, also), contrasting (however, yet), causal "
        "(therefore, as a result), or illustrative (for example, specifically). Pick the "
        "transition word that matches.\n"
        "- **Rhetorical Synthesis:** you are given a student's bullet-point notes and a stated "
        "writing goal. Match the answer choice to the goal -- not to the most interesting or "
        "most detailed bullet, but to the one that achieves the stated purpose.\n\n"
        "**The Universal R&W Process**\n"
        "Step 1: Read the question stem first. Know what you are looking for before you read "
        "the passage.\n"
        "Step 2: Read the passage or notes.\n"
        "Step 3: Predict your answer in your own words before reading the choices.\n"
        "Step 4: Eliminate wrong choices using the passage as your only judge. If a choice "
        "sounds plausible but isn't supported by the text, eliminate it.\n\n"
        "⚠️ Common mistake: reading all four answer choices first and then going back to the "
        "passage to find support. This approach lets attractive wrong answers contaminate your "
        "reading. The passage must drive your prediction -- not the other way around.\n\n"
        "💡 Tip: The fastest readers on the SAT spend the most time on the question stem and "
        "the least time on the answer choices, because they predict accurately. For every "
        "question, ask yourself: 'If I had to answer this in one sentence before looking at the "
        "choices, what would I say?' That sentence is your prediction -- protect it."
    ),
    (
        3,
        "**Math: Strategy Recap**\n\n"
        "SAT Math is not a test of mathematical talent. It is a test of mathematical procedure "
        "applied under time pressure. The students who score highest are not always the students "
        "who know the most advanced mathematics -- they are the students who set up problems "
        "correctly, avoid careless errors, and know exactly which tool to reach for on each "
        "question type. This lesson gives you those tools.\n\n"
        "**The Four Math Domains**\n"
        "- **Algebra (~35%):** linear equations, systems of equations, linear inequalities, "
        "linear functions, and absolute value. This is the largest domain -- master it first.\n"
        "- **Advanced Math (~35%):** quadratic equations, polynomials, exponential functions, "
        "rational expressions, and function notation. Most 'hard' questions live here.\n"
        "- **Problem-Solving & Data Analysis (~15%):** ratios, rates, unit conversions, "
        "percentages, probability, and statistics (mean, median, mode, margin of error, "
        "interpreting tables and graphs). Heavy on real-world context.\n"
        "- **Geometry & Trigonometry (~15%):** area, perimeter, volume, coordinate geometry, "
        "right triangles, the Pythagorean theorem, and SOH-CAH-TOA.\n\n"
        "**Calculator Strategy**\n"
        "A College Board-approved calculator (including Desmos, built into the test interface) "
        "is allowed for both Math modules. But a calculator cannot set up a problem -- you can. "
        "Always read and annotate the question on paper (or on-screen) before you calculate. "
        "Students who reach for the calculator first and set up the problem second make "
        "systematic errors because they calculate the right answer to the wrong question.\n\n"
        "**Grid-In (Free Response) Format**\n"
        "Several questions per module require you to enter a numerical answer, not choose one. "
        "Key rules:\n"
        "- Fractions and decimals are both accepted.\n"
        "- Never grid in a mixed number: 2½ must be entered as 5/2 or 2.5.\n"
        "- If your answer is a repeating decimal, fill the grid completely (e.g., .333).\n"
        "- There is no negative sign in the grid -- if you get a negative answer, recheck your work.\n\n"
        "**The Plug-In Strategy**\n"
        "When a question and its answer choices both contain variables, **assign a simple number** "
        "to the variable (use 2, 3, or 5 -- avoid 0 and 1 because they create special cases). "
        "Compute both the question and the answer choices with your number. The choice that "
        "matches your computed result is correct. This strategy converts an abstract algebra "
        "problem into basic arithmetic.\n\n"
        "**The Backsolving Strategy**\n"
        "When the question asks for a specific numerical value and the four answer choices are "
        "numbers (not expressions), **substitute the choices back into the equation or scenario**. "
        "Start with the middle value -- if there are four choices, start with the second-smallest. "
        "If it produces a value that is too high, try the smallest; if too low, try the largest. "
        "You will find the answer in at most two substitutions.\n\n"
        "**What Is (and Is Not) on the Formula Sheet**\n"
        "The on-screen reference sheet includes: area and perimeter of common shapes, volume "
        "formulas, the Pythagorean theorem, and special right triangle ratios. It does NOT include: "
        "the quadratic formula, the distance formula, slope formula, SOH-CAH-TOA, or any "
        "statistics formulas. Know those by heart before test day.\n\n"
        "**Time Management**\n"
        "Each Math module gives you 22 questions in 35 minutes -- that is 1 minute and 35 "
        "seconds per question. Easy questions at the beginning of a module should take 45 to "
        "60 seconds. Hard questions at the end may take 2 to 3 minutes. The rule: if you have "
        "been on a question for more than 2 minutes, flag it, answer your best guess, and "
        "move on. Return at the end if time allows. Do not let one hard question cost you "
        "three easy ones that come after it.\n\n"
        "**Common Traps to Avoid**\n"
        "- Reading the last line too quickly: many questions ask for x + 3 or 2y, not x or y.\n"
        "- Forgetting to flip the inequality sign when multiplying or dividing by a negative number.\n"
        "- Using the area formula when the question asks for circumference, or vice versa.\n"
        "- Treating correlation in a data table as causation (a common Data Analysis trap).\n\n"
        "⚠️ Common mistake: spending 4 to 5 minutes on a single difficult question in Module 1, "
        "then rushing the remaining questions. One hard question is worth the same as one easy "
        "question. Protect your easy points first.\n\n"
        "💡 Tip: After you find an answer, spend 5 seconds re-reading the question's last line "
        "to confirm you solved for the right thing. 'What is the value of 3x + 1?' is not the "
        "same as 'What is the value of x?' This single habit eliminates one of the most common "
        "careless-error categories on the entire Math section."
    ),
    (
        4,
        "**Test-Day Game Plan: Pacing & Stamina**\n\n"
        "You have done the preparation. You know the content. Now the question is: can you "
        "execute for two hours and fourteen minutes under real conditions? Stamina and pacing "
        "are skills -- and like every other skill on this test, they are trainable. This is "
        "your game plan for the day everything counts.\n\n"
        "**The Night Before**\n"
        "- Lay out your government-issued photo ID, your admission ticket (printed or on your "
        "phone), an approved calculator with fresh batteries, and two No. 2 pencils.\n"
        "- Eat a real dinner -- not just snacks. Your brain runs on glucose; fuel it properly.\n"
        "- Avoid screens after 9 PM. Blue light suppresses melatonin and shortens deep sleep.\n"
        "- Aim for at least 8 hours of sleep. This is non-negotiable. No amount of last-minute "
        "studying compensates for impaired working memory caused by sleep deprivation.\n"
        "- Do not study new material the night before. Review your notes briefly if it calms "
        "you, then stop. Your job now is rest.\n\n"
        "**The Morning Of**\n"
        "- Eat a real breakfast -- protein, complex carbohydrates, and minimal sugar. A blood "
        "sugar crash during the Math section is a real and avoidable problem.\n"
        "- Arrive 15 to 20 minutes early. Late arrivals are turned away.\n"
        "- Bring a snack (granola bar, nuts, fruit) and a water bottle for the break.\n"
        "- Leave your phone in your bag during the test. Checking it during the break is a "
        "distraction and a potential rules violation.\n\n"
        "**During the Reading & Writing Section**\n"
        "- Read the question stem before the passage. Know what you're hunting for.\n"
        "- Answer every question -- there is no penalty for wrong answers. A blank earns "
        "zero points. A guess earns either one point or zero; the expected value is always "
        "positive. Guess on everything you cannot solve.\n"
        "- Flag uncertain questions and return to them. Do not stall.\n"
        "- Trust your prediction over your gut feeling. If you predicted an answer before "
        "reading the choices and the choices are making you second-guess yourself, go back "
        "to the passage. The passage is always the judge.\n\n"
        "**During the 10-Minute Break**\n"
        "- Eat your snack and drink water.\n"
        "- Stand up, walk around, and shake out your hands and shoulders.\n"
        "- Do NOT review your Reading & Writing answers. That section is locked; you cannot "
        "change anything, and revisiting it occupies mental space you need for Math.\n"
        "- Do NOT discuss the test with other students. Their experience of the questions "
        "can shake your confidence for no reason.\n"
        "- Take three slow, deep breaths before returning to your seat.\n\n"
        "**During the Math Section**\n"
        "- The reference sheet is available -- use it freely for geometry formulas.\n"
        "- Write out your work. Students who set up problems on paper make fewer errors than "
        "students who try to hold setups in their head.\n"
        "- Pace yourself: 22 questions in 35 minutes is 1 minute 35 seconds each. Easy "
        "questions early in the module should take under 60 seconds. If a question is taking "
        "more than 2 minutes, flag it and move on.\n"
        "- Use the 5-minute break between Math modules to reset mentally. Breathe. Refocus.\n\n"
        "**Managing Test Anxiety**\n"
        "If you feel panic rising during the test, do this: stop, put down your pencil or "
        "lift your hands from the keyboard, and take three slow breaths (inhale 4 counts, "
        "exhale 6 counts). Then refocus only on the current question. Not the last question "
        "you got wrong. Not how many questions are left. Just the one in front of you. "
        "One question at a time is the only unit of measurement that matters during the test.\n\n"
        "**The Adaptive Mindset**\n"
        "If your Math Module 2 feels hard -- harder than Module 1 -- that is good news. It "
        "means the engine routed you to the high-score track. Lean into it. Hard questions "
        "in Module 2 are worth more. Do not panic at difficulty; recalibrate. Take an extra "
        "30 seconds to set up carefully if you need it.\n\n"
        "**After the Test**\n"
        "Scores are typically released within two weeks of your test date. If you are not "
        "satisfied, the SAT can be retaken -- most students improve on a second attempt after "
        "reviewing their score report and targeting weak domains. One test is data, not destiny.\n\n"
        "⚠️ Common mistake: skipping breakfast or eating only coffee and sugar, then "
        "experiencing a focus crash in the second half of Math. Your brain is burning through "
        "energy at an elevated rate during an exam. Feed it.\n\n"
        "💡 Tip: The single most important mindset rule for test day is this -- you have "
        "prepared, and preparation is the only thing you control. You cannot control which "
        "questions appear, how other students perform, or what your score will be. You can "
        "control your process: read carefully, predict before choosing, write out your work, "
        "answer every question, and flag-and-return when stuck. Trust your training. Execute "
        "your process. The score takes care of itself."
    ),
]


class Command(BaseCommand):
    help = "Enrich lesson content for SAT Full-Length Practice Test"

    def handle(self, *args, **options):
        for order, content in LESSONS:
            rows = Lesson.objects.filter(
                course__slug="sat-full-length-practice", order=order
            ).update(content=content)
            self.stdout.write(f"  Lesson {order}: {rows} row(s) updated")
        self.stdout.write(
            self.style.SUCCESS(
                "Done enriching SAT Full-Length Practice Test lessons."
            )
        )
