from django.core.management.base import BaseCommand
from courses.models import Lesson

LESSONS = [
    (
        1,
        "**Linear Equations in One Variable** — the most fundamental skill in SAT Algebra — asks you to find the value of a variable that makes an equation true. Mastering the different types and recognizing special cases will earn you points quickly.\n\n"
        "**Types of Linear Equations**\n\n"
        "- **One-step equations:** A single operation stands between you and the answer. Example: x + 9 = 15. Subtract 9 from both sides to get x = 6. Example: x/4 = 3. Multiply both sides by 4 to get x = 12.\n"
        "- **Two-step equations:** Undo addition or subtraction first, then undo multiplication or division. Example: 2x - 4 = 10. Add 4: 2x = 14. Divide by 2: x = 7.\n"
        "- **Multi-step equations:** Distribute, combine **like terms**, then isolate the variable. Example: 3(x - 2) + x = 14. Distribute: 3x - 6 + x = 14. Combine: 4x - 6 = 14. Add 6: 4x = 20. Divide by 4: x = 5.\n"
        "- **Equations with fractions:** Multiply every term by the **LCD (Least Common Denominator)** to clear fractions before solving. Example: x/3 + x/4 = 7. LCD = 12. Multiply through: 4x + 3x = 84. So 7x = 84, x = 12.\n"
        "- **Equations with decimals:** Multiply every term by 10 or 100 to convert to integers. Example: 0.2x + 0.5 = 1.3. Multiply by 10: 2x + 5 = 13. So 2x = 8, x = 4.\n\n"
        "**No Solution vs. Infinite Solutions**\n\n"
        "When you solve an equation and the variable cancels out entirely, the result is either a **false statement** or a **true statement**.\n\n"
        "- **No solution:** Variable cancels, leaving something like 3 = 7. This is impossible — no value of x can make it true. Graphically, the two sides represent **parallel lines** that never intersect.\n"
        "- **Infinite solutions:** Variable cancels, leaving something like 5 = 5. This is always true — every real number is a solution. Graphically, both sides represent the **same line**.\n\n"
        "**SAT Example 1 (Difficulty: Easy)**\n"
        "If 3x - 7 = 14, what is the value of x?\n"
        "Step 1: Add 7 to both sides: 3x = 21.\n"
        "Step 2: Divide by 3: x = 7.\n"
        "Answer: x = 7. Verify: 3(7) - 7 = 21 - 7 = 14. Correct.\n\n"
        "**SAT Example 2 (Difficulty: Medium)**\n"
        "Solve: 4(x - 2) + 2 = 3x + 4.\n"
        "Step 1: Distribute: 4x - 8 + 2 = 3x + 4.\n"
        "Step 2: Simplify left side: 4x - 6 = 3x + 4.\n"
        "Step 3: Subtract 3x: x - 6 = 4.\n"
        "Step 4: Add 6: x = 10.\n"
        "Verify: 4(10 - 2) + 2 = 32 + 2 = 34; 3(10) + 4 = 34. Correct.\n\n"
        "**SAT Example 3 (Difficulty: Medium — Special Case)**\n"
        "How many solutions does 2(x + 5) = 2x + 10 have?\n"
        "Step 1: Distribute: 2x + 10 = 2x + 10.\n"
        "Step 2: Subtract 2x from both sides: 10 = 10.\n"
        "This is always true, so there are **infinitely many solutions**.\n\n"
        "**Common SAT Traps**\n\n"
        "- **Solving for the wrong thing:** If the question asks for 3x and you find x = 4, the answer is 12 — not 4. Re-read the final question before writing your answer.\n"
        "- **Not distributing the negative:** -(x - 3) = -x + 3, not -x - 3. Every term inside the parentheses changes sign.\n"
        "- **Missing both solutions of |x| = k:** The equation |x - 2| = 5 gives x - 2 = 5 (so x = 7) AND x - 2 = -5 (so x = -3). Always set up both cases for absolute value.\n"
        "- **Stopping too early:** After finding x = 5, check whether the problem actually wants 2x + 1.\n\n"
        "**Tip:** Always substitute your answer back into the original equation to verify. This takes 10 seconds and can catch errors before they cost you points."
    ),
    (
        2,
        "A **linear function** creates a perfectly straight line on the coordinate plane. The SAT tests your ability to work with multiple forms of linear equations, find key features, and reason about relationships between lines.\n\n"
        "**The Four Forms**\n\n"
        "- **Slope-intercept form:** y = mx + b. The slope **m** is immediately visible, and **b** is the y-intercept. This is the most useful form for reading off key features.\n"
        "- **Point-slope form:** y - y₁ = m(x - x₁). Use this when you know one point and the slope but not the y-intercept. Rearrange to slope-intercept when needed.\n"
        "- **Standard form:** Ax + By = C. Often seen in systems of equations. Convert to slope-intercept by solving for y: y = (C - Ax)/B = (C/B) - (A/B)x.\n"
        "- **Horizontal and vertical lines:** y = k is a horizontal line (slope = 0). x = k is a vertical line (slope is undefined).\n\n"
        "**Slope Formula**\n\n"
        "**Slope (m) = (y₂ - y₁) / (x₂ - x₁)**. Slope measures rise over run — how much y changes for every 1-unit increase in x.\n\n"
        "[[figure:slope_types|Types of slope — positive, negative, zero, undefined]]\n\n"
        "- **Positive slope:** Line rises from left to right.\n"
        "- **Negative slope:** Line falls from left to right.\n"
        "- **Zero slope:** Perfectly horizontal line.\n"
        "- **Undefined slope:** Perfectly vertical line.\n\n"
        "**Finding Intercepts**\n\n"
        "- **y-intercept:** Set x = 0 and solve for y. In y = 3x - 6: y = 3(0) - 6 = -6. The y-intercept is (0, -6).\n"
        "- **x-intercept:** Set y = 0 and solve for x. In y = 3x - 6: 0 = 3x - 6, so x = 2. The x-intercept is (2, 0).\n\n"
        "**Writing an Equation from Two Points**\n\n"
        "Step 1: Calculate slope using the slope formula.\n"
        "Step 2: Plug the slope and one point into point-slope form.\n"
        "Step 3: Simplify to slope-intercept form.\n\n"
        "**Parallel and Perpendicular Lines**\n\n"
        "- **Parallel lines** have the same slope but different y-intercepts: m₁ = m₂.\n"
        "- **Perpendicular lines** have slopes that are **negative reciprocals** of each other: m₁ × m₂ = -1. If one slope is 3, the perpendicular slope is -1/3.\n\n"
        "**SAT Example 1:** A line passes through (2, 5) and (6, 13). What is its y-intercept?\n"
        "Step 1: Slope = (13 - 5)/(6 - 2) = 8/4 = 2.\n"
        "Step 2: Point-slope: y - 5 = 2(x - 2) → y - 5 = 2x - 4 → y = 2x + 1.\n"
        "The y-intercept is **1** (the point (0, 1)).\n\n"
        "**SAT Example 2 (Interpreting slope in context):** A taxi charges according to y = 2.5x + 3, where x is miles and y is cost in dollars. What does 2.5 represent?\n"
        "The slope 2.5 is the **rate of change**: the cost increases by $2.50 for each additional mile. The constant 3 is the base fare when no miles are driven.\n\n"
        "**SAT Example 3 (Parallel/Perpendicular):** A line has equation y = -3x + 7. Which line is perpendicular to it?\n"
        "The slope is -3. The perpendicular slope is the negative reciprocal: 1/3. Any line of the form y = (1/3)x + b is perpendicular.\n\n"
        "**Common SAT Traps**\n\n"
        "- **Swapping numerator and denominator in the slope formula:** Always put y-values in the numerator and x-values in the denominator.\n"
        "- **Confusing x-intercept and y-intercept:** Remember, y-intercept is where the line crosses the y-axis (x = 0); x-intercept is where it crosses the x-axis (y = 0).\n"
        "- **Forgetting that perpendicular slopes are negative reciprocals:** The reciprocal of 2 is 1/2, but you must also flip the sign to get -1/2.\n\n"
        "**Tip:** Before answering any question about a linear function, rewrite the equation in slope-intercept form (y = mx + b). The slope and y-intercept are then immediately readable without further calculation."
    ),
    (
        3,
        "A **system of linear equations** is a set of two or more equations that must all be satisfied simultaneously. The solution is the ordered pair (x, y) that makes every equation in the system true at the same time.\n\n"
        "**Method 1: Substitution**\n\n"
        "Best used when one variable is already isolated (or easy to isolate).\n\n"
        "Step 1: Solve one equation for one variable.\n"
        "Step 2: Substitute that expression into the other equation.\n"
        "Step 3: Solve the resulting single-variable equation.\n"
        "Step 4: Substitute back to find the other variable.\n\n"
        "Example: y = 2x - 1 and 3x + y = 14.\n"
        "Substitute y: 3x + (2x - 1) = 14 → 5x - 1 = 14 → 5x = 15 → x = 3.\n"
        "Back-substitute: y = 2(3) - 1 = 5. Solution: (3, 5).\n\n"
        "**Method 2: Elimination (Addition Method)**\n\n"
        "Best used when both equations are in standard form Ax + By = C.\n\n"
        "Step 1: Multiply one or both equations by constants so that one variable has equal and opposite coefficients.\n"
        "Step 2: Add the equations — the target variable cancels.\n"
        "Step 3: Solve for the remaining variable, then back-substitute.\n\n"
        "Example: 2x + 3y = 12 and 5x - 3y = 9.\n"
        "The y-coefficients are already opposites. Add the equations: 7x = 21 → x = 3.\n"
        "Back-substitute: 2(3) + 3y = 12 → 6 + 3y = 12 → y = 2. Solution: (3, 2).\n\n"
        "**Scaling Example:** 3x + 2y = 11 and 5x + 4y = 21. Multiply the first equation by 2: 6x + 4y = 22. Subtract the second: x = 1. Back-substitute: y = 4.\n\n"
        "**Number of Solutions**\n\n"
        "- **One solution:** Lines intersect at exactly one point. Different slopes.\n"
        "- **No solution:** Lines are parallel — same slope, different y-intercepts. Algebraically, a contradiction like 0 = 5 appears.\n"
        "- **Infinitely many solutions:** Lines are identical — same slope, same y-intercept. Algebraically, a tautology like 0 = 0 appears.\n\n"
        "**How to tell algebraically without graphing:** Put both equations into slope-intercept form. If slopes differ → one solution. If slopes are equal and intercepts differ → no solution. If both slope and intercept are equal → infinite solutions.\n\n"
        "**SAT Shortcut:** If the question asks for x + y or 2x - y (not for x and y individually), try **adding or subtracting the two equations directly** to see if it produces the target expression. This can save 60+ seconds per problem.\n\n"
        "**SAT Example 1:** Solve: x + y = 10 and x - y = 4.\n"
        "Add: 2x = 14 → x = 7. Substitute: y = 3. Solution: (7, 3).\n\n"
        "**SAT Example 2 (No solution):** 2x + 3y = 12 and 4x + 6y = 18.\n"
        "Multiply the first by 2: 4x + 6y = 24. Compare to 4x + 6y = 18. Since 24 ≠ 18, there is no solution.\n\n"
        "**SAT Example 3 (Word problem):** A store sells pens for $2 and notebooks for $5. A customer buys 8 items for $25. How many of each?\n"
        "Let p = pens, n = notebooks. System: p + n = 8 and 2p + 5n = 25.\n"
        "Multiply first by 2: 2p + 2n = 16. Subtract from second: 3n = 9 → n = 3. So p = 5.\n\n"
        "**Common SAT Traps**\n\n"
        "- **Finding only one variable:** After elimination or substitution, always solve for both x and y unless the problem specifies otherwise.\n"
        "- **Sign errors during elimination:** When subtracting equations, distribute the negative to every term.\n"
        "- **Assuming a unique solution exists:** Always check whether the problem could have no solution or infinitely many.\n\n"
        "**Tip:** On the SAT, if you see a system where both equations share the same structure (same ratio of coefficients), immediately check for the no-solution or infinite-solution case before doing any work."
    ),
    (
        4,
        "A **linear inequality** replaces the equals sign of a linear equation with an inequality symbol (<, >, ≤, or ≥). Solving, graphing, and interpreting inequalities are all heavily tested on the SAT.\n\n"
        "**Solving Linear Inequalities**\n\n"
        "The steps mirror equation-solving with one critical rule:\n\n"
        "Step 1: Simplify each side — distribute and combine **like terms**.\n"
        "Step 2: Move variable terms to one side using addition or subtraction.\n"
        "Step 3: Isolate the variable by multiplying or dividing.\n"
        "Step 4 (The Flip Rule): **Whenever you multiply or divide both sides by a negative number, flip the inequality sign.** This is the most commonly tested rule in all of SAT algebra.\n\n"
        "Example: -3x + 6 ≤ 18. Subtract 6: -3x ≤ 12. Divide by -3 and flip: x ≥ -4.\n\n"
        "[[figure:linear_inequality_shade|Number line with shaded inequality region]]\n\n"
        "**Compound Inequalities**\n\n"
        "- **AND (conjunction):** Both conditions must hold simultaneously. Written as a “sandwich”: -2 < x ≤ 5. On the number line, shade the **overlap** of both regions.\n"
        "- **OR (disjunction):** At least one condition holds. Example: x < -1 or x > 4. On the number line, shade the **union** of both regions (two separate shaded segments).\n\n"
        "**Interval Notation Reference Table**\n\n"
        "- x > a → (a, ∞)\n"
        "- x ≥ a → [a, ∞)\n"
        "- x < b → (-∞, b)\n"
        "- x ≤ b → (-∞, b]\n"
        "- a < x < b → (a, b)\n"
        "- a ≤ x ≤ b → [a, b]\n\n"
        "Parentheses ( ) are used for **strict** inequalities (< or >); brackets [ ] are used for **inclusive** inequalities (≤ or ≥).\n\n"
        "**Graphing on the Coordinate Plane**\n\n"
        "When graphing y > mx + b or y ≤ mx + b:\n\n"
        "- **Dashed boundary line** for strict inequalities (< or >); **solid boundary line** for inclusive (≤ or ≥).\n"
        "- To choose which side to shade: **pick a test point** (usually (0, 0)) and substitute. If the inequality is satisfied, shade the side containing that point. If not, shade the other side.\n\n"
        "**SAT Example 1 (One-step):** Which value satisfies 2x + 3 > 11?\n"
        "2x > 8 → x > 4. Only values greater than 4 qualify. Check answer choices for a number like 5 or 6.\n\n"
        "**SAT Example 2 (Flip the sign):** Solve -4x ≥ 20.\n"
        "Divide by -4 and flip: x ≤ -5. In interval notation: (-∞, -5].\n\n"
        "**SAT Example 3 (Compound):** Solve -1 < 3x - 4 < 11.\n"
        "Add 4 to all three parts: 3 < 3x < 15. Divide by 3: 1 < x < 5. In interval notation: (1, 5).\n\n"
        "**Common SAT Traps**\n\n"
        "- **Forgetting to flip the inequality sign:** Dividing by a negative without flipping is the single most common algebra mistake on the SAT. Always check whether you divided by a negative.\n"
        "- **Using the wrong bracket type in interval notation:** x > 3 is (3, ∞), not [3, ∞). The open circle on the number line corresponds to a parenthesis.\n"
        "- **Incorrect test point:** When graphing, some students always test (0, 0) without realizing it lies on the boundary line for equations like y = x. Choose a point clearly off the boundary.\n\n"
        "**Tip:** After solving an inequality, pick a value from your solution set and substitute it into the original inequality. If the inequality holds, your solution is correct. This verification step takes 10 seconds and catches sign-flip errors every time."
    ),
    (
        5,
        "A large share of SAT algebra problems disguise algebraic equations as everyday stories. Your task is to **translate** the words into math, **solve**, and **interpret** the result in context.\n\n"
        "**Translation Table**\n\n"
        "- \"is,\" \"equals,\" \"is the same as,\" \"gives\" → =\n"
        "- \"more than,\" \"increased by,\" \"added to\" → +\n"
        "- \"less than,\" \"decreased by,\" \"subtracted from\" → -\n"
        "- \"times,\" \"of,\" \"per,\" \"at a rate of\" → ×\n"
        "- \"split equally,\" \"divided among\" → ÷\n"
        "- \"what number,\" \"how many,\" \"find\" → use a variable (x)\n\n"
        "**Warning on “less than”:** \"5 less than x\" means x - 5, not 5 - x. The subject of the phrase comes first in the subtraction.\n\n"
        "**Common Linear Model Types**\n\n"
        "- **Distance = Rate × Time (d = rt):** Use when objects travel at constant speeds. Two objects moving in opposite directions: total distance = (r₁ + r₂) × t. Two objects moving in the same direction: distance between = |r₁ - r₂| × t.\n"
        "- **Fixed + Variable Cost:** Total = base fee + (rate per unit × quantity). Example: C = 75 + 50h for a plumber charging $75 flat plus $50/hour.\n"
        "- **Mixture problems:** Two quantities combined. Example: 30% solution + 60% solution = 45% solution. Set up: 0.30x + 0.60y = 0.45(x + y), plus x + y = total.\n"
        "- **Consecutive integer problems:** Consecutive integers: n, n+1, n+2. Consecutive even or odd integers: n, n+2, n+4.\n"
        "- **Break-even:** Set revenue equal to total cost: R(x) = C(x). Solve for x.\n\n"
        "**Step-by-Step Problem-Solving Framework**\n\n"
        "Step 1: Define your variable(s) — write \"Let x = ...\"\n"
        "Step 2: Write the equation(s) from the word problem.\n"
        "Step 3: Solve algebraically.\n"
        "Step 4: Check reasonableness (negative time? Fractional number of people? These indicate an error).\n"
        "Step 5: Answer the specific question asked (the problem may ask for 2x, not x).\n\n"
        "**SAT Example 1 (Distance):** Two trains leave the same station in opposite directions. Train A travels at 55 mph; Train B at 45 mph. After how many hours are they 300 miles apart?\n"
        "Combined speed = 55 + 45 = 100 mph. Distance = rate × time: 300 = 100t → t = 3 hours.\n\n"
        "**SAT Example 2 (Fixed + Variable):** A car rental costs $30 per day plus $0.20 per mile. Jenna’s bill for one day was $78. How many miles did she drive?\n"
        "78 = 30 + 0.20m → 48 = 0.20m → m = 240 miles.\n\n"
        "**SAT Example 3 (Break-even):** A company sells widgets for $20 each. Fixed costs are $360; variable cost is $8 per widget. How many widgets must they sell to break even?\n"
        "Revenue = Cost → 20x = 8x + 360 → 12x = 360 → x = 30 widgets.\n"
        "Check: Revenue = 20(30) = $600; Cost = 8(30) + 360 = $240 + $360 = $600. Confirmed.\n\n"
        "**Checking Reasonableness**\n\n"
        "- Negative time (t = -2 hours) → recheck your equation setup.\n"
        "- Fractional people (x = 3.5 students) → round only if the problem says so, otherwise recheck.\n"
        "- Answer significantly larger or smaller than numbers in the problem → verify you used the right units.\n\n"
        "**Common SAT Traps**\n\n"
        "- **Confusing “x less than y” with “x minus y”:** “5 less than x” is x - 5; “x less than 5” is 5 - x.\n"
        "- **Mixing units:** If some quantities are in minutes and others in hours, convert everything to the same unit before writing the equation.\n"
        "- **Using the wrong variable as the answer:** After solving for x = 30 widgets, make sure the question didn’t ask for revenue at break-even.\n\n"
        "**Tip:** Underline the key quantities and their units as you read the problem. Define your variable in writing before you write any equation. This discipline eliminates the majority of word-problem errors."
    ),
    (
        6,
        "One of the most distinctive SAT question types does not ask you to solve — instead, it asks you to **explain what a number means** in a real-world context. These questions reward students who understand structure over those who merely compute.\n\n"
        "**The Framework: y = mx + b**\n\n"
        "For any linear model of the form y = mx + b:\n\n"
        "- **m (the slope / coefficient of x)** is the **rate of change**. It tells you how much y increases (or decreases) for every one-unit increase in x. It always carries units of “y-units per x-unit.”\n"
        "- **b (the constant / y-intercept)** is the **initial value** — the value of y when x = 0. It represents a starting amount, flat fee, or baseline measurement.\n\n"
        "**Units Analysis**\n\n"
        "Units help you interpret. If x is measured in hours and y in dollars, then:\n\n"
        "- The coefficient of x has units of **dollars per hour** (a rate).\n"
        "- The constant has units of **dollars** (a fixed amount independent of time).\n\n"
        "Always ask: “What does one unit of x represent? What happens to y when x increases by 1?”\n\n"
        "**SAT Example 1 (Coefficient as rate):** In the equation C = 50 + 12n, C is total cost in dollars and n is the number of items purchased. What does 12 represent?\n"
        "12 is the coefficient of n. For each additional item purchased (n increases by 1), the cost increases by $12. So 12 represents the **cost per item**.\n"
        "50 is the constant (y-intercept). When n = 0 (no items purchased), C = 50. So 50 represents the **fixed starting cost** (base fee, delivery charge, etc.).\n\n"
        "**SAT Example 2 (Interpreting a population model):** P = 1500 - 25t, where P is population and t is years after 2000. What does each part mean?\n"
        "- 1500 is the initial value (t = 0, year 2000): the population was 1,500 in 2000.\n"
        "- -25 is the rate of change: the population **decreases by 25 people per year**. The negative sign tells you it is declining.\n\n"
        "**SAT Example 3 (Unit conversion question):** A phone plan costs C = 15 + 0.05m, where C is in dollars and m is in minutes. By how much does C increase for each additional 20 minutes?\n"
        "The rate is $0.05 per minute. For 20 minutes: 0.05 × 20 = **$1.00** increase.\n"
        "Do not confuse the per-minute rate (0.05) with the cost for 20 minutes (1.00).\n\n"
        "**Common SAT Phrasing and How to Respond**\n\n"
        "- \"What does 12 represent in this context?\" → Identify whether 12 is a coefficient or a constant. Coefficient = rate of change; constant = initial value.\n"
        "- \"What is the meaning of the constant 50?\" → Substitute x = 0 into the equation and interpret the result in context.\n"
        "- \"By how much does C increase for each additional unit?\" → This is asking for the coefficient (slope), not the constant.\n"
        "- \"What value of x makes y equal zero?\" → Set y = 0 and solve. This is the x-intercept, which may or may not have a real-world meaning.\n\n"
        "**Common SAT Traps**\n\n"
        "- **Confusing the coefficient with the constant:** Many students reverse them. Remember: the coefficient is attached to the variable (it changes); the constant stands alone (it does not change with x).\n"
        "- **Ignoring units:** A coefficient of 12 in a cost-per-item model means something very different from 12 in a speed-in-miles-per-hour model. Read the context carefully.\n"
        "- **Interpreting b as a rate:** b is not a rate. It is a fixed value that does not depend on x. The rate is always m.\n\n"
        "**Tip:** To find what the constant means, substitute x = 0. To find what the coefficient means, substitute x = 1 and x = 0, then find the difference. This gives the exact change per unit, straight from the model."
    ),
    (
        7,
        "Knowing algebra is necessary but not sufficient for a top SAT score. **Strategic test-taking** — choosing the right method for each problem — can save minutes that are better spent on harder questions.\n\n"
        "**Strategy 1: Plugging In Numbers**\n\n"
        "When a question has variables in both the question and the answer choices, replace the variable with a specific simple number, compute the target expression, then find which answer matches.\n\n"
        "When to use: The answer choices contain variables; the problem says “in terms of x.”\n\n"
        "Example: If the cost of n items is C = 3n + 5, which expression represents the cost of (n + 2) items?\n"
        "Plug in n = 4: C = 3(4) + 5 = 17. Now (n + 2) = 6 items: C = 3(6) + 5 = 23.\n"
        "Check each answer choice with n = 4 and find the one that gives 23. The answer 3n + 11 gives 3(4) + 11 = 23. Correct.\n"
        "Avoid plugging in 0 or 1 since they often make multiple choices produce the same value.\n\n"
        "**Strategy 2: Backsolving (Working from Answer Choices)**\n\n"
        "When answer choices are specific numbers and the question asks you to solve for a value, substitute each answer choice into the original equation or inequality.\n\n"
        "When to use: Answer choices are numbers; setting up algebra feels slow or error-prone.\n\n"
        "Step 1: Start with choice B or C (middle values on the SAT, choices are often ordered).\n"
        "Step 2: Substitute into the problem. If too high, try a smaller choice; if too low, try a larger one.\n\n"
        "Example: Which value of x satisfies 3x - 4 = 2x + 1?\n"
        "Try x = 5: Left side = 3(5) - 4 = 11. Right side = 2(5) + 1 = 11. Match! Answer is x = 5.\n\n"
        "**Strategy 3: Process of Elimination**\n\n"
        "Partial knowledge still eliminates wrong answers.\n\n"
        "- **Eliminate by sign:** If you know x must be positive, eliminate all negative choices.\n"
        "- **Eliminate by magnitude:** If the answer must be between 0 and 10, eliminate choices like 50 or -3.\n"
        "- **Eliminate by structure:** If the answer must be an integer, eliminate fractions and decimals.\n\n"
        "Even eliminating one or two choices dramatically improves your odds on a guess.\n\n"
        "**Strategy 4: Time Management**\n\n"
        "- **60-second rule:** If you have spent more than 60 seconds on a problem without a clear path forward, mark it and move on. Return with fresh eyes after completing easier problems.\n"
        "- **Flagging:** Use the test’s flagging feature (or a mark in your booklet) to identify skipped questions so you find them quickly on the return pass.\n"
        "- **Calculator vs. mental math:** On the calculator section, use the calculator for messy arithmetic but solve clean algebra mentally to save time. Typing simple equations is often slower than mental solving.\n\n"
        "**The 4 Most Common SAT Algebra Traps**\n\n"
        "- **Trap 1 — Solving for the wrong thing:** You find x = 5 but the question asks for 2x + 3. Always re-read the final question before selecting your answer.\n"
        "- **Trap 2 — Assuming a unique solution:** A system problem may have no solution or infinitely many. Check before assuming one unique (x, y) pair exists.\n"
        "- **Trap 3 — Forgetting both solutions of an absolute value equation:** |x - 3| = 7 gives x = 10 AND x = -4. The SAT may list both as separate answer choices.\n"
        "- **Trap 4 — Misreading “no solution” as x = 0:** “No solution” means there is no value of x that works — not that x equals zero. x = 0 is a perfectly valid solution to many equations.\n\n"
        "**Common SAT Traps**\n\n"
        "- Rushing through the setup and solving for the right variable but wrong expression.\n"
        "- Choosing plugging-in when backsolving would be faster (and vice versa).\n"
        "- Spending too long on a difficult problem and running out of time for easy problems later in the section.\n\n"
        "**Tip:** After circling your answer, re-read the question one final time. Confirm you answered exactly what was asked. This 5-second habit catches “solving for the wrong thing” errors that cost students 2–4 points per test."
    ),
]


class Command(BaseCommand):
    help = "Enrich lesson content for SAT Math: Algebra"

    def handle(self, *args, **options):
        for order, content in LESSONS:
            rows = Lesson.objects.filter(
                course__slug="sat-math-algebra", order=order
            ).update(content=content)
            self.stdout.write(f"  Lesson {order}: {rows} row(s) updated")
        self.stdout.write(
            self.style.SUCCESS("Done enriching SAT Math: Algebra lessons.")
        )
