# Generated by Django 5.2.15 on 2026-06-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('essay', 'Essay / Free Response')], default='mcq', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='rubric',
            field=models.TextField(blank=True, help_text='Grading rubric/guidance for essay questions.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Question text'),
        ),
    ]
