# Generated by Django 5.2.15 on 2026-06-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_alter_question_difficulty_alter_question_qtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('mcq', 'Multiple Choice')], default='mcq', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='rubric',
            field=models.TextField(blank=True, help_text='Reserved for a later written-response phase.'),
        ),
    ]
