# Generated by Django 5.2.15 on 2026-06-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_remove_essay_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('written', 'Written Response')], default='mcq', max_length=10),
        ),
    ]
